// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package linksdb

import (
	"context"
)

// Querier is every query in this package, with one signature per query
// regardless of which dialect answers it.
//
// That is the point of this package: the params type, the row type, and the
// method signature are the same on every dialect, so nothing above this line
// knows or cares which database is underneath.
//
// # A note on the :execrows count
//
// MySQL reports rows *changed*: an UPDATE that sets a column to the value it
// already held affects zero rows there. Postgres and SQLite report rows
// *matched*, and count that same UPDATE as one.
//
// So a statement that gates on the count — treating zero as "not found" — is
// correct on two engines and wrong on the third. Either give it a predicate
// that discriminates, or set clientFoundRows=true in the MySQL DSN, which
// switches MySQL to matched semantics.
type Querier interface {
	// GetLink runs the :one query.
	GetLink(ctx context.Context, db DBTX, arg GetLinkParams) (GetLinkRow, error)
	// InsertLink runs the :exec query.
	InsertLink(ctx context.Context, db DBTX, arg InsertLinkParams) error
	// ResolveLink runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	ResolveLink(ctx context.Context, db DBTX, arg ResolveLinkParams) (int64, error)
	// SweepLinks runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	SweepLinks(ctx context.Context, db DBTX, arg SweepLinksParams) (int64, error)
}
