// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package linksdb

import (
	"context"
	"strings"
	"time"
)

const getLinkMySQL = `SELECT
	{{prefix}}action_links.action,
	{{prefix}}action_links.subject,
	{{prefix}}action_links.metadata,
	{{prefix}}action_links.state,
	{{prefix}}action_links.version,
	{{prefix}}action_links.created_at,
	{{prefix}}action_links.expires_at,
	{{prefix}}action_links.resolved_at,
	{{prefix}}action_links.purge_after
FROM {{prefix}}action_links
WHERE {{prefix}}action_links.id = ?`

const insertLinkMySQL = `
INSERT INTO {{prefix}}action_links (
	id,
	action,
	subject,
	metadata,
	state,
	version,
	created_at,
	expires_at,
	resolved_at,
	purge_after
) VALUES (
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?
)`

const resolveLinkMySQL = `UPDATE {{prefix}}action_links SET
	state = ?,
	resolved_at = ?,
	purge_after = ?
WHERE id = ?
	AND resolved_at IS NULL`

const sweepLinksMySQL = `DELETE FROM {{prefix}}action_links
WHERE purge_after <= ?`

// mysqlQueries answers every query in Querier against mysql.
type mysqlQueries struct {
	getLink     string
	insertLink  string
	resolveLink string
	sweepLinks  string
}

// newMySQL returns the mysql querier with prefix substituted into every
// table name the analyzer identified.
func newMySQL(prefix string) *mysqlQueries {
	return &mysqlQueries{
		getLink:     strings.ReplaceAll(getLinkMySQL, prefixMarker, prefix),
		insertLink:  strings.ReplaceAll(insertLinkMySQL, prefixMarker, prefix),
		resolveLink: strings.ReplaceAll(resolveLinkMySQL, prefixMarker, prefix),
		sweepLinks:  strings.ReplaceAll(sweepLinksMySQL, prefixMarker, prefix),
	}
}

// GetLink runs the :one query against mysql.
func (q *mysqlQueries) GetLink(ctx context.Context, db DBTX, arg GetLinkParams) (GetLinkRow, error) {
	row := db.QueryRowContext(ctx, q.getLink,
		arg.ID,
	)

	var i GetLinkRow

	err := row.Scan(
		&i.Action,
		&i.Subject,
		&i.Metadata,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ResolvedAt,
		&i.PurgeAfter,
	)

	return i, err
}

// InsertLink runs the :exec query against mysql.
func (q *mysqlQueries) InsertLink(ctx context.Context, db DBTX, arg InsertLinkParams) error {
	_, err := db.ExecContext(ctx, q.insertLink,
		arg.ID,
		arg.Action,
		arg.Subject,
		arg.Metadata,
		arg.State,
		arg.Version,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ResolvedAt,
		arg.PurgeAfter,
	)

	return err
}

// ResolveLink runs the :execrows query against mysql.
func (q *mysqlQueries) ResolveLink(ctx context.Context, db DBTX, arg ResolveLinkParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.resolveLink,
		arg.State,
		arg.ResolvedAt,
		arg.PurgeAfter,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// SweepLinks runs the :execrows query against mysql.
func (q *mysqlQueries) SweepLinks(ctx context.Context, db DBTX, arg SweepLinksParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.sweepLinks,
		arg.PurgeBefore,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		ID string
	}(GetLinkParams{})
	_ = struct {
		Action     string
		Subject    string
		Metadata   []byte
		State      int64
		Version    int64
		CreatedAt  time.Time
		ExpiresAt  time.Time
		ResolvedAt *time.Time
		PurgeAfter time.Time
	}(GetLinkRow{})
	_ = struct {
		ID         string
		Action     string
		Subject    string
		Metadata   []byte
		State      int64
		Version    int64
		CreatedAt  time.Time
		ExpiresAt  time.Time
		ResolvedAt *time.Time
		PurgeAfter time.Time
	}(InsertLinkParams{})
	_ = struct {
		State      int64
		ResolvedAt *time.Time
		PurgeAfter time.Time
		ID         string
	}(ResolveLinkParams{})
	_ = struct {
		PurgeBefore time.Time
	}(SweepLinksParams{})
)
