// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package linksdb

import (
	"context"
	"strings"
	"time"
)

const getLinkSQLite = `SELECT
	{{prefix}}action_links.action,
	{{prefix}}action_links.subject,
	{{prefix}}action_links.metadata,
	{{prefix}}action_links.state,
	{{prefix}}action_links.version,
	{{prefix}}action_links.created_at,
	{{prefix}}action_links.expires_at,
	{{prefix}}action_links.resolved_at,
	{{prefix}}action_links.purge_after
FROM {{prefix}}action_links
WHERE {{prefix}}action_links.id = ?1`

const insertLinkSQLite = `
INSERT INTO {{prefix}}action_links (
	id,
	action,
	subject,
	metadata,
	state,
	version,
	created_at,
	expires_at,
	resolved_at,
	purge_after
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	?8,
	?9,
	?10
)`

const resolveLinkSQLite = `UPDATE {{prefix}}action_links SET
	state = ?1,
	resolved_at = ?2,
	purge_after = ?3
WHERE id = ?4
	AND resolved_at IS NULL`

const revokeSubjectLinksSQLite = `UPDATE {{prefix}}action_links SET
	state = ?1,
	resolved_at = ?2,
	purge_after = ?3
WHERE subject = ?4
	AND resolved_at IS NULL`

const sweepLinksSQLite = `DELETE FROM {{prefix}}action_links
WHERE purge_after <= ?1`

// sqliteQueries answers every query in Querier against sqlite.
type sqliteQueries struct {
	getLink            string
	insertLink         string
	resolveLink        string
	revokeSubjectLinks string
	sweepLinks         string
}

// newSQLite returns the sqlite querier with prefix substituted into every
// table name the analyzer identified.
func newSQLite(prefix string) *sqliteQueries {
	return &sqliteQueries{
		getLink:            strings.ReplaceAll(getLinkSQLite, prefixMarker, prefix),
		insertLink:         strings.ReplaceAll(insertLinkSQLite, prefixMarker, prefix),
		resolveLink:        strings.ReplaceAll(resolveLinkSQLite, prefixMarker, prefix),
		revokeSubjectLinks: strings.ReplaceAll(revokeSubjectLinksSQLite, prefixMarker, prefix),
		sweepLinks:         strings.ReplaceAll(sweepLinksSQLite, prefixMarker, prefix),
	}
}

// timeText renders a time argument as the text this engine stores timestamps as.
//
// This engine has no date type: a DATETIME column holds text, and a comparison
// between two of them compares two strings. What a driver writes for a bound
// time.Time is Go's own rendering of it, whose leading characters happen to be
// the stored shape — but only while the value is UTC. A time carrying any other
// zone puts its own wall clock in those leading characters, so every window
// comparison is off by that offset, silently, and only for the callers whose
// clock is not UTC.
//
// Converting here is what makes the bound text the stored shape by
// construction rather than by accident, whatever zone the caller's time
// carries. The layout is whole seconds, which is what CURRENT_TIMESTAMP writes,
// so a bound value and a stored one are one shape rather than two that sort
// alike — which does mean a sub-second time bound here is stored truncated to
// the second on this engine.
func timeText(t time.Time) string {
	return t.UTC().Format("2006-01-02 15:04:05")
}

// timeTextPtr is timeText for a nullable argument. It preserves nil, so a
// field the caller left unset still binds NULL rather than the zero time.
func timeTextPtr(t *time.Time) any {
	if t == nil {
		return nil
	}

	return timeText(*t)
}

// GetLink runs the :one query against sqlite.
func (q *sqliteQueries) GetLink(ctx context.Context, db DBTX, arg GetLinkParams) (GetLinkRow, error) {
	row := db.QueryRowContext(ctx, q.getLink,
		arg.ID,
	)

	var i GetLinkRow

	err := row.Scan(
		&i.Action,
		&i.Subject,
		&i.Metadata,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ResolvedAt,
		&i.PurgeAfter,
	)

	return i, err
}

// InsertLink runs the :exec query against sqlite.
func (q *sqliteQueries) InsertLink(ctx context.Context, db DBTX, arg InsertLinkParams) error {
	_, err := db.ExecContext(ctx, q.insertLink,
		arg.ID,
		arg.Action,
		arg.Subject,
		arg.Metadata,
		arg.State,
		arg.Version,
		timeText(arg.CreatedAt),
		timeText(arg.ExpiresAt),
		timeTextPtr(arg.ResolvedAt),
		timeText(arg.PurgeAfter),
	)

	return err
}

// ResolveLink runs the :execrows query against sqlite.
func (q *sqliteQueries) ResolveLink(ctx context.Context, db DBTX, arg ResolveLinkParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.resolveLink,
		arg.State,
		timeTextPtr(arg.ResolvedAt),
		timeText(arg.PurgeAfter),
		arg.ID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// RevokeSubjectLinks runs the :execrows query against sqlite.
func (q *sqliteQueries) RevokeSubjectLinks(ctx context.Context, db DBTX, arg RevokeSubjectLinksParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.revokeSubjectLinks,
		arg.State,
		timeTextPtr(arg.ResolvedAt),
		timeText(arg.PurgeAfter),
		arg.Subject,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// SweepLinks runs the :execrows query against sqlite.
func (q *sqliteQueries) SweepLinks(ctx context.Context, db DBTX, arg SweepLinksParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.sweepLinks,
		timeText(arg.PurgeBefore),
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		ID string
	}(GetLinkParams{})
	_ = struct {
		Action     string
		Subject    string
		Metadata   []byte
		State      int64
		Version    int64
		CreatedAt  time.Time
		ExpiresAt  time.Time
		ResolvedAt *time.Time
		PurgeAfter time.Time
	}(GetLinkRow{})
	_ = struct {
		ID         string
		Action     string
		Subject    string
		Metadata   []byte
		State      int64
		Version    int64
		CreatedAt  time.Time
		ExpiresAt  time.Time
		ResolvedAt *time.Time
		PurgeAfter time.Time
	}(InsertLinkParams{})
	_ = struct {
		State      int64
		ResolvedAt *time.Time
		PurgeAfter time.Time
		ID         string
	}(ResolveLinkParams{})
	_ = struct {
		State      int64
		ResolvedAt *time.Time
		PurgeAfter time.Time
		Subject    string
	}(RevokeSubjectLinksParams{})
	_ = struct {
		PurgeBefore time.Time
	}(SweepLinksParams{})
)
