// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package linksdb

import (
	"time"
)

// GetLinkParams are the arguments to GetLink.
type GetLinkParams struct {
	ID string
}

// GetLinkRow is one row of GetLink's result.
type GetLinkRow struct {
	Action     string
	Subject    string
	Metadata   []byte
	State      int64
	Version    int64
	CreatedAt  time.Time
	ExpiresAt  time.Time
	ResolvedAt *time.Time
	PurgeAfter time.Time
}

// InsertLinkParams are the arguments to InsertLink.
type InsertLinkParams struct {
	ID         string
	Action     string
	Subject    string
	Metadata   []byte
	State      int64
	Version    int64
	CreatedAt  time.Time
	ExpiresAt  time.Time
	ResolvedAt *time.Time
	PurgeAfter time.Time
}

// ResolveLinkParams are the arguments to ResolveLink.
type ResolveLinkParams struct {
	State      int64
	ResolvedAt *time.Time
	PurgeAfter time.Time
	ID         string
}

// SweepLinksParams are the arguments to SweepLinks.
type SweepLinksParams struct {
	PurgeBefore time.Time
}
