package catalogen

import (
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	platformerrors "github.com/primandproper/platform-go/v10/errors"

	"github.com/shoenig/test"
	"github.com/shoenig/test/must"
)

// domainTree writes a miniature domain tree and returns the directory holding
// it. The files it writes cover what a real one has: the long constant suffix
// most events use, the short one a dozen identity events use, a doc comment on
// a grouped spec and one on a lone declaration, and a package the scan must not
// descend into.
func domainTree(t *testing.T) string {
	t.Helper()

	dir := t.TempDir()

	writeGo(t, filepath.Join(dir, "orders", "events.go"), `package orders

type ServiceEventType string

const (
	// OrderCreatedServiceEventType fires when an order is placed.
	OrderCreatedServiceEventType ServiceEventType = "order.created"

	// OrderShippedServiceEventType fires when an order leaves the warehouse.
	OrderShippedServiceEventType ServiceEventType = "order.shipped"
)
`)

	// The short suffix: the same publishing path, a different naming habit.
	writeGo(t, filepath.Join(dir, "identity", "events.go"), `package identity

// PasswordChangedEventType fires when a user changes their password.
const PasswordChangedEventType = "user.password_changed"
`)

	// Vendored code is not this application's domain.
	writeGo(t, filepath.Join(dir, "vendor", "elsewhere", "events.go"), `package elsewhere

const VendoredEventType = "vendored.event"
`)

	// Neither is a fixture, nor a test file beside real code.
	writeGo(t, filepath.Join(dir, "orders", "testdata", "events.go"), `package testdata

const FixtureEventType = "fixture.event"
`)
	writeGo(t, filepath.Join(dir, "orders", "events_test.go"), `package orders

const TestOnlyEventType = "test.only"
`)

	return dir
}

func writeGo(t *testing.T, path, contents string) {
	t.Helper()

	must.NoError(t, os.MkdirAll(filepath.Dir(path), 0o750))
	must.NoError(t, os.WriteFile(path, []byte(contents), 0o600))
}

// optionsFor pairs a domain tree with an output path outside it.
func optionsFor(t *testing.T, dir string) Options {
	t.Helper()

	return Options{
		Dir:        dir,
		OutputPath: filepath.Join(t.TempDir(), "catalog", "catalog.go"),
		Package:    "catalog",
	}
}

func TestGenerate(T *testing.T) {
	T.Parallel()

	T.Run("derives the catalog from the constants", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))

		must.NoError(t, Generate(opts))

		generated := read(t, opts.OutputPath)

		test.StrContains(t, generated, `"order.created": {Description: "Fires when an order is placed."}`)
		test.StrContains(t, generated, `"order.shipped": {Description: "Fires when an order leaves the warehouse."}`)

		// The short suffix is the whole reason the default is EventType rather
		// than ServiceEventType: this event is published like the rest, and
		// collecting only the longer form leaves it failing the dispatch gate.
		test.StrContains(t, generated, `"user.password_changed": {Description: "Fires when a user changes their password."}`)

		// The constant's name travels with the entry, which is what turns an
		// event type read here back into the declaration it came from.
		test.StrContains(t, generated, "// OrderCreatedServiceEventType")

		test.StrContains(t, generated, "// Code generated by webhooks/catalogen. DO NOT EDIT.")
		test.StrContains(t, generated, "package catalog\n")
		test.StrContains(t, generated, `import "github.com/primandproper/platform-go/v10/webhooks"`)
		test.StrContains(t, generated, "var Catalog = webhooks.Catalog{")
	})

	T.Run("collects nothing from vendor, testdata, or test files", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))

		must.NoError(t, Generate(opts))

		generated := read(t, opts.OutputPath)

		test.StrNotContains(t, generated, "vendored.event")
		test.StrNotContains(t, generated, "fixture.event")
		test.StrNotContains(t, generated, "test.only")
	})

	T.Run("the output parses as Go and is gofmt'd", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))

		must.NoError(t, Generate(opts))

		generated := read(t, opts.OutputPath)

		_, err := parser.ParseFile(token.NewFileSet(), opts.OutputPath, generated, parser.SkipObjectResolution)
		must.NoError(t, err)

		formatted, err := format.Source([]byte(generated))
		must.NoError(t, err)
		test.Eq(t, generated, string(formatted))
	})

	T.Run("is deterministic across runs", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))

		must.NoError(t, Generate(opts))
		first := read(t, opts.OutputPath)

		must.NoError(t, Generate(opts))
		test.Eq(t, first, read(t, opts.OutputPath))

		// Sorted by event type, so the file order does not follow whichever
		// order the filesystem walked in.
		user := strings.Index(first, `"user.password_changed"`)
		order := strings.Index(first, `"order.created"`)
		test.Less(t, user, order)
	})

	T.Run("creates the output directory", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))
		opts.OutputPath = filepath.Join(t.TempDir(), "a", "b", "c", "catalog.go")
		opts.Package = "c"

		must.NoError(t, Generate(opts))
		test.StrContains(t, read(t, opts.OutputPath), "package c\n")
	})

	T.Run("does not read its own previous output", func(t *testing.T) {
		t.Parallel()

		// The generated catalog usually lives under the tree it is generated
		// from, so a second run walks over it.
		dir := domainTree(t)

		opts := Options{
			Dir:        dir,
			OutputPath: filepath.Join(dir, "webhooks", "catalog", "catalog.go"),
			Package:    "catalog",
		}

		must.NoError(t, Generate(opts))
		first := read(t, opts.OutputPath)

		must.NoError(t, Generate(opts))
		test.Eq(t, first, read(t, opts.OutputPath))
		must.NoError(t, Check(opts))
	})

	T.Run("writes nothing when the derivation fails", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))

		must.NoError(t, Generate(opts))
		good := read(t, opts.OutputPath)

		writeGo(t, filepath.Join(opts.Dir, "orders", "broken.go"), `package orders

const CountedEventType = 3
`)

		test.ErrorIs(t, Generate(opts), ErrNotAStringConstant)
		test.Eq(t, good, read(t, opts.OutputPath))
	})
}

func TestGenerateFailures(T *testing.T) {
	T.Parallel()

	T.Run("an empty catalog is an error, not an empty file", func(t *testing.T) {
		t.Parallel()

		// An empty catalog rejects every dispatch, and the cause is a mistyped
		// Dir or Suffix far more often than an application with no events.
		opts := optionsFor(t, domainTree(t))
		opts.Suffix = "NotASuffixAnythingUses"

		err := Generate(opts)

		test.ErrorIs(t, err, ErrNoEventTypes)
		test.False(t, exists(opts.OutputPath))
	})

	T.Run("a duplicate event type names both constants", func(t *testing.T) {
		t.Parallel()

		dir := domainTree(t)
		writeGo(t, filepath.Join(dir, "billing", "events.go"), `package billing

// OrderCreatedAgainEventType duplicates an event another package declares.
const OrderCreatedAgainEventType = "order.created"
`)

		err := Generate(optionsFor(t, dir))

		must.ErrorIs(t, err, ErrDuplicateEventType)
		test.StrContains(t, err.Error(), "order.created")
		test.StrContains(t, err.Error(), "OrderCreatedAgainEventType")
		test.StrContains(t, err.Error(), "OrderCreatedServiceEventType")
	})

	T.Run("a non-string constant is reported rather than skipped", func(t *testing.T) {
		t.Parallel()

		// Skipping it is what produces the missing catalog entry, which is a
		// failed dispatch rather than a missing webhook.
		dir := domainTree(t)
		writeGo(t, filepath.Join(dir, "counting", "events.go"), `package counting

type EventType int

const (
	FirstEventType EventType = iota
	SecondEventType
)
`)

		err := Generate(optionsFor(t, dir))

		must.ErrorIs(t, err, ErrNotAStringConstant)
		test.StrContains(t, err.Error(), "FirstEventType")
	})

	T.Run("a name with no value of its own is reported", func(t *testing.T) {
		t.Parallel()

		dir := domainTree(t)
		writeGo(t, filepath.Join(dir, "aliasing", "events.go"), `package aliasing

const (
	DeclaredEventType = "declared.event"
	RepeatedEventType
)
`)

		err := Generate(optionsFor(t, dir))

		must.ErrorIs(t, err, ErrNotAStringConstant)
		test.StrContains(t, err.Error(), "RepeatedEventType")
	})

	T.Run("an empty event type is reported", func(t *testing.T) {
		t.Parallel()

		dir := domainTree(t)
		writeGo(t, filepath.Join(dir, "blank", "events.go"), `package blank

// UnsetEventType is not an event anything can subscribe to.
const UnsetEventType = ""
`)

		test.ErrorIs(t, Generate(optionsFor(t, dir)), ErrEmptyEventType)
	})

	T.Run("unparseable source fails the whole run", func(t *testing.T) {
		t.Parallel()

		dir := domainTree(t)
		writeGo(t, filepath.Join(dir, "broken", "events.go"), "package broken\n\nconst = = =\n")

		err := Generate(optionsFor(t, dir))

		must.Error(t, err)
		test.StrContains(t, err.Error(), "parsing")
	})

	T.Run("a missing directory fails", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, filepath.Join(t.TempDir(), "nonexistent"))

		must.Error(t, Generate(opts))
		test.False(t, exists(opts.OutputPath))
	})
}

func TestOptions(T *testing.T) {
	T.Parallel()

	T.Run("defaults the suffix, the package, and the variable", func(t *testing.T) {
		t.Parallel()

		opts := Options{
			Dir:        domainTree(t),
			OutputPath: filepath.Join(t.TempDir(), "catalog", "catalog.go"),
		}

		must.NoError(t, Generate(opts))

		generated := read(t, opts.OutputPath)

		test.StrContains(t, generated, "package catalog\n")
		test.StrContains(t, generated, "var Catalog = webhooks.Catalog{")
		test.StrContains(t, generated, "Source: constants ending in EventType under")
	})

	T.Run("honors an explicit suffix", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))
		opts.Suffix = "ServiceEventType"

		must.NoError(t, Generate(opts))

		generated := read(t, opts.OutputPath)

		test.StrContains(t, generated, "order.created")
		test.StrNotContains(t, generated, "user.password_changed")
	})

	T.Run("honors an explicit variable name", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))
		opts.VarName = "All"

		must.NoError(t, Generate(opts))
		test.StrContains(t, read(t, opts.OutputPath), "var All = webhooks.Catalog{")
	})

	T.Run("rejects the options it cannot generate from", func(t *testing.T) {
		t.Parallel()

		valid := optionsFor(t, domainTree(t))

		for _, tc := range []struct {
			wantErr error
			mutate  func(*Options)
			name    string
		}{
			{
				name:    "no directory",
				mutate:  func(o *Options) { o.Dir = "" },
				wantErr: ErrNoDir,
			},
			{
				name:    "no output path",
				mutate:  func(o *Options) { o.OutputPath = "" },
				wantErr: ErrNoOutputPath,
			},
			{
				name:    "package name is not an identifier",
				mutate:  func(o *Options) { o.Package = "not-an-identifier" },
				wantErr: ErrInvalidPackageName,
			},
			{
				name:    "package name is a keyword",
				mutate:  func(o *Options) { o.Package = "range" },
				wantErr: ErrInvalidPackageName,
			},
			{
				name:    "package derived from a directory that is not an identifier",
				mutate:  func(o *Options) { o.Package, o.OutputPath = "", filepath.Join(t.TempDir(), "web-hooks", "catalog.go") },
				wantErr: ErrInvalidPackageName,
			},
			{
				name:    "variable name is not an identifier",
				mutate:  func(o *Options) { o.VarName = "2Catalog" },
				wantErr: ErrInvalidVarName,
			},
		} {
			t.Run(tc.name, func(t *testing.T) {
				t.Parallel()

				opts := valid
				tc.mutate(&opts)

				test.ErrorIs(t, Generate(opts), tc.wantErr)
				test.ErrorIs(t, Check(opts), tc.wantErr)
			})
		}
	})

	T.Run("the empty-input errors are platform errors", func(t *testing.T) {
		t.Parallel()

		test.ErrorIs(t, ErrNoDir, platformerrors.ErrEmptyInputParameter)
		test.ErrorIs(t, ErrNoOutputPath, platformerrors.ErrEmptyInputParameter)
	})
}

func TestCheck(T *testing.T) {
	T.Parallel()

	T.Run("passes on a catalog that matches", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))

		must.NoError(t, Generate(opts))
		test.NoError(t, Check(opts))
	})

	T.Run("writes nothing", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))

		test.Error(t, Check(opts))
		test.False(t, exists(opts.OutputPath))
	})

	T.Run("fails when there is no catalog at all", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))

		err := Check(opts)

		must.ErrorIs(t, err, ErrCatalogOutOfDate)
		test.StrContains(t, err.Error(), "no catalog at")
	})

	T.Run("names an event the constants added", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))
		must.NoError(t, Generate(opts))

		// The failure this whole package exists for: a new domain event, and a
		// catalog nobody remembered to update.
		writeGo(t, filepath.Join(opts.Dir, "shipping", "events.go"), `package shipping

// LabelPrintedServiceEventType fires when a shipping label is printed.
const LabelPrintedServiceEventType = "shipping.label_printed"
`)

		err := Check(opts)

		must.ErrorIs(t, err, ErrCatalogOutOfDate)
		test.StrContains(t, err.Error(), "1 missing (shipping.label_printed)")
	})

	T.Run("names an event the constants dropped", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))
		must.NoError(t, Generate(opts))

		must.NoError(t, os.Remove(filepath.Join(opts.Dir, "identity", "events.go")))

		err := Check(opts)

		must.ErrorIs(t, err, ErrCatalogOutOfDate)
		test.StrContains(t, err.Error(), "1 no longer declared (user.password_changed)")
	})

	T.Run("names an event whose description changed", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))
		must.NoError(t, Generate(opts))

		writeGo(t, filepath.Join(opts.Dir, "identity", "events.go"), `package identity

// PasswordChangedEventType fires when a password is rotated, by the user or an admin.
const PasswordChangedEventType = "user.password_changed"
`)

		err := Check(opts)

		must.ErrorIs(t, err, ErrCatalogOutOfDate)
		test.StrContains(t, err.Error(), "1 redescribed (user.password_changed)")
	})

	T.Run("reports every category at once", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))
		must.NoError(t, Generate(opts))

		writeGo(t, filepath.Join(opts.Dir, "identity", "events.go"), `package identity

// PasswordChangedEventType fires when a password is rotated.
const PasswordChangedEventType = "user.password_changed"

// SessionRevokedEventType fires when a session is revoked.
const SessionRevokedEventType = "user.session_revoked"
`)
		must.NoError(t, os.Remove(filepath.Join(opts.Dir, "orders", "events.go")))

		err := Check(opts)

		must.ErrorIs(t, err, ErrCatalogOutOfDate)
		test.StrContains(t, err.Error(), "1 missing (user.session_revoked)")
		test.StrContains(t, err.Error(), "2 no longer declared (order.created, order.shipped)")
		test.StrContains(t, err.Error(), "1 redescribed (user.password_changed)")
	})

	T.Run("fails on a hand-written file that is not a catalog", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))
		writeGo(t, opts.OutputPath, "package catalog\n\nconst Nothing = \"here\"\n")

		err := Check(opts)

		must.ErrorIs(t, err, ErrCatalogOutOfDate)
		test.StrContains(t, err.Error(), "does not declare a webhooks.Catalog named Catalog")
	})

	T.Run("fails when only the file around the entries differs", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))
		must.NoError(t, Generate(opts))

		// The entries are right, the header the generator writes today is not.
		generated := read(t, opts.OutputPath)
		writeGo(t, opts.OutputPath, strings.Replace(generated, "// Code generated", "// code generated", 1))

		err := Check(opts)

		must.ErrorIs(t, err, ErrCatalogOutOfDate)
		test.StrContains(t, err.Error(), "the entries match but the generated file does not")
	})

	T.Run("fails when the committed catalog was edited by hand", func(t *testing.T) {
		t.Parallel()

		opts := optionsFor(t, domainTree(t))
		must.NoError(t, Generate(opts))

		generated := read(t, opts.OutputPath)
		writeGo(t, opts.OutputPath, strings.Replace(generated, "order.created", "order.craeted", 1))

		err := Check(opts)

		must.ErrorIs(t, err, ErrCatalogOutOfDate)
		test.StrContains(t, err.Error(), "order.created")
		test.StrContains(t, err.Error(), "order.craeted")
	})
}

func read(t *testing.T, path string) string {
	t.Helper()

	contents, err := os.ReadFile(path)
	must.NoError(t, err)

	return string(contents)
}

func exists(path string) bool {
	_, err := os.Stat(path)

	return err == nil
}
