package catalogen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"reflect"
	"slices"
	"strings"

	platformerrors "github.com/primandproper/platform-go/v10/errors"
	"github.com/primandproper/platform-go/v10/webhooks"
)

// The import the generated file needs, taken from the type it declares rather
// than written out as a string, so that a major version bump moves the
// generated import along with everything else.
var (
	catalogImportPath = reflect.TypeOf(webhooks.EventDefinition{}).PkgPath()
	catalogPkgName    = path.Base(catalogImportPath)
)

// driftListLimit caps how many event types Check names per category. The
// message exists to point at what changed; a catalog that grew by two hundred
// events has one cause, and listing all of them buries it.
const driftListLimit = 8

// descriptionField is the field of webhooks.EventDefinition the generated
// entries set, and the one Check reads back when explaining a mismatch.
const descriptionField = "Description"

// render writes the catalog file for a resolved set of options. The result is
// gofmt'd, so what lands on disk is what a formatter would leave there and a
// repo running one over its generated files sees no diff.
func render(opts *Options, entries []entry) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by %s/catalogen. DO NOT EDIT.\n", catalogPkgName)
	fmt.Fprintf(&buf, "//\n// Source: constants ending in %s under %s.\n\n", opts.Suffix, sourceDir(opts.Dir))
	fmt.Fprintf(&buf, "package %s\n\n", opts.Package)
	fmt.Fprintf(&buf, "import %q\n\n", catalogImportPath)

	fmt.Fprintf(&buf, "// %s is every event type this application publishes, and the value\n", opts.VarName)
	fmt.Fprintf(&buf, "// %s.WithCatalog takes: an event type outside it can be neither\n", catalogPkgName)
	fmt.Fprintf(&buf, "// subscribed to nor dispatched.\n//\n")
	fmt.Fprintf(&buf, "// Each entry's description is the doc comment of the constant named beside\n")
	fmt.Fprintf(&buf, "// it, so editing this file loses the change on the next generation. Edit\n")
	fmt.Fprintf(&buf, "// the constant instead.\n")
	fmt.Fprintf(&buf, "var %s = %s.Catalog{\n", opts.VarName, catalogPkgName)

	for i := range entries {
		e := &entries[i]

		fmt.Fprintf(&buf, "\t// %s\n", e.constName)
		fmt.Fprintf(&buf, "\t%q: {%s: %q},\n", e.eventType, descriptionField, e.description)
	}

	buf.WriteString("}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, platformerrors.Wrap(err, "formatting the generated catalog")
	}

	return src, nil
}

// sourceDir renders the scanned tree for the generated file's header, in slash
// form so the file reads the same on either kind of filesystem.
//
// An absolute Dir underneath the working directory is written relative to it.
// A generator is run from the root of the repository it generates into, so that
// is the repository-relative path — and the alternative is a checked-in file
// naming whoever's home directory last generated it, which every other
// developer's run would then rewrite.
func sourceDir(dir string) string {
	cleaned := filepath.Clean(dir)

	if filepath.IsAbs(cleaned) {
		if cwd, err := os.Getwd(); err == nil {
			if rel, relErr := filepath.Rel(cwd, cleaned); relErr == nil && !strings.HasPrefix(rel, "..") {
				cleaned = rel
			}
		}
	}

	return filepath.ToSlash(cleaned)
}

// describeDrift explains, in one line, how the committed catalog differs from
// the generated one. It is best-effort prose for an error message: a file it
// cannot read as a catalog is reported as such rather than diffed.
func describeDrift(committed, want []byte, varName string) string {
	have, haveOK := parseCatalog(committed, varName)
	if !haveOK {
		return fmt.Sprintf("the committed file does not declare a %s.Catalog named %s", catalogPkgName, varName)
	}

	expected, expectedOK := parseCatalog(want, varName)
	if !expectedOK {
		return "the committed file differs from the generated catalog"
	}

	var missing, unexpected, redescribed []string

	for eventType, description := range expected {
		switch committedDescription, ok := have[eventType]; {
		case !ok:
			missing = append(missing, eventType)
		case committedDescription != description:
			redescribed = append(redescribed, eventType)
		}
	}

	for eventType := range have {
		if _, ok := expected[eventType]; !ok {
			unexpected = append(unexpected, eventType)
		}
	}

	parts := []string{
		summarize("missing", missing),
		summarize("no longer declared", unexpected),
		summarize("redescribed", redescribed),
	}
	parts = slices.DeleteFunc(parts, func(s string) bool { return s == "" })

	if len(parts) == 0 {
		// The entries agree, so what differs is the file around them: the
		// package clause, the variable name, or a header this generator has
		// since changed.
		return "the entries match but the generated file does not; regenerate it"
	}

	return strings.Join(parts, ", ")
}

// summarize renders one category of drift, sorted for a stable message and
// truncated so a wholesale change does not fill the terminal.
func summarize(label string, eventTypes []string) string {
	if len(eventTypes) == 0 {
		return ""
	}

	slices.Sort(eventTypes)

	shown := eventTypes
	suffix := ""

	if len(shown) > driftListLimit {
		suffix = fmt.Sprintf(" and %d more", len(shown)-driftListLimit)
		shown = shown[:driftListLimit]
	}

	return fmt.Sprintf("%d %s (%s%s)", len(eventTypes), label, strings.Join(shown, ", "), suffix)
}

// parseCatalog reads the event types and descriptions back out of a rendered
// catalog file. It reports false for anything it cannot recognize as one,
// rather than an empty catalog, so a hand-written file is not described as
// having lost every event.
func parseCatalog(src []byte, varName string) (map[string]string, bool) {
	file, err := parser.ParseFile(token.NewFileSet(), "catalog.go", src, parser.SkipObjectResolution)
	if err != nil {
		return nil, false
	}

	for _, decl := range file.Decls {
		gen, isGenDecl := decl.(*ast.GenDecl)
		if !isGenDecl || gen.Tok != token.VAR {
			continue
		}

		for _, spec := range gen.Specs {
			valueSpec, isValueSpec := spec.(*ast.ValueSpec)
			if !isValueSpec {
				continue
			}

			for i, name := range valueSpec.Names {
				if name.Name != varName || i >= len(valueSpec.Values) {
					continue
				}

				literal, isLiteral := valueSpec.Values[i].(*ast.CompositeLit)
				if !isLiteral {
					return nil, false
				}

				return catalogFromLiteral(literal)
			}
		}
	}

	return nil, false
}

// catalogFromLiteral reads the entries of a webhooks.Catalog composite literal.
func catalogFromLiteral(literal *ast.CompositeLit) (map[string]string, bool) {
	catalog := make(map[string]string, len(literal.Elts))

	for _, elt := range literal.Elts {
		pair, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			return nil, false
		}

		eventType, ok := stringValue(pair.Key)
		if !ok {
			return nil, false
		}

		definition, ok := pair.Value.(*ast.CompositeLit)
		if !ok {
			return nil, false
		}

		catalog[eventType] = descriptionIn(definition)
	}

	return catalog, true
}

// descriptionIn reads the Description of one event definition literal. A
// literal that sets no fields describes an event with no prose, which is what
// an undocumented constant generates.
func descriptionIn(definition *ast.CompositeLit) string {
	for _, elt := range definition.Elts {
		pair, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}

		key, isIdent := pair.Key.(*ast.Ident)
		if !isIdent || key.Name != descriptionField {
			continue
		}

		if description, isString := stringValue(pair.Value); isString {
			return description
		}
	}

	return ""
}
