// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: dev

package identitydb

import (
	"context"
	"strings"
	"time"

	"github.com/primandproper/platform-go/v13/tenancy"
)

const answerInvitationMySQL = `UPDATE {{prefix}}identity_invitations SET
	status = ?,
	note = ?,
	to_user = ?,
	last_updated_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND id = ?
	AND scope = ?
	AND status = ?`

const archiveAccountMySQL = `UPDATE {{prefix}}identity_accounts SET
	archived_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND id = ?
	AND scope = ?`

const archiveUserMySQL = `UPDATE {{prefix}}identity_users SET
	archived_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND id = ?
	AND scope = ?`

const createAccountMySQL = `INSERT INTO {{prefix}}identity_accounts (
	id,
	scope,
	name,
	owner_user_id,
	billing_status,
	subscription_plan_id,
	payment_processor_customer_id,
	last_payment_provider_synced_at,
	address_line1,
	address_line2,
	address_city,
	address_state,
	address_postal_code,
	address_country,
	address_phone,
	time_zone
) VALUES (
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?
)`

const createInvitationMySQL = `INSERT INTO {{prefix}}identity_invitations (
	id,
	scope,
	belongs_to_account,
	from_user,
	to_email,
	to_name,
	to_user,
	token,
	status,
	note,
	expires_at
) VALUES (
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?
)`

const createUserMySQL = `
INSERT INTO {{prefix}}identity_users (
	id,
	scope,
	username,
	email_address,
	first_name,
	last_name,
	hashed_password,
	requires_password_change,
	password_last_changed_at,
	two_factor_secret,
	two_factor_secret_verified_at,
	email_address_verified_at,
	email_address_verification_token,
	account_status,
	account_status_explanation,
	last_accepted_terms_of_service,
	last_accepted_privacy_policy
) VALUES (
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?
)`

const getAccountMySQL = `SELECT
	{{prefix}}identity_accounts.id,
	{{prefix}}identity_accounts.scope,
	{{prefix}}identity_accounts.name,
	{{prefix}}identity_accounts.owner_user_id,
	{{prefix}}identity_accounts.billing_status,
	{{prefix}}identity_accounts.subscription_plan_id,
	{{prefix}}identity_accounts.payment_processor_customer_id,
	{{prefix}}identity_accounts.last_payment_provider_synced_at,
	{{prefix}}identity_accounts.address_line1,
	{{prefix}}identity_accounts.address_line2,
	{{prefix}}identity_accounts.address_city,
	{{prefix}}identity_accounts.address_state,
	{{prefix}}identity_accounts.address_postal_code,
	{{prefix}}identity_accounts.address_country,
	{{prefix}}identity_accounts.address_phone,
	{{prefix}}identity_accounts.time_zone,
	{{prefix}}identity_accounts.created_at,
	{{prefix}}identity_accounts.last_updated_at,
	{{prefix}}identity_accounts.archived_at
FROM {{prefix}}identity_accounts
WHERE {{prefix}}identity_accounts.archived_at IS NULL
	AND {{prefix}}identity_accounts.id = ?
	AND {{prefix}}identity_accounts.scope = ?`

const getAccountCreatedAtMySQL = `SELECT
	{{prefix}}identity_accounts.created_at
FROM {{prefix}}identity_accounts
WHERE {{prefix}}identity_accounts.id = ?`

const getInvitationMySQL = `SELECT
	{{prefix}}identity_invitations.id,
	{{prefix}}identity_invitations.scope,
	{{prefix}}identity_invitations.belongs_to_account,
	{{prefix}}identity_invitations.from_user,
	{{prefix}}identity_invitations.to_email,
	{{prefix}}identity_invitations.to_name,
	{{prefix}}identity_invitations.to_user,
	{{prefix}}identity_invitations.token,
	{{prefix}}identity_invitations.status,
	{{prefix}}identity_invitations.note,
	{{prefix}}identity_invitations.expires_at,
	{{prefix}}identity_invitations.created_at,
	{{prefix}}identity_invitations.last_updated_at,
	{{prefix}}identity_invitations.archived_at
FROM {{prefix}}identity_invitations
WHERE {{prefix}}identity_invitations.archived_at IS NULL
	AND {{prefix}}identity_invitations.id = ?
	AND {{prefix}}identity_invitations.scope = ?`

const getInvitationCreatedAtMySQL = `SELECT
	{{prefix}}identity_invitations.created_at
FROM {{prefix}}identity_invitations
WHERE {{prefix}}identity_invitations.id = ?`

const getMembershipByUserAndAccountMySQL = `SELECT
	{{prefix}}identity_memberships.id,
	{{prefix}}identity_memberships.scope,
	{{prefix}}identity_memberships.belongs_to_user,
	{{prefix}}identity_memberships.belongs_to_account,
	{{prefix}}identity_memberships.default_account,
	{{prefix}}identity_memberships.created_at,
	{{prefix}}identity_memberships.last_updated_at,
	{{prefix}}identity_memberships.archived_at
FROM {{prefix}}identity_memberships
WHERE {{prefix}}identity_memberships.archived_at IS NULL
	AND {{prefix}}identity_memberships.scope = ?
	AND {{prefix}}identity_memberships.belongs_to_user = ?
	AND {{prefix}}identity_memberships.belongs_to_account = ?`

const getMembershipFallbackAccountIDMySQL = `SELECT
	{{prefix}}identity_memberships.belongs_to_account
FROM {{prefix}}identity_memberships
WHERE {{prefix}}identity_memberships.archived_at IS NULL
	AND {{prefix}}identity_memberships.scope = ?
	AND {{prefix}}identity_memberships.belongs_to_user = ?
	AND {{prefix}}identity_memberships.belongs_to_account <> ?
ORDER BY {{prefix}}identity_memberships.belongs_to_account ASC
LIMIT 1`

const getMembershipIdbyUserAndAccountMySQL = `SELECT
	{{prefix}}identity_memberships.id
FROM {{prefix}}identity_memberships
WHERE {{prefix}}identity_memberships.archived_at IS NULL
	AND {{prefix}}identity_memberships.scope = ?
	AND {{prefix}}identity_memberships.belongs_to_user = ?
	AND {{prefix}}identity_memberships.belongs_to_account = ?`

const getUserMySQL = `SELECT
	{{prefix}}identity_users.id,
	{{prefix}}identity_users.scope,
	{{prefix}}identity_users.username,
	{{prefix}}identity_users.email_address,
	{{prefix}}identity_users.first_name,
	{{prefix}}identity_users.last_name,
	{{prefix}}identity_users.hashed_password,
	{{prefix}}identity_users.requires_password_change,
	{{prefix}}identity_users.password_last_changed_at,
	{{prefix}}identity_users.two_factor_secret,
	{{prefix}}identity_users.two_factor_secret_verified_at,
	{{prefix}}identity_users.email_address_verified_at,
	{{prefix}}identity_users.email_address_verification_token,
	{{prefix}}identity_users.account_status,
	{{prefix}}identity_users.account_status_explanation,
	{{prefix}}identity_users.last_accepted_terms_of_service,
	{{prefix}}identity_users.last_accepted_privacy_policy,
	{{prefix}}identity_users.created_at,
	{{prefix}}identity_users.last_updated_at,
	{{prefix}}identity_users.archived_at
FROM {{prefix}}identity_users
WHERE {{prefix}}identity_users.archived_at IS NULL
	AND {{prefix}}identity_users.id = ?
	AND {{prefix}}identity_users.scope = ?`

const getUserByEmailAddressMySQL = `SELECT
	{{prefix}}identity_users.id,
	{{prefix}}identity_users.scope,
	{{prefix}}identity_users.username,
	{{prefix}}identity_users.email_address,
	{{prefix}}identity_users.first_name,
	{{prefix}}identity_users.last_name,
	{{prefix}}identity_users.hashed_password,
	{{prefix}}identity_users.requires_password_change,
	{{prefix}}identity_users.password_last_changed_at,
	{{prefix}}identity_users.two_factor_secret,
	{{prefix}}identity_users.two_factor_secret_verified_at,
	{{prefix}}identity_users.email_address_verified_at,
	{{prefix}}identity_users.email_address_verification_token,
	{{prefix}}identity_users.account_status,
	{{prefix}}identity_users.account_status_explanation,
	{{prefix}}identity_users.last_accepted_terms_of_service,
	{{prefix}}identity_users.last_accepted_privacy_policy,
	{{prefix}}identity_users.created_at,
	{{prefix}}identity_users.last_updated_at,
	{{prefix}}identity_users.archived_at
FROM {{prefix}}identity_users
WHERE {{prefix}}identity_users.archived_at IS NULL
	AND {{prefix}}identity_users.email_address = ?
	AND {{prefix}}identity_users.scope = ?`

const getUserByEmailVerificationTokenMySQL = `SELECT
	{{prefix}}identity_users.id,
	{{prefix}}identity_users.scope,
	{{prefix}}identity_users.username,
	{{prefix}}identity_users.email_address,
	{{prefix}}identity_users.first_name,
	{{prefix}}identity_users.last_name,
	{{prefix}}identity_users.hashed_password,
	{{prefix}}identity_users.requires_password_change,
	{{prefix}}identity_users.password_last_changed_at,
	{{prefix}}identity_users.two_factor_secret,
	{{prefix}}identity_users.two_factor_secret_verified_at,
	{{prefix}}identity_users.email_address_verified_at,
	{{prefix}}identity_users.email_address_verification_token,
	{{prefix}}identity_users.account_status,
	{{prefix}}identity_users.account_status_explanation,
	{{prefix}}identity_users.last_accepted_terms_of_service,
	{{prefix}}identity_users.last_accepted_privacy_policy,
	{{prefix}}identity_users.created_at,
	{{prefix}}identity_users.last_updated_at,
	{{prefix}}identity_users.archived_at
FROM {{prefix}}identity_users
WHERE {{prefix}}identity_users.archived_at IS NULL
	AND {{prefix}}identity_users.email_address_verification_token = ?
	AND {{prefix}}identity_users.scope = ?`

const getUserByUsernameMySQL = `SELECT
	{{prefix}}identity_users.id,
	{{prefix}}identity_users.scope,
	{{prefix}}identity_users.username,
	{{prefix}}identity_users.email_address,
	{{prefix}}identity_users.first_name,
	{{prefix}}identity_users.last_name,
	{{prefix}}identity_users.hashed_password,
	{{prefix}}identity_users.requires_password_change,
	{{prefix}}identity_users.password_last_changed_at,
	{{prefix}}identity_users.two_factor_secret,
	{{prefix}}identity_users.two_factor_secret_verified_at,
	{{prefix}}identity_users.email_address_verified_at,
	{{prefix}}identity_users.email_address_verification_token,
	{{prefix}}identity_users.account_status,
	{{prefix}}identity_users.account_status_explanation,
	{{prefix}}identity_users.last_accepted_terms_of_service,
	{{prefix}}identity_users.last_accepted_privacy_policy,
	{{prefix}}identity_users.created_at,
	{{prefix}}identity_users.last_updated_at,
	{{prefix}}identity_users.archived_at
FROM {{prefix}}identity_users
WHERE {{prefix}}identity_users.archived_at IS NULL
	AND {{prefix}}identity_users.username = ?
	AND {{prefix}}identity_users.scope = ?`

const getUserCreatedAtMySQL = `SELECT
	{{prefix}}identity_users.created_at
FROM {{prefix}}identity_users
WHERE {{prefix}}identity_users.id = ?`

const listAccountMembersMySQL = `SELECT
	{{prefix}}identity_memberships.id,
	{{prefix}}identity_memberships.scope,
	{{prefix}}identity_memberships.belongs_to_user,
	{{prefix}}identity_memberships.belongs_to_account,
	{{prefix}}identity_memberships.default_account,
	{{prefix}}identity_memberships.created_at,
	{{prefix}}identity_memberships.last_updated_at,
	{{prefix}}identity_memberships.archived_at,
	{{prefix}}identity_users.id AS user_id,
	{{prefix}}identity_users.scope AS user_scope,
	{{prefix}}identity_users.username AS user_username,
	{{prefix}}identity_users.email_address AS user_email_address,
	{{prefix}}identity_users.first_name AS user_first_name,
	{{prefix}}identity_users.last_name AS user_last_name,
	{{prefix}}identity_users.hashed_password AS user_hashed_password,
	{{prefix}}identity_users.requires_password_change AS user_requires_password_change,
	{{prefix}}identity_users.password_last_changed_at AS user_password_last_changed_at,
	{{prefix}}identity_users.two_factor_secret AS user_two_factor_secret,
	{{prefix}}identity_users.two_factor_secret_verified_at AS user_two_factor_secret_verified_at,
	{{prefix}}identity_users.email_address_verified_at AS user_email_address_verified_at,
	{{prefix}}identity_users.email_address_verification_token AS user_email_address_verification_token,
	{{prefix}}identity_users.account_status AS user_account_status,
	{{prefix}}identity_users.account_status_explanation AS user_account_status_explanation,
	{{prefix}}identity_users.last_accepted_terms_of_service AS user_last_accepted_terms_of_service,
	{{prefix}}identity_users.last_accepted_privacy_policy AS user_last_accepted_privacy_policy,
	{{prefix}}identity_users.created_at AS user_created_at,
	{{prefix}}identity_users.last_updated_at AS user_last_updated_at,
	{{prefix}}identity_users.archived_at AS user_archived_at,
	(
		SELECT COUNT({{prefix}}identity_memberships.id)
		FROM {{prefix}}identity_memberships
		JOIN {{prefix}}identity_users ON {{prefix}}identity_memberships.belongs_to_user={{prefix}}identity_users.id
		WHERE {{prefix}}identity_memberships.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			AND {{prefix}}identity_memberships.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			AND (
				{{prefix}}identity_memberships.last_updated_at IS NULL
				OR {{prefix}}identity_memberships.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			)
			AND (
				{{prefix}}identity_memberships.last_updated_at IS NULL
				OR {{prefix}}identity_memberships.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			)
			AND (COALESCE(?, false) = true OR {{prefix}}identity_memberships.archived_at IS NULL)
			AND {{prefix}}identity_memberships.scope = ?
			AND {{prefix}}identity_memberships.belongs_to_account = ?
			AND {{prefix}}identity_users.archived_at IS NULL
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}identity_memberships.id)
		FROM {{prefix}}identity_memberships
		JOIN {{prefix}}identity_users ON {{prefix}}identity_memberships.belongs_to_user={{prefix}}identity_users.id
		WHERE (COALESCE(?, false) = true OR {{prefix}}identity_memberships.archived_at IS NULL)
			AND {{prefix}}identity_memberships.scope = ?
			AND {{prefix}}identity_memberships.belongs_to_account = ?
			AND {{prefix}}identity_users.archived_at IS NULL
	) AS total_count
FROM {{prefix}}identity_memberships
JOIN {{prefix}}identity_users ON {{prefix}}identity_memberships.belongs_to_user={{prefix}}identity_users.id
WHERE {{prefix}}identity_memberships.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	AND {{prefix}}identity_memberships.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	AND (
		{{prefix}}identity_memberships.last_updated_at IS NULL
		OR {{prefix}}identity_memberships.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	)
	AND (
		{{prefix}}identity_memberships.last_updated_at IS NULL
		OR {{prefix}}identity_memberships.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	)
	AND (COALESCE(?, false) = true OR {{prefix}}identity_memberships.archived_at IS NULL)
	AND {{prefix}}identity_memberships.scope = ?
	AND {{prefix}}identity_memberships.belongs_to_account = ?
	AND {{prefix}}identity_users.archived_at IS NULL
	AND {{prefix}}identity_memberships.id > COALESCE(?, '')
ORDER BY {{prefix}}identity_memberships.id ASC
LIMIT ?`

const listAccountsMySQL = `SELECT
	{{prefix}}identity_accounts.id,
	{{prefix}}identity_accounts.scope,
	{{prefix}}identity_accounts.name,
	{{prefix}}identity_accounts.owner_user_id,
	{{prefix}}identity_accounts.billing_status,
	{{prefix}}identity_accounts.subscription_plan_id,
	{{prefix}}identity_accounts.payment_processor_customer_id,
	{{prefix}}identity_accounts.last_payment_provider_synced_at,
	{{prefix}}identity_accounts.address_line1,
	{{prefix}}identity_accounts.address_line2,
	{{prefix}}identity_accounts.address_city,
	{{prefix}}identity_accounts.address_state,
	{{prefix}}identity_accounts.address_postal_code,
	{{prefix}}identity_accounts.address_country,
	{{prefix}}identity_accounts.address_phone,
	{{prefix}}identity_accounts.time_zone,
	{{prefix}}identity_accounts.created_at,
	{{prefix}}identity_accounts.last_updated_at,
	{{prefix}}identity_accounts.archived_at,
	(
		SELECT COUNT({{prefix}}identity_accounts.id)
		FROM {{prefix}}identity_accounts
		WHERE {{prefix}}identity_accounts.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			AND {{prefix}}identity_accounts.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			AND (
				{{prefix}}identity_accounts.last_updated_at IS NULL
				OR {{prefix}}identity_accounts.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			)
			AND (
				{{prefix}}identity_accounts.last_updated_at IS NULL
				OR {{prefix}}identity_accounts.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			)
			AND (COALESCE(?, false) = true OR {{prefix}}identity_accounts.archived_at IS NULL)
			AND {{prefix}}identity_accounts.scope = ?
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}identity_accounts.id)
		FROM {{prefix}}identity_accounts
		WHERE (COALESCE(?, false) = true OR {{prefix}}identity_accounts.archived_at IS NULL)
			AND {{prefix}}identity_accounts.scope = ?
	) AS total_count
FROM {{prefix}}identity_accounts
WHERE {{prefix}}identity_accounts.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	AND {{prefix}}identity_accounts.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	AND (
		{{prefix}}identity_accounts.last_updated_at IS NULL
		OR {{prefix}}identity_accounts.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	)
	AND (
		{{prefix}}identity_accounts.last_updated_at IS NULL
		OR {{prefix}}identity_accounts.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	)
	AND (COALESCE(?, false) = true OR {{prefix}}identity_accounts.archived_at IS NULL)
	AND {{prefix}}identity_accounts.scope = ?
	AND {{prefix}}identity_accounts.id > COALESCE(?, '')
ORDER BY {{prefix}}identity_accounts.id ASC
LIMIT ?`

const listAccountsForUserMySQL = `SELECT
	{{prefix}}identity_accounts.id,
	{{prefix}}identity_accounts.scope,
	{{prefix}}identity_accounts.name,
	{{prefix}}identity_accounts.owner_user_id,
	{{prefix}}identity_accounts.billing_status,
	{{prefix}}identity_accounts.subscription_plan_id,
	{{prefix}}identity_accounts.payment_processor_customer_id,
	{{prefix}}identity_accounts.last_payment_provider_synced_at,
	{{prefix}}identity_accounts.address_line1,
	{{prefix}}identity_accounts.address_line2,
	{{prefix}}identity_accounts.address_city,
	{{prefix}}identity_accounts.address_state,
	{{prefix}}identity_accounts.address_postal_code,
	{{prefix}}identity_accounts.address_country,
	{{prefix}}identity_accounts.address_phone,
	{{prefix}}identity_accounts.time_zone,
	{{prefix}}identity_accounts.created_at,
	{{prefix}}identity_accounts.last_updated_at,
	{{prefix}}identity_accounts.archived_at,
	(
		SELECT COUNT({{prefix}}identity_accounts.id)
		FROM {{prefix}}identity_accounts
		JOIN {{prefix}}identity_memberships ON {{prefix}}identity_accounts.id={{prefix}}identity_memberships.belongs_to_account
		WHERE {{prefix}}identity_accounts.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			AND {{prefix}}identity_accounts.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			AND (
				{{prefix}}identity_accounts.last_updated_at IS NULL
				OR {{prefix}}identity_accounts.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			)
			AND (
				{{prefix}}identity_accounts.last_updated_at IS NULL
				OR {{prefix}}identity_accounts.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			)
			AND (COALESCE(?, false) = true OR {{prefix}}identity_accounts.archived_at IS NULL)
			AND {{prefix}}identity_accounts.scope = ?
			AND {{prefix}}identity_memberships.archived_at IS NULL
			AND {{prefix}}identity_memberships.belongs_to_user = ?
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}identity_accounts.id)
		FROM {{prefix}}identity_accounts
		JOIN {{prefix}}identity_memberships ON {{prefix}}identity_accounts.id={{prefix}}identity_memberships.belongs_to_account
		WHERE (COALESCE(?, false) = true OR {{prefix}}identity_accounts.archived_at IS NULL)
			AND {{prefix}}identity_accounts.scope = ?
			AND {{prefix}}identity_memberships.archived_at IS NULL
			AND {{prefix}}identity_memberships.belongs_to_user = ?
	) AS total_count
FROM {{prefix}}identity_accounts
JOIN {{prefix}}identity_memberships ON {{prefix}}identity_accounts.id={{prefix}}identity_memberships.belongs_to_account
WHERE {{prefix}}identity_accounts.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	AND {{prefix}}identity_accounts.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	AND (
		{{prefix}}identity_accounts.last_updated_at IS NULL
		OR {{prefix}}identity_accounts.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	)
	AND (
		{{prefix}}identity_accounts.last_updated_at IS NULL
		OR {{prefix}}identity_accounts.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	)
	AND (COALESCE(?, false) = true OR {{prefix}}identity_accounts.archived_at IS NULL)
	AND {{prefix}}identity_accounts.scope = ?
	AND {{prefix}}identity_memberships.archived_at IS NULL
	AND {{prefix}}identity_memberships.belongs_to_user = ?
	AND {{prefix}}identity_accounts.id > COALESCE(?, '')
ORDER BY {{prefix}}identity_accounts.id ASC
LIMIT ?`

const listInvitationsMySQL = `SELECT
	{{prefix}}identity_invitations.id,
	{{prefix}}identity_invitations.scope,
	{{prefix}}identity_invitations.belongs_to_account,
	{{prefix}}identity_invitations.from_user,
	{{prefix}}identity_invitations.to_email,
	{{prefix}}identity_invitations.to_name,
	{{prefix}}identity_invitations.to_user,
	{{prefix}}identity_invitations.token,
	{{prefix}}identity_invitations.status,
	{{prefix}}identity_invitations.note,
	{{prefix}}identity_invitations.expires_at,
	{{prefix}}identity_invitations.created_at,
	{{prefix}}identity_invitations.last_updated_at,
	{{prefix}}identity_invitations.archived_at,
	(
		SELECT COUNT({{prefix}}identity_invitations.id)
		FROM {{prefix}}identity_invitations
		WHERE {{prefix}}identity_invitations.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			AND {{prefix}}identity_invitations.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			AND (
				{{prefix}}identity_invitations.last_updated_at IS NULL
				OR {{prefix}}identity_invitations.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			)
			AND (
				{{prefix}}identity_invitations.last_updated_at IS NULL
				OR {{prefix}}identity_invitations.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			)
			AND (COALESCE(?, false) = true OR {{prefix}}identity_invitations.archived_at IS NULL)
			AND {{prefix}}identity_invitations.scope = ?
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}identity_invitations.id)
		FROM {{prefix}}identity_invitations
		WHERE (COALESCE(?, false) = true OR {{prefix}}identity_invitations.archived_at IS NULL)
			AND {{prefix}}identity_invitations.scope = ?
	) AS total_count
FROM {{prefix}}identity_invitations
WHERE {{prefix}}identity_invitations.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	AND {{prefix}}identity_invitations.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	AND (
		{{prefix}}identity_invitations.last_updated_at IS NULL
		OR {{prefix}}identity_invitations.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	)
	AND (
		{{prefix}}identity_invitations.last_updated_at IS NULL
		OR {{prefix}}identity_invitations.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	)
	AND (COALESCE(?, false) = true OR {{prefix}}identity_invitations.archived_at IS NULL)
	AND {{prefix}}identity_invitations.scope = ?
	AND {{prefix}}identity_invitations.id > COALESCE(?, '')
ORDER BY {{prefix}}identity_invitations.id ASC
LIMIT ?`

const listInvitationsByFromUserMySQL = `SELECT
	{{prefix}}identity_invitations.id,
	{{prefix}}identity_invitations.scope,
	{{prefix}}identity_invitations.belongs_to_account,
	{{prefix}}identity_invitations.from_user,
	{{prefix}}identity_invitations.to_email,
	{{prefix}}identity_invitations.to_name,
	{{prefix}}identity_invitations.to_user,
	{{prefix}}identity_invitations.token,
	{{prefix}}identity_invitations.status,
	{{prefix}}identity_invitations.note,
	{{prefix}}identity_invitations.expires_at,
	{{prefix}}identity_invitations.created_at,
	{{prefix}}identity_invitations.last_updated_at,
	{{prefix}}identity_invitations.archived_at,
	(
		SELECT COUNT({{prefix}}identity_invitations.id)
		FROM {{prefix}}identity_invitations
		WHERE {{prefix}}identity_invitations.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			AND {{prefix}}identity_invitations.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			AND (
				{{prefix}}identity_invitations.last_updated_at IS NULL
				OR {{prefix}}identity_invitations.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			)
			AND (
				{{prefix}}identity_invitations.last_updated_at IS NULL
				OR {{prefix}}identity_invitations.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			)
			AND (COALESCE(?, false) = true OR {{prefix}}identity_invitations.archived_at IS NULL)
			AND {{prefix}}identity_invitations.scope = ?
			AND {{prefix}}identity_invitations.from_user = ?
			AND {{prefix}}identity_invitations.status = ?
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}identity_invitations.id)
		FROM {{prefix}}identity_invitations
		WHERE (COALESCE(?, false) = true OR {{prefix}}identity_invitations.archived_at IS NULL)
			AND {{prefix}}identity_invitations.scope = ?
			AND {{prefix}}identity_invitations.from_user = ?
			AND {{prefix}}identity_invitations.status = ?
	) AS total_count
FROM {{prefix}}identity_invitations
WHERE {{prefix}}identity_invitations.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	AND {{prefix}}identity_invitations.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	AND (
		{{prefix}}identity_invitations.last_updated_at IS NULL
		OR {{prefix}}identity_invitations.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	)
	AND (
		{{prefix}}identity_invitations.last_updated_at IS NULL
		OR {{prefix}}identity_invitations.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	)
	AND (COALESCE(?, false) = true OR {{prefix}}identity_invitations.archived_at IS NULL)
	AND {{prefix}}identity_invitations.scope = ?
	AND {{prefix}}identity_invitations.from_user = ?
	AND {{prefix}}identity_invitations.status = ?
	AND {{prefix}}identity_invitations.id > COALESCE(?, '')
ORDER BY {{prefix}}identity_invitations.id ASC
LIMIT ?`

const listInvitationsByToEmailMySQL = `SELECT
	{{prefix}}identity_invitations.id,
	{{prefix}}identity_invitations.scope,
	{{prefix}}identity_invitations.belongs_to_account,
	{{prefix}}identity_invitations.from_user,
	{{prefix}}identity_invitations.to_email,
	{{prefix}}identity_invitations.to_name,
	{{prefix}}identity_invitations.to_user,
	{{prefix}}identity_invitations.token,
	{{prefix}}identity_invitations.status,
	{{prefix}}identity_invitations.note,
	{{prefix}}identity_invitations.expires_at,
	{{prefix}}identity_invitations.created_at,
	{{prefix}}identity_invitations.last_updated_at,
	{{prefix}}identity_invitations.archived_at,
	(
		SELECT COUNT({{prefix}}identity_invitations.id)
		FROM {{prefix}}identity_invitations
		WHERE {{prefix}}identity_invitations.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			AND {{prefix}}identity_invitations.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			AND (
				{{prefix}}identity_invitations.last_updated_at IS NULL
				OR {{prefix}}identity_invitations.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			)
			AND (
				{{prefix}}identity_invitations.last_updated_at IS NULL
				OR {{prefix}}identity_invitations.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			)
			AND (COALESCE(?, false) = true OR {{prefix}}identity_invitations.archived_at IS NULL)
			AND {{prefix}}identity_invitations.scope = ?
			AND {{prefix}}identity_invitations.to_email = ?
			AND {{prefix}}identity_invitations.status = ?
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}identity_invitations.id)
		FROM {{prefix}}identity_invitations
		WHERE (COALESCE(?, false) = true OR {{prefix}}identity_invitations.archived_at IS NULL)
			AND {{prefix}}identity_invitations.scope = ?
			AND {{prefix}}identity_invitations.to_email = ?
			AND {{prefix}}identity_invitations.status = ?
	) AS total_count
FROM {{prefix}}identity_invitations
WHERE {{prefix}}identity_invitations.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	AND {{prefix}}identity_invitations.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	AND (
		{{prefix}}identity_invitations.last_updated_at IS NULL
		OR {{prefix}}identity_invitations.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	)
	AND (
		{{prefix}}identity_invitations.last_updated_at IS NULL
		OR {{prefix}}identity_invitations.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	)
	AND (COALESCE(?, false) = true OR {{prefix}}identity_invitations.archived_at IS NULL)
	AND {{prefix}}identity_invitations.scope = ?
	AND {{prefix}}identity_invitations.to_email = ?
	AND {{prefix}}identity_invitations.status = ?
	AND {{prefix}}identity_invitations.id > COALESCE(?, '')
ORDER BY {{prefix}}identity_invitations.id ASC
LIMIT ?`

const listMembershipsForUserMySQL = `SELECT
	{{prefix}}identity_memberships.id,
	{{prefix}}identity_memberships.scope,
	{{prefix}}identity_memberships.belongs_to_user,
	{{prefix}}identity_memberships.belongs_to_account,
	{{prefix}}identity_memberships.default_account,
	{{prefix}}identity_memberships.created_at,
	{{prefix}}identity_memberships.last_updated_at,
	{{prefix}}identity_memberships.archived_at
FROM {{prefix}}identity_memberships
WHERE {{prefix}}identity_memberships.archived_at IS NULL
	AND {{prefix}}identity_memberships.scope = ?
	AND {{prefix}}identity_memberships.belongs_to_user = ?
ORDER BY {{prefix}}identity_memberships.default_account DESC, {{prefix}}identity_memberships.belongs_to_account ASC`

const listUsersMySQL = `SELECT
	{{prefix}}identity_users.id,
	{{prefix}}identity_users.scope,
	{{prefix}}identity_users.username,
	{{prefix}}identity_users.email_address,
	{{prefix}}identity_users.first_name,
	{{prefix}}identity_users.last_name,
	{{prefix}}identity_users.hashed_password,
	{{prefix}}identity_users.requires_password_change,
	{{prefix}}identity_users.password_last_changed_at,
	{{prefix}}identity_users.two_factor_secret,
	{{prefix}}identity_users.two_factor_secret_verified_at,
	{{prefix}}identity_users.email_address_verified_at,
	{{prefix}}identity_users.email_address_verification_token,
	{{prefix}}identity_users.account_status,
	{{prefix}}identity_users.account_status_explanation,
	{{prefix}}identity_users.last_accepted_terms_of_service,
	{{prefix}}identity_users.last_accepted_privacy_policy,
	{{prefix}}identity_users.created_at,
	{{prefix}}identity_users.last_updated_at,
	{{prefix}}identity_users.archived_at,
	(
		SELECT COUNT({{prefix}}identity_users.id)
		FROM {{prefix}}identity_users
		WHERE {{prefix}}identity_users.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			AND {{prefix}}identity_users.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			AND (
				{{prefix}}identity_users.last_updated_at IS NULL
				OR {{prefix}}identity_users.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
			)
			AND (
				{{prefix}}identity_users.last_updated_at IS NULL
				OR {{prefix}}identity_users.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
			)
			AND (COALESCE(?, false) = true OR {{prefix}}identity_users.archived_at IS NULL)
			AND {{prefix}}identity_users.scope = ?
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}identity_users.id)
		FROM {{prefix}}identity_users
		WHERE (COALESCE(?, false) = true OR {{prefix}}identity_users.archived_at IS NULL)
			AND {{prefix}}identity_users.scope = ?
	) AS total_count
FROM {{prefix}}identity_users
WHERE {{prefix}}identity_users.created_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	AND {{prefix}}identity_users.created_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	AND (
		{{prefix}}identity_users.last_updated_at IS NULL
		OR {{prefix}}identity_users.last_updated_at > COALESCE(?, (SELECT CURRENT_TIMESTAMP - INTERVAL 999 YEAR))
	)
	AND (
		{{prefix}}identity_users.last_updated_at IS NULL
		OR {{prefix}}identity_users.last_updated_at < COALESCE(?, (SELECT CURRENT_TIMESTAMP + INTERVAL 999 YEAR))
	)
	AND (COALESCE(?, false) = true OR {{prefix}}identity_users.archived_at IS NULL)
	AND {{prefix}}identity_users.scope = ?
	AND {{prefix}}identity_users.id > COALESCE(?, '')
ORDER BY {{prefix}}identity_users.id ASC
LIMIT ?`

const markUserEmailAddressVerifiedMySQL = `UPDATE {{prefix}}identity_users SET
	email_address_verified_at = ?,
	email_address_verification_token = ?,
	last_updated_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND id = ?
	AND scope = ?
	AND email_address_verification_token = ?`

const setUserEmailAddressVerificationTokenMySQL = `UPDATE {{prefix}}identity_users SET
	email_address_verification_token = ?,
	last_updated_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND id = ?
	AND scope = ?`

const setUserRequiresPasswordChangeMySQL = `UPDATE {{prefix}}identity_users SET
	requires_password_change = ?,
	last_updated_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND id = ?
	AND scope = ?`

const transferAccountOwnershipMySQL = `UPDATE {{prefix}}identity_accounts SET
	owner_user_id = ?,
	last_updated_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND id = ?
	AND scope = ?
	AND owner_user_id = ?`

const updateAccountMySQL = `UPDATE {{prefix}}identity_accounts SET
	name = ?,
	address_line1 = ?,
	address_line2 = ?,
	address_city = ?,
	address_state = ?,
	address_postal_code = ?,
	address_country = ?,
	address_phone = ?,
	time_zone = ?,
	last_updated_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND id = ?
	AND scope = ?`

const updateUserMySQL = `UPDATE {{prefix}}identity_users SET
	username = ?,
	email_address = ?,
	first_name = ?,
	last_name = ?,
	email_address_verified_at = ?,
	last_updated_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND id = ?
	AND scope = ?`

const updateUserAccountStatusMySQL = `UPDATE {{prefix}}identity_users SET
	account_status = ?,
	account_status_explanation = ?,
	last_updated_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND id = ?
	AND scope = ?`

const updateUserPasswordMySQL = `UPDATE {{prefix}}identity_users SET
	hashed_password = ?,
	requires_password_change = ?,
	password_last_changed_at = ?,
	last_updated_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND id = ?
	AND scope = ?`

const updateUserTwoFactorSecretMySQL = `UPDATE {{prefix}}identity_users SET
	two_factor_secret = ?,
	two_factor_secret_verified_at = ?,
	last_updated_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND id = ?
	AND scope = ?`

const upsertMembershipMySQL = `INSERT INTO {{prefix}}identity_memberships (
	id,
	scope,
	belongs_to_user,
	belongs_to_account,
	default_account
) VALUES (
	?,
	?,
	?,
	?,
	?
)
ON DUPLICATE KEY UPDATE
	default_account = VALUES(default_account),
	archived_at = NULL,
	last_updated_at = CURRENT_TIMESTAMP(6)`

// mysqlQueries answers every query in Querier against mysql.
type mysqlQueries struct {
	answerInvitation                     string
	archiveAccount                       string
	archiveUser                          string
	createAccount                        string
	createInvitation                     string
	createUser                           string
	getAccount                           string
	getAccountCreatedAt                  string
	getInvitation                        string
	getInvitationCreatedAt               string
	getMembershipByUserAndAccount        string
	getMembershipFallbackAccountID       string
	getMembershipIdbyUserAndAccount      string
	getUser                              string
	getUserByEmailAddress                string
	getUserByEmailVerificationToken      string
	getUserByUsername                    string
	getUserCreatedAt                     string
	listAccountMembers                   string
	listAccounts                         string
	listAccountsForUser                  string
	listInvitations                      string
	listInvitationsByFromUser            string
	listInvitationsByToEmail             string
	listMembershipsForUser               string
	listUsers                            string
	markUserEmailAddressVerified         string
	setUserEmailAddressVerificationToken string
	setUserRequiresPasswordChange        string
	transferAccountOwnership             string
	updateAccount                        string
	updateUser                           string
	updateUserAccountStatus              string
	updateUserPassword                   string
	updateUserTwoFactorSecret            string
	upsertMembership                     string
}

// newMySQL returns the mysql querier with prefix substituted into every
// table name the analyzer identified.
func newMySQL(prefix string) *mysqlQueries {
	return &mysqlQueries{
		answerInvitation:                     strings.ReplaceAll(answerInvitationMySQL, prefixMarker, prefix),
		archiveAccount:                       strings.ReplaceAll(archiveAccountMySQL, prefixMarker, prefix),
		archiveUser:                          strings.ReplaceAll(archiveUserMySQL, prefixMarker, prefix),
		createAccount:                        strings.ReplaceAll(createAccountMySQL, prefixMarker, prefix),
		createInvitation:                     strings.ReplaceAll(createInvitationMySQL, prefixMarker, prefix),
		createUser:                           strings.ReplaceAll(createUserMySQL, prefixMarker, prefix),
		getAccount:                           strings.ReplaceAll(getAccountMySQL, prefixMarker, prefix),
		getAccountCreatedAt:                  strings.ReplaceAll(getAccountCreatedAtMySQL, prefixMarker, prefix),
		getInvitation:                        strings.ReplaceAll(getInvitationMySQL, prefixMarker, prefix),
		getInvitationCreatedAt:               strings.ReplaceAll(getInvitationCreatedAtMySQL, prefixMarker, prefix),
		getMembershipByUserAndAccount:        strings.ReplaceAll(getMembershipByUserAndAccountMySQL, prefixMarker, prefix),
		getMembershipFallbackAccountID:       strings.ReplaceAll(getMembershipFallbackAccountIDMySQL, prefixMarker, prefix),
		getMembershipIdbyUserAndAccount:      strings.ReplaceAll(getMembershipIdbyUserAndAccountMySQL, prefixMarker, prefix),
		getUser:                              strings.ReplaceAll(getUserMySQL, prefixMarker, prefix),
		getUserByEmailAddress:                strings.ReplaceAll(getUserByEmailAddressMySQL, prefixMarker, prefix),
		getUserByEmailVerificationToken:      strings.ReplaceAll(getUserByEmailVerificationTokenMySQL, prefixMarker, prefix),
		getUserByUsername:                    strings.ReplaceAll(getUserByUsernameMySQL, prefixMarker, prefix),
		getUserCreatedAt:                     strings.ReplaceAll(getUserCreatedAtMySQL, prefixMarker, prefix),
		listAccountMembers:                   strings.ReplaceAll(listAccountMembersMySQL, prefixMarker, prefix),
		listAccounts:                         strings.ReplaceAll(listAccountsMySQL, prefixMarker, prefix),
		listAccountsForUser:                  strings.ReplaceAll(listAccountsForUserMySQL, prefixMarker, prefix),
		listInvitations:                      strings.ReplaceAll(listInvitationsMySQL, prefixMarker, prefix),
		listInvitationsByFromUser:            strings.ReplaceAll(listInvitationsByFromUserMySQL, prefixMarker, prefix),
		listInvitationsByToEmail:             strings.ReplaceAll(listInvitationsByToEmailMySQL, prefixMarker, prefix),
		listMembershipsForUser:               strings.ReplaceAll(listMembershipsForUserMySQL, prefixMarker, prefix),
		listUsers:                            strings.ReplaceAll(listUsersMySQL, prefixMarker, prefix),
		markUserEmailAddressVerified:         strings.ReplaceAll(markUserEmailAddressVerifiedMySQL, prefixMarker, prefix),
		setUserEmailAddressVerificationToken: strings.ReplaceAll(setUserEmailAddressVerificationTokenMySQL, prefixMarker, prefix),
		setUserRequiresPasswordChange:        strings.ReplaceAll(setUserRequiresPasswordChangeMySQL, prefixMarker, prefix),
		transferAccountOwnership:             strings.ReplaceAll(transferAccountOwnershipMySQL, prefixMarker, prefix),
		updateAccount:                        strings.ReplaceAll(updateAccountMySQL, prefixMarker, prefix),
		updateUser:                           strings.ReplaceAll(updateUserMySQL, prefixMarker, prefix),
		updateUserAccountStatus:              strings.ReplaceAll(updateUserAccountStatusMySQL, prefixMarker, prefix),
		updateUserPassword:                   strings.ReplaceAll(updateUserPasswordMySQL, prefixMarker, prefix),
		updateUserTwoFactorSecret:            strings.ReplaceAll(updateUserTwoFactorSecretMySQL, prefixMarker, prefix),
		upsertMembership:                     strings.ReplaceAll(upsertMembershipMySQL, prefixMarker, prefix),
	}
}

// AnswerInvitation runs the :execrows query against mysql.
func (q *mysqlQueries) AnswerInvitation(ctx context.Context, db DBTX, arg AnswerInvitationParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.answerInvitation,
		arg.Status,
		arg.Note,
		arg.ToUser,
		arg.ID,
		arg.Scope,
		arg.CurrentStatus,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// ArchiveAccount runs the :execrows query against mysql.
func (q *mysqlQueries) ArchiveAccount(ctx context.Context, db DBTX, arg ArchiveAccountParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.archiveAccount,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// ArchiveUser runs the :execrows query against mysql.
func (q *mysqlQueries) ArchiveUser(ctx context.Context, db DBTX, arg ArchiveUserParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.archiveUser,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// CreateAccount runs the :exec query against mysql.
func (q *mysqlQueries) CreateAccount(ctx context.Context, db DBTX, arg CreateAccountParams) error {
	_, err := db.ExecContext(ctx, q.createAccount,
		arg.ID,
		arg.Scope,
		arg.Name,
		arg.OwnerUserID,
		arg.BillingStatus,
		arg.SubscriptionPlanID,
		arg.PaymentProcessorCustomerID,
		arg.LastPaymentProviderSyncedAt,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressPostalCode,
		arg.AddressCountry,
		arg.AddressPhone,
		arg.TimeZone,
	)

	return err
}

// CreateInvitation runs the :exec query against mysql.
func (q *mysqlQueries) CreateInvitation(ctx context.Context, db DBTX, arg CreateInvitationParams) error {
	_, err := db.ExecContext(ctx, q.createInvitation,
		arg.ID,
		arg.Scope,
		arg.BelongsToAccount,
		arg.FromUser,
		arg.ToEmail,
		arg.ToName,
		arg.ToUser,
		arg.Token,
		arg.Status,
		arg.Note,
		arg.ExpiresAt,
	)

	return err
}

// CreateUser runs the :exec query against mysql.
func (q *mysqlQueries) CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) error {
	_, err := db.ExecContext(ctx, q.createUser,
		arg.ID,
		arg.Scope,
		arg.Username,
		arg.EmailAddress,
		arg.FirstName,
		arg.LastName,
		arg.HashedPassword,
		arg.RequiresPasswordChange,
		arg.PasswordLastChangedAt,
		arg.TwoFactorSecret,
		arg.TwoFactorSecretVerifiedAt,
		arg.EmailAddressVerifiedAt,
		arg.EmailAddressVerificationToken,
		arg.AccountStatus,
		arg.AccountStatusExplanation,
		arg.LastAcceptedTermsOfService,
		arg.LastAcceptedPrivacyPolicy,
	)

	return err
}

// GetAccount runs the :one query against mysql.
func (q *mysqlQueries) GetAccount(ctx context.Context, db DBTX, arg GetAccountParams) (GetAccountRow, error) {
	row := db.QueryRowContext(ctx, q.getAccount,
		arg.ID,
		arg.Scope,
	)

	var i GetAccountRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Name,
		&i.OwnerUserID,
		&i.BillingStatus,
		&i.SubscriptionPlanID,
		&i.PaymentProcessorCustomerID,
		&i.LastPaymentProviderSyncedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressPostalCode,
		&i.AddressCountry,
		&i.AddressPhone,
		&i.TimeZone,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetAccountCreatedAt runs the :one query against mysql.
func (q *mysqlQueries) GetAccountCreatedAt(ctx context.Context, db DBTX, arg GetAccountCreatedAtParams) (GetAccountCreatedAtRow, error) {
	row := db.QueryRowContext(ctx, q.getAccountCreatedAt,
		arg.ID,
	)

	var i GetAccountCreatedAtRow

	err := row.Scan(
		&i.CreatedAt,
	)

	return i, err
}

// GetInvitation runs the :one query against mysql.
func (q *mysqlQueries) GetInvitation(ctx context.Context, db DBTX, arg GetInvitationParams) (GetInvitationRow, error) {
	row := db.QueryRowContext(ctx, q.getInvitation,
		arg.ID,
		arg.Scope,
	)

	var i GetInvitationRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.BelongsToAccount,
		&i.FromUser,
		&i.ToEmail,
		&i.ToName,
		&i.ToUser,
		&i.Token,
		&i.Status,
		&i.Note,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetInvitationCreatedAt runs the :one query against mysql.
func (q *mysqlQueries) GetInvitationCreatedAt(ctx context.Context, db DBTX, arg GetInvitationCreatedAtParams) (GetInvitationCreatedAtRow, error) {
	row := db.QueryRowContext(ctx, q.getInvitationCreatedAt,
		arg.ID,
	)

	var i GetInvitationCreatedAtRow

	err := row.Scan(
		&i.CreatedAt,
	)

	return i, err
}

// GetMembershipByUserAndAccount runs the :one query against mysql.
func (q *mysqlQueries) GetMembershipByUserAndAccount(ctx context.Context, db DBTX, arg GetMembershipByUserAndAccountParams) (GetMembershipByUserAndAccountRow, error) {
	row := db.QueryRowContext(ctx, q.getMembershipByUserAndAccount,
		arg.Scope,
		arg.BelongsToUser,
		arg.BelongsToAccount,
	)

	var i GetMembershipByUserAndAccountRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.BelongsToUser,
		&i.BelongsToAccount,
		&i.DefaultAccount,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetMembershipFallbackAccountID runs the :one query against mysql.
func (q *mysqlQueries) GetMembershipFallbackAccountID(ctx context.Context, db DBTX, arg GetMembershipFallbackAccountIDParams) (GetMembershipFallbackAccountIDRow, error) {
	row := db.QueryRowContext(ctx, q.getMembershipFallbackAccountID,
		arg.Scope,
		arg.BelongsToUser,
		arg.BelongsToAccount,
	)

	var i GetMembershipFallbackAccountIDRow

	err := row.Scan(
		&i.BelongsToAccount,
	)

	return i, err
}

// GetMembershipIDByUserAndAccount runs the :one query against mysql.
func (q *mysqlQueries) GetMembershipIDByUserAndAccount(ctx context.Context, db DBTX, arg GetMembershipIDByUserAndAccountParams) (GetMembershipIDByUserAndAccountRow, error) {
	row := db.QueryRowContext(ctx, q.getMembershipIdbyUserAndAccount,
		arg.Scope,
		arg.BelongsToUser,
		arg.BelongsToAccount,
	)

	var i GetMembershipIDByUserAndAccountRow

	err := row.Scan(
		&i.ID,
	)

	return i, err
}

// GetUser runs the :one query against mysql.
func (q *mysqlQueries) GetUser(ctx context.Context, db DBTX, arg GetUserParams) (GetUserRow, error) {
	row := db.QueryRowContext(ctx, q.getUser,
		arg.ID,
		arg.Scope,
	)

	var i GetUserRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Username,
		&i.EmailAddress,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.RequiresPasswordChange,
		&i.PasswordLastChangedAt,
		&i.TwoFactorSecret,
		&i.TwoFactorSecretVerifiedAt,
		&i.EmailAddressVerifiedAt,
		&i.EmailAddressVerificationToken,
		&i.AccountStatus,
		&i.AccountStatusExplanation,
		&i.LastAcceptedTermsOfService,
		&i.LastAcceptedPrivacyPolicy,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetUserByEmailAddress runs the :one query against mysql.
func (q *mysqlQueries) GetUserByEmailAddress(ctx context.Context, db DBTX, arg GetUserByEmailAddressParams) (GetUserByEmailAddressRow, error) {
	row := db.QueryRowContext(ctx, q.getUserByEmailAddress,
		arg.EmailAddress,
		arg.Scope,
	)

	var i GetUserByEmailAddressRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Username,
		&i.EmailAddress,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.RequiresPasswordChange,
		&i.PasswordLastChangedAt,
		&i.TwoFactorSecret,
		&i.TwoFactorSecretVerifiedAt,
		&i.EmailAddressVerifiedAt,
		&i.EmailAddressVerificationToken,
		&i.AccountStatus,
		&i.AccountStatusExplanation,
		&i.LastAcceptedTermsOfService,
		&i.LastAcceptedPrivacyPolicy,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetUserByEmailVerificationToken runs the :one query against mysql.
func (q *mysqlQueries) GetUserByEmailVerificationToken(ctx context.Context, db DBTX, arg GetUserByEmailVerificationTokenParams) (GetUserByEmailVerificationTokenRow, error) {
	row := db.QueryRowContext(ctx, q.getUserByEmailVerificationToken,
		arg.EmailAddressVerificationToken,
		arg.Scope,
	)

	var i GetUserByEmailVerificationTokenRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Username,
		&i.EmailAddress,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.RequiresPasswordChange,
		&i.PasswordLastChangedAt,
		&i.TwoFactorSecret,
		&i.TwoFactorSecretVerifiedAt,
		&i.EmailAddressVerifiedAt,
		&i.EmailAddressVerificationToken,
		&i.AccountStatus,
		&i.AccountStatusExplanation,
		&i.LastAcceptedTermsOfService,
		&i.LastAcceptedPrivacyPolicy,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetUserByUsername runs the :one query against mysql.
func (q *mysqlQueries) GetUserByUsername(ctx context.Context, db DBTX, arg GetUserByUsernameParams) (GetUserByUsernameRow, error) {
	row := db.QueryRowContext(ctx, q.getUserByUsername,
		arg.Username,
		arg.Scope,
	)

	var i GetUserByUsernameRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Username,
		&i.EmailAddress,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.RequiresPasswordChange,
		&i.PasswordLastChangedAt,
		&i.TwoFactorSecret,
		&i.TwoFactorSecretVerifiedAt,
		&i.EmailAddressVerifiedAt,
		&i.EmailAddressVerificationToken,
		&i.AccountStatus,
		&i.AccountStatusExplanation,
		&i.LastAcceptedTermsOfService,
		&i.LastAcceptedPrivacyPolicy,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetUserCreatedAt runs the :one query against mysql.
func (q *mysqlQueries) GetUserCreatedAt(ctx context.Context, db DBTX, arg GetUserCreatedAtParams) (GetUserCreatedAtRow, error) {
	row := db.QueryRowContext(ctx, q.getUserCreatedAt,
		arg.ID,
	)

	var i GetUserCreatedAtRow

	err := row.Scan(
		&i.CreatedAt,
	)

	return i, err
}

// ListAccountMembers runs the :many query against mysql.
func (q *mysqlQueries) ListAccountMembers(ctx context.Context, db DBTX, arg ListAccountMembersParams) ([]ListAccountMembersRow, error) {
	rows, err := db.QueryContext(ctx, q.listAccountMembers,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.BelongsToAccount,
		arg.IncludeArchived,
		arg.Scope,
		arg.BelongsToAccount,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.BelongsToAccount,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListAccountMembersRow

	for rows.Next() {
		var i ListAccountMembersRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.BelongsToUser,
			&i.BelongsToAccount,
			&i.DefaultAccount,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.UserID,
			&i.UserScope,
			&i.UserUsername,
			&i.UserEmailAddress,
			&i.UserFirstName,
			&i.UserLastName,
			&i.UserHashedPassword,
			&i.UserRequiresPasswordChange,
			&i.UserPasswordLastChangedAt,
			&i.UserTwoFactorSecret,
			&i.UserTwoFactorSecretVerifiedAt,
			&i.UserEmailAddressVerifiedAt,
			&i.UserEmailAddressVerificationToken,
			&i.UserAccountStatus,
			&i.UserAccountStatusExplanation,
			&i.UserLastAcceptedTermsOfService,
			&i.UserLastAcceptedPrivacyPolicy,
			&i.UserCreatedAt,
			&i.UserLastUpdatedAt,
			&i.UserArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListAccounts runs the :many query against mysql.
func (q *mysqlQueries) ListAccounts(ctx context.Context, db DBTX, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := db.QueryContext(ctx, q.listAccounts,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.IncludeArchived,
		arg.Scope,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListAccountsRow

	for rows.Next() {
		var i ListAccountsRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.Name,
			&i.OwnerUserID,
			&i.BillingStatus,
			&i.SubscriptionPlanID,
			&i.PaymentProcessorCustomerID,
			&i.LastPaymentProviderSyncedAt,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressPostalCode,
			&i.AddressCountry,
			&i.AddressPhone,
			&i.TimeZone,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListAccountsForUser runs the :many query against mysql.
func (q *mysqlQueries) ListAccountsForUser(ctx context.Context, db DBTX, arg ListAccountsForUserParams) ([]ListAccountsForUserRow, error) {
	rows, err := db.QueryContext(ctx, q.listAccountsForUser,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.BelongsToUser,
		arg.IncludeArchived,
		arg.Scope,
		arg.BelongsToUser,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.BelongsToUser,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListAccountsForUserRow

	for rows.Next() {
		var i ListAccountsForUserRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.Name,
			&i.OwnerUserID,
			&i.BillingStatus,
			&i.SubscriptionPlanID,
			&i.PaymentProcessorCustomerID,
			&i.LastPaymentProviderSyncedAt,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressPostalCode,
			&i.AddressCountry,
			&i.AddressPhone,
			&i.TimeZone,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListInvitations runs the :many query against mysql.
func (q *mysqlQueries) ListInvitations(ctx context.Context, db DBTX, arg ListInvitationsParams) ([]ListInvitationsRow, error) {
	rows, err := db.QueryContext(ctx, q.listInvitations,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.IncludeArchived,
		arg.Scope,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListInvitationsRow

	for rows.Next() {
		var i ListInvitationsRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.BelongsToAccount,
			&i.FromUser,
			&i.ToEmail,
			&i.ToName,
			&i.ToUser,
			&i.Token,
			&i.Status,
			&i.Note,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListInvitationsByFromUser runs the :many query against mysql.
func (q *mysqlQueries) ListInvitationsByFromUser(ctx context.Context, db DBTX, arg ListInvitationsByFromUserParams) ([]ListInvitationsByFromUserRow, error) {
	rows, err := db.QueryContext(ctx, q.listInvitationsByFromUser,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.FromUser,
		arg.Status,
		arg.IncludeArchived,
		arg.Scope,
		arg.FromUser,
		arg.Status,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.FromUser,
		arg.Status,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListInvitationsByFromUserRow

	for rows.Next() {
		var i ListInvitationsByFromUserRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.BelongsToAccount,
			&i.FromUser,
			&i.ToEmail,
			&i.ToName,
			&i.ToUser,
			&i.Token,
			&i.Status,
			&i.Note,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListInvitationsByToEmail runs the :many query against mysql.
func (q *mysqlQueries) ListInvitationsByToEmail(ctx context.Context, db DBTX, arg ListInvitationsByToEmailParams) ([]ListInvitationsByToEmailRow, error) {
	rows, err := db.QueryContext(ctx, q.listInvitationsByToEmail,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.ToEmail,
		arg.Status,
		arg.IncludeArchived,
		arg.Scope,
		arg.ToEmail,
		arg.Status,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.ToEmail,
		arg.Status,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListInvitationsByToEmailRow

	for rows.Next() {
		var i ListInvitationsByToEmailRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.BelongsToAccount,
			&i.FromUser,
			&i.ToEmail,
			&i.ToName,
			&i.ToUser,
			&i.Token,
			&i.Status,
			&i.Note,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListMembershipsForUser runs the :many query against mysql.
func (q *mysqlQueries) ListMembershipsForUser(ctx context.Context, db DBTX, arg ListMembershipsForUserParams) ([]ListMembershipsForUserRow, error) {
	rows, err := db.QueryContext(ctx, q.listMembershipsForUser,
		arg.Scope,
		arg.BelongsToUser,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListMembershipsForUserRow

	for rows.Next() {
		var i ListMembershipsForUserRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.BelongsToUser,
			&i.BelongsToAccount,
			&i.DefaultAccount,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListUsers runs the :many query against mysql.
func (q *mysqlQueries) ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := db.QueryContext(ctx, q.listUsers,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.IncludeArchived,
		arg.Scope,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListUsersRow

	for rows.Next() {
		var i ListUsersRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.Username,
			&i.EmailAddress,
			&i.FirstName,
			&i.LastName,
			&i.HashedPassword,
			&i.RequiresPasswordChange,
			&i.PasswordLastChangedAt,
			&i.TwoFactorSecret,
			&i.TwoFactorSecretVerifiedAt,
			&i.EmailAddressVerifiedAt,
			&i.EmailAddressVerificationToken,
			&i.AccountStatus,
			&i.AccountStatusExplanation,
			&i.LastAcceptedTermsOfService,
			&i.LastAcceptedPrivacyPolicy,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// MarkUserEmailAddressVerified runs the :execrows query against mysql.
func (q *mysqlQueries) MarkUserEmailAddressVerified(ctx context.Context, db DBTX, arg MarkUserEmailAddressVerifiedParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.markUserEmailAddressVerified,
		arg.EmailAddressVerifiedAt,
		arg.EmailAddressVerificationToken,
		arg.ID,
		arg.Scope,
		arg.CurrentEmailAddressVerificationToken,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// SetUserEmailAddressVerificationToken runs the :execrows query against mysql.
func (q *mysqlQueries) SetUserEmailAddressVerificationToken(ctx context.Context, db DBTX, arg SetUserEmailAddressVerificationTokenParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.setUserEmailAddressVerificationToken,
		arg.EmailAddressVerificationToken,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// SetUserRequiresPasswordChange runs the :execrows query against mysql.
func (q *mysqlQueries) SetUserRequiresPasswordChange(ctx context.Context, db DBTX, arg SetUserRequiresPasswordChangeParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.setUserRequiresPasswordChange,
		arg.RequiresPasswordChange,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// TransferAccountOwnership runs the :execrows query against mysql.
func (q *mysqlQueries) TransferAccountOwnership(ctx context.Context, db DBTX, arg TransferAccountOwnershipParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.transferAccountOwnership,
		arg.OwnerUserID,
		arg.ID,
		arg.Scope,
		arg.CurrentOwnerUserID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpdateAccount runs the :execrows query against mysql.
func (q *mysqlQueries) UpdateAccount(ctx context.Context, db DBTX, arg UpdateAccountParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateAccount,
		arg.Name,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressPostalCode,
		arg.AddressCountry,
		arg.AddressPhone,
		arg.TimeZone,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpdateUser runs the :execrows query against mysql.
func (q *mysqlQueries) UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateUser,
		arg.Username,
		arg.EmailAddress,
		arg.FirstName,
		arg.LastName,
		arg.EmailAddressVerifiedAt,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpdateUserAccountStatus runs the :execrows query against mysql.
func (q *mysqlQueries) UpdateUserAccountStatus(ctx context.Context, db DBTX, arg UpdateUserAccountStatusParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateUserAccountStatus,
		arg.AccountStatus,
		arg.AccountStatusExplanation,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpdateUserPassword runs the :execrows query against mysql.
func (q *mysqlQueries) UpdateUserPassword(ctx context.Context, db DBTX, arg UpdateUserPasswordParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateUserPassword,
		arg.HashedPassword,
		arg.RequiresPasswordChange,
		arg.PasswordLastChangedAt,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpdateUserTwoFactorSecret runs the :execrows query against mysql.
func (q *mysqlQueries) UpdateUserTwoFactorSecret(ctx context.Context, db DBTX, arg UpdateUserTwoFactorSecretParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateUserTwoFactorSecret,
		arg.TwoFactorSecret,
		arg.TwoFactorSecretVerifiedAt,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpsertMembership runs the :exec query against mysql.
func (q *mysqlQueries) UpsertMembership(ctx context.Context, db DBTX, arg UpsertMembershipParams) error {
	_, err := db.ExecContext(ctx, q.upsertMembership,
		arg.ID,
		arg.Scope,
		arg.BelongsToUser,
		arg.BelongsToAccount,
		arg.DefaultAccount,
	)

	return err
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		Status        string
		Note          string
		ToUser        *string
		ID            string
		Scope         tenancy.Scope
		CurrentStatus string
	}(AnswerInvitationParams{})
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(ArchiveAccountParams{})
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(ArchiveUserParams{})
	_ = struct {
		ID                          string
		Scope                       tenancy.Scope
		Name                        string
		OwnerUserID                 string
		BillingStatus               string
		SubscriptionPlanID          *string
		PaymentProcessorCustomerID  string
		LastPaymentProviderSyncedAt *time.Time
		AddressLine1                string
		AddressLine2                string
		AddressCity                 string
		AddressState                string
		AddressPostalCode           string
		AddressCountry              string
		AddressPhone                string
		TimeZone                    string
	}(CreateAccountParams{})
	_ = struct {
		ID               string
		Scope            tenancy.Scope
		BelongsToAccount string
		FromUser         string
		ToEmail          string
		ToName           string
		ToUser           *string
		Token            string
		Status           string
		Note             string
		ExpiresAt        time.Time
	}(CreateInvitationParams{})
	_ = struct {
		ID                            string
		Scope                         tenancy.Scope
		Username                      string
		EmailAddress                  string
		FirstName                     string
		LastName                      string
		HashedPassword                string
		RequiresPasswordChange        bool
		PasswordLastChangedAt         *time.Time
		TwoFactorSecret               string
		TwoFactorSecretVerifiedAt     *time.Time
		EmailAddressVerifiedAt        *time.Time
		EmailAddressVerificationToken string
		AccountStatus                 string
		AccountStatusExplanation      string
		LastAcceptedTermsOfService    *time.Time
		LastAcceptedPrivacyPolicy     *time.Time
	}(CreateUserParams{})
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(GetAccountParams{})
	_ = struct {
		ID                          string
		Scope                       tenancy.Scope
		Name                        string
		OwnerUserID                 string
		BillingStatus               string
		SubscriptionPlanID          *string
		PaymentProcessorCustomerID  string
		LastPaymentProviderSyncedAt *time.Time
		AddressLine1                string
		AddressLine2                string
		AddressCity                 string
		AddressState                string
		AddressPostalCode           string
		AddressCountry              string
		AddressPhone                string
		TimeZone                    string
		CreatedAt                   time.Time
		LastUpdatedAt               *time.Time
		ArchivedAt                  *time.Time
	}(GetAccountRow{})
	_ = struct {
		ID string
	}(GetAccountCreatedAtParams{})
	_ = struct {
		CreatedAt time.Time
	}(GetAccountCreatedAtRow{})
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(GetInvitationParams{})
	_ = struct {
		ID               string
		Scope            tenancy.Scope
		BelongsToAccount string
		FromUser         string
		ToEmail          string
		ToName           string
		ToUser           *string
		Token            string
		Status           string
		Note             string
		ExpiresAt        time.Time
		CreatedAt        time.Time
		LastUpdatedAt    *time.Time
		ArchivedAt       *time.Time
	}(GetInvitationRow{})
	_ = struct {
		ID string
	}(GetInvitationCreatedAtParams{})
	_ = struct {
		CreatedAt time.Time
	}(GetInvitationCreatedAtRow{})
	_ = struct {
		Scope            tenancy.Scope
		BelongsToUser    string
		BelongsToAccount string
	}(GetMembershipByUserAndAccountParams{})
	_ = struct {
		ID               string
		Scope            tenancy.Scope
		BelongsToUser    string
		BelongsToAccount string
		DefaultAccount   bool
		CreatedAt        time.Time
		LastUpdatedAt    *time.Time
		ArchivedAt       *time.Time
	}(GetMembershipByUserAndAccountRow{})
	_ = struct {
		Scope            tenancy.Scope
		BelongsToUser    string
		BelongsToAccount string
	}(GetMembershipFallbackAccountIDParams{})
	_ = struct {
		BelongsToAccount string
	}(GetMembershipFallbackAccountIDRow{})
	_ = struct {
		Scope            tenancy.Scope
		BelongsToUser    string
		BelongsToAccount string
	}(GetMembershipIDByUserAndAccountParams{})
	_ = struct {
		ID string
	}(GetMembershipIDByUserAndAccountRow{})
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(GetUserParams{})
	_ = struct {
		ID                            string
		Scope                         tenancy.Scope
		Username                      string
		EmailAddress                  string
		FirstName                     string
		LastName                      string
		HashedPassword                string
		RequiresPasswordChange        bool
		PasswordLastChangedAt         *time.Time
		TwoFactorSecret               string
		TwoFactorSecretVerifiedAt     *time.Time
		EmailAddressVerifiedAt        *time.Time
		EmailAddressVerificationToken string
		AccountStatus                 string
		AccountStatusExplanation      string
		LastAcceptedTermsOfService    *time.Time
		LastAcceptedPrivacyPolicy     *time.Time
		CreatedAt                     time.Time
		LastUpdatedAt                 *time.Time
		ArchivedAt                    *time.Time
	}(GetUserRow{})
	_ = struct {
		EmailAddress string
		Scope        tenancy.Scope
	}(GetUserByEmailAddressParams{})
	_ = struct {
		ID                            string
		Scope                         tenancy.Scope
		Username                      string
		EmailAddress                  string
		FirstName                     string
		LastName                      string
		HashedPassword                string
		RequiresPasswordChange        bool
		PasswordLastChangedAt         *time.Time
		TwoFactorSecret               string
		TwoFactorSecretVerifiedAt     *time.Time
		EmailAddressVerifiedAt        *time.Time
		EmailAddressVerificationToken string
		AccountStatus                 string
		AccountStatusExplanation      string
		LastAcceptedTermsOfService    *time.Time
		LastAcceptedPrivacyPolicy     *time.Time
		CreatedAt                     time.Time
		LastUpdatedAt                 *time.Time
		ArchivedAt                    *time.Time
	}(GetUserByEmailAddressRow{})
	_ = struct {
		EmailAddressVerificationToken string
		Scope                         tenancy.Scope
	}(GetUserByEmailVerificationTokenParams{})
	_ = struct {
		ID                            string
		Scope                         tenancy.Scope
		Username                      string
		EmailAddress                  string
		FirstName                     string
		LastName                      string
		HashedPassword                string
		RequiresPasswordChange        bool
		PasswordLastChangedAt         *time.Time
		TwoFactorSecret               string
		TwoFactorSecretVerifiedAt     *time.Time
		EmailAddressVerifiedAt        *time.Time
		EmailAddressVerificationToken string
		AccountStatus                 string
		AccountStatusExplanation      string
		LastAcceptedTermsOfService    *time.Time
		LastAcceptedPrivacyPolicy     *time.Time
		CreatedAt                     time.Time
		LastUpdatedAt                 *time.Time
		ArchivedAt                    *time.Time
	}(GetUserByEmailVerificationTokenRow{})
	_ = struct {
		Username string
		Scope    tenancy.Scope
	}(GetUserByUsernameParams{})
	_ = struct {
		ID                            string
		Scope                         tenancy.Scope
		Username                      string
		EmailAddress                  string
		FirstName                     string
		LastName                      string
		HashedPassword                string
		RequiresPasswordChange        bool
		PasswordLastChangedAt         *time.Time
		TwoFactorSecret               string
		TwoFactorSecretVerifiedAt     *time.Time
		EmailAddressVerifiedAt        *time.Time
		EmailAddressVerificationToken string
		AccountStatus                 string
		AccountStatusExplanation      string
		LastAcceptedTermsOfService    *time.Time
		LastAcceptedPrivacyPolicy     *time.Time
		CreatedAt                     time.Time
		LastUpdatedAt                 *time.Time
		ArchivedAt                    *time.Time
	}(GetUserByUsernameRow{})
	_ = struct {
		ID string
	}(GetUserCreatedAtParams{})
	_ = struct {
		CreatedAt time.Time
	}(GetUserCreatedAtRow{})
	_ = struct {
		CreatedAfter     *time.Time
		CreatedBefore    *time.Time
		UpdatedAfter     *time.Time
		UpdatedBefore    *time.Time
		IncludeArchived  bool
		Scope            tenancy.Scope
		BelongsToAccount string
		PageCursor       *string
		ResultLimit      int64
	}(ListAccountMembersParams{})
	_ = struct {
		ID                                string
		Scope                             tenancy.Scope
		BelongsToUser                     string
		BelongsToAccount                  string
		DefaultAccount                    bool
		CreatedAt                         time.Time
		LastUpdatedAt                     *time.Time
		ArchivedAt                        *time.Time
		UserID                            string
		UserScope                         tenancy.Scope
		UserUsername                      string
		UserEmailAddress                  string
		UserFirstName                     string
		UserLastName                      string
		UserHashedPassword                string
		UserRequiresPasswordChange        bool
		UserPasswordLastChangedAt         *time.Time
		UserTwoFactorSecret               string
		UserTwoFactorSecretVerifiedAt     *time.Time
		UserEmailAddressVerifiedAt        *time.Time
		UserEmailAddressVerificationToken string
		UserAccountStatus                 string
		UserAccountStatusExplanation      string
		UserLastAcceptedTermsOfService    *time.Time
		UserLastAcceptedPrivacyPolicy     *time.Time
		UserCreatedAt                     time.Time
		UserLastUpdatedAt                 *time.Time
		UserArchivedAt                    *time.Time
		FilteredCount                     int64
		TotalCount                        int64
	}(ListAccountMembersRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		PageCursor      *string
		ResultLimit     int64
	}(ListAccountsParams{})
	_ = struct {
		ID                          string
		Scope                       tenancy.Scope
		Name                        string
		OwnerUserID                 string
		BillingStatus               string
		SubscriptionPlanID          *string
		PaymentProcessorCustomerID  string
		LastPaymentProviderSyncedAt *time.Time
		AddressLine1                string
		AddressLine2                string
		AddressCity                 string
		AddressState                string
		AddressPostalCode           string
		AddressCountry              string
		AddressPhone                string
		TimeZone                    string
		CreatedAt                   time.Time
		LastUpdatedAt               *time.Time
		ArchivedAt                  *time.Time
		FilteredCount               int64
		TotalCount                  int64
	}(ListAccountsRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		BelongsToUser   string
		PageCursor      *string
		ResultLimit     int64
	}(ListAccountsForUserParams{})
	_ = struct {
		ID                          string
		Scope                       tenancy.Scope
		Name                        string
		OwnerUserID                 string
		BillingStatus               string
		SubscriptionPlanID          *string
		PaymentProcessorCustomerID  string
		LastPaymentProviderSyncedAt *time.Time
		AddressLine1                string
		AddressLine2                string
		AddressCity                 string
		AddressState                string
		AddressPostalCode           string
		AddressCountry              string
		AddressPhone                string
		TimeZone                    string
		CreatedAt                   time.Time
		LastUpdatedAt               *time.Time
		ArchivedAt                  *time.Time
		FilteredCount               int64
		TotalCount                  int64
	}(ListAccountsForUserRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		PageCursor      *string
		ResultLimit     int64
	}(ListInvitationsParams{})
	_ = struct {
		ID               string
		Scope            tenancy.Scope
		BelongsToAccount string
		FromUser         string
		ToEmail          string
		ToName           string
		ToUser           *string
		Token            string
		Status           string
		Note             string
		ExpiresAt        time.Time
		CreatedAt        time.Time
		LastUpdatedAt    *time.Time
		ArchivedAt       *time.Time
		FilteredCount    int64
		TotalCount       int64
	}(ListInvitationsRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		FromUser        string
		Status          string
		PageCursor      *string
		ResultLimit     int64
	}(ListInvitationsByFromUserParams{})
	_ = struct {
		ID               string
		Scope            tenancy.Scope
		BelongsToAccount string
		FromUser         string
		ToEmail          string
		ToName           string
		ToUser           *string
		Token            string
		Status           string
		Note             string
		ExpiresAt        time.Time
		CreatedAt        time.Time
		LastUpdatedAt    *time.Time
		ArchivedAt       *time.Time
		FilteredCount    int64
		TotalCount       int64
	}(ListInvitationsByFromUserRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		ToEmail         string
		Status          string
		PageCursor      *string
		ResultLimit     int64
	}(ListInvitationsByToEmailParams{})
	_ = struct {
		ID               string
		Scope            tenancy.Scope
		BelongsToAccount string
		FromUser         string
		ToEmail          string
		ToName           string
		ToUser           *string
		Token            string
		Status           string
		Note             string
		ExpiresAt        time.Time
		CreatedAt        time.Time
		LastUpdatedAt    *time.Time
		ArchivedAt       *time.Time
		FilteredCount    int64
		TotalCount       int64
	}(ListInvitationsByToEmailRow{})
	_ = struct {
		Scope         tenancy.Scope
		BelongsToUser string
	}(ListMembershipsForUserParams{})
	_ = struct {
		ID               string
		Scope            tenancy.Scope
		BelongsToUser    string
		BelongsToAccount string
		DefaultAccount   bool
		CreatedAt        time.Time
		LastUpdatedAt    *time.Time
		ArchivedAt       *time.Time
	}(ListMembershipsForUserRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		PageCursor      *string
		ResultLimit     int64
	}(ListUsersParams{})
	_ = struct {
		ID                            string
		Scope                         tenancy.Scope
		Username                      string
		EmailAddress                  string
		FirstName                     string
		LastName                      string
		HashedPassword                string
		RequiresPasswordChange        bool
		PasswordLastChangedAt         *time.Time
		TwoFactorSecret               string
		TwoFactorSecretVerifiedAt     *time.Time
		EmailAddressVerifiedAt        *time.Time
		EmailAddressVerificationToken string
		AccountStatus                 string
		AccountStatusExplanation      string
		LastAcceptedTermsOfService    *time.Time
		LastAcceptedPrivacyPolicy     *time.Time
		CreatedAt                     time.Time
		LastUpdatedAt                 *time.Time
		ArchivedAt                    *time.Time
		FilteredCount                 int64
		TotalCount                    int64
	}(ListUsersRow{})
	_ = struct {
		EmailAddressVerifiedAt               *time.Time
		EmailAddressVerificationToken        string
		ID                                   string
		Scope                                tenancy.Scope
		CurrentEmailAddressVerificationToken string
	}(MarkUserEmailAddressVerifiedParams{})
	_ = struct {
		EmailAddressVerificationToken string
		ID                            string
		Scope                         tenancy.Scope
	}(SetUserEmailAddressVerificationTokenParams{})
	_ = struct {
		RequiresPasswordChange bool
		ID                     string
		Scope                  tenancy.Scope
	}(SetUserRequiresPasswordChangeParams{})
	_ = struct {
		OwnerUserID        string
		ID                 string
		Scope              tenancy.Scope
		CurrentOwnerUserID string
	}(TransferAccountOwnershipParams{})
	_ = struct {
		Name              string
		AddressLine1      string
		AddressLine2      string
		AddressCity       string
		AddressState      string
		AddressPostalCode string
		AddressCountry    string
		AddressPhone      string
		TimeZone          string
		ID                string
		Scope             tenancy.Scope
	}(UpdateAccountParams{})
	_ = struct {
		Username               string
		EmailAddress           string
		FirstName              string
		LastName               string
		EmailAddressVerifiedAt *time.Time
		ID                     string
		Scope                  tenancy.Scope
	}(UpdateUserParams{})
	_ = struct {
		AccountStatus            string
		AccountStatusExplanation string
		ID                       string
		Scope                    tenancy.Scope
	}(UpdateUserAccountStatusParams{})
	_ = struct {
		HashedPassword         string
		RequiresPasswordChange bool
		PasswordLastChangedAt  *time.Time
		ID                     string
		Scope                  tenancy.Scope
	}(UpdateUserPasswordParams{})
	_ = struct {
		TwoFactorSecret           string
		TwoFactorSecretVerifiedAt *time.Time
		ID                        string
		Scope                     tenancy.Scope
	}(UpdateUserTwoFactorSecretParams{})
	_ = struct {
		ID               string
		Scope            tenancy.Scope
		BelongsToUser    string
		BelongsToAccount string
		DefaultAccount   bool
	}(UpsertMembershipParams{})
)
