// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package identitydb

import (
	"context"
)

// Querier is every query in this package, with one signature per query
// regardless of which dialect answers it.
//
// That is the point of this package: the params type, the row type, and the
// method signature are the same on every dialect, so nothing above this line
// knows or cares which database is underneath.
//
// # A note on the :execrows count
//
// MySQL reports rows *changed*: an UPDATE that sets a column to the value it
// already held affects zero rows there. Postgres and SQLite report rows
// *matched*, and count that same UPDATE as one.
//
// So a statement that gates on the count — treating zero as "not found" — is
// correct on two engines and wrong on the third. Either give it a predicate
// that discriminates, or set clientFoundRows=true in the MySQL DSN, which
// switches MySQL to matched semantics.
//
// # A note on empty lists
//
// A list parameter that is empty matches nothing, on every dialect: Postgres
// binds an empty array to `= ANY`, and the other two expand to `IN (NULL)` because
// `IN ()` is a syntax error there. Asking for the rows whose key is in an empty
// set gets no rows back, which is what the empty set says, so a caller does not
// have to guard the call.
//
// The negation is where they part company, and nothing below can warn you. An
// empty list makes `NOT IN (NULL)` never true, so it matches nothing, while
// Postgres's empty `<> ALL` is true and matches everything. Both readings are
// defensible and no shared signature can say which was meant — so test
// membership rather than its negation, and let the caller decide what an empty
// set means before it calls.
type Querier interface {
	// AnswerInvitation runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	AnswerInvitation(ctx context.Context, db DBTX, arg AnswerInvitationParams) (int64, error)
	// ArchiveAccount runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	ArchiveAccount(ctx context.Context, db DBTX, arg ArchiveAccountParams) (int64, error)
	// ArchiveUser runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	ArchiveUser(ctx context.Context, db DBTX, arg ArchiveUserParams) (int64, error)
	// CountSearchUsersByUsername runs the :one query.
	CountSearchUsersByUsername(ctx context.Context, db DBTX, arg CountSearchUsersByUsernameParams) (CountSearchUsersByUsernameRow, error)
	// CreateAccount runs the :exec query.
	CreateAccount(ctx context.Context, db DBTX, arg CreateAccountParams) error
	// CreateInvitation runs the :exec query.
	CreateInvitation(ctx context.Context, db DBTX, arg CreateInvitationParams) error
	// CreateUser runs the :exec query.
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) error
	// GetAccount runs the :one query.
	GetAccount(ctx context.Context, db DBTX, arg GetAccountParams) (GetAccountRow, error)
	// GetAccountCreatedAt runs the :one query.
	GetAccountCreatedAt(ctx context.Context, db DBTX, arg GetAccountCreatedAtParams) (GetAccountCreatedAtRow, error)
	// GetInvitation runs the :one query.
	GetInvitation(ctx context.Context, db DBTX, arg GetInvitationParams) (GetInvitationRow, error)
	// GetInvitationCreatedAt runs the :one query.
	GetInvitationCreatedAt(ctx context.Context, db DBTX, arg GetInvitationCreatedAtParams) (GetInvitationCreatedAtRow, error)
	// GetMembershipByUserAndAccount runs the :one query.
	GetMembershipByUserAndAccount(ctx context.Context, db DBTX, arg GetMembershipByUserAndAccountParams) (GetMembershipByUserAndAccountRow, error)
	// GetMembershipFallbackAccountID runs the :one query.
	GetMembershipFallbackAccountID(ctx context.Context, db DBTX, arg GetMembershipFallbackAccountIDParams) (GetMembershipFallbackAccountIDRow, error)
	// GetMembershipIDByUserAndAccount runs the :one query.
	GetMembershipIDByUserAndAccount(ctx context.Context, db DBTX, arg GetMembershipIDByUserAndAccountParams) (GetMembershipIDByUserAndAccountRow, error)
	// GetUser runs the :one query.
	GetUser(ctx context.Context, db DBTX, arg GetUserParams) (GetUserRow, error)
	// GetUserByEmailAddress runs the :one query.
	GetUserByEmailAddress(ctx context.Context, db DBTX, arg GetUserByEmailAddressParams) (GetUserByEmailAddressRow, error)
	// GetUserByEmailVerificationToken runs the :one query.
	GetUserByEmailVerificationToken(ctx context.Context, db DBTX, arg GetUserByEmailVerificationTokenParams) (GetUserByEmailVerificationTokenRow, error)
	// GetUserByUsername runs the :one query.
	GetUserByUsername(ctx context.Context, db DBTX, arg GetUserByUsernameParams) (GetUserByUsernameRow, error)
	// GetUserCreatedAt runs the :one query.
	GetUserCreatedAt(ctx context.Context, db DBTX, arg GetUserCreatedAtParams) (GetUserCreatedAtRow, error)
	// ListAccountMembers runs the :many query.
	ListAccountMembers(ctx context.Context, db DBTX, arg ListAccountMembersParams) ([]ListAccountMembersRow, error)
	// ListAccounts runs the :many query.
	ListAccounts(ctx context.Context, db DBTX, arg ListAccountsParams) ([]ListAccountsRow, error)
	// ListAccountsForUser runs the :many query.
	ListAccountsForUser(ctx context.Context, db DBTX, arg ListAccountsForUserParams) ([]ListAccountsForUserRow, error)
	// ListInvitationRolesByInvitationIDs runs the :many query.
	ListInvitationRolesByInvitationIDs(ctx context.Context, db DBTX, arg ListInvitationRolesByInvitationIDsParams) ([]ListInvitationRolesByInvitationIDsRow, error)
	// ListInvitations runs the :many query.
	ListInvitations(ctx context.Context, db DBTX, arg ListInvitationsParams) ([]ListInvitationsRow, error)
	// ListInvitationsByFromUser runs the :many query.
	ListInvitationsByFromUser(ctx context.Context, db DBTX, arg ListInvitationsByFromUserParams) ([]ListInvitationsByFromUserRow, error)
	// ListInvitationsByToEmail runs the :many query.
	ListInvitationsByToEmail(ctx context.Context, db DBTX, arg ListInvitationsByToEmailParams) ([]ListInvitationsByToEmailRow, error)
	// ListMembershipRolesByMembershipIDs runs the :many query.
	ListMembershipRolesByMembershipIDs(ctx context.Context, db DBTX, arg ListMembershipRolesByMembershipIDsParams) ([]ListMembershipRolesByMembershipIDsRow, error)
	// ListMembershipsForUser runs the :many query.
	ListMembershipsForUser(ctx context.Context, db DBTX, arg ListMembershipsForUserParams) ([]ListMembershipsForUserRow, error)
	// ListUserRolesByUserIDs runs the :many query.
	ListUserRolesByUserIDs(ctx context.Context, db DBTX, arg ListUserRolesByUserIDsParams) ([]ListUserRolesByUserIDsRow, error)
	// ListUsers runs the :many query.
	ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]ListUsersRow, error)
	// ListUsersByIDs runs the :many query.
	ListUsersByIDs(ctx context.Context, db DBTX, arg ListUsersByIDsParams) ([]ListUsersByIDsRow, error)
	// MarkAccountBillingSynced runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	MarkAccountBillingSynced(ctx context.Context, db DBTX, arg MarkAccountBillingSyncedParams) (int64, error)
	// MarkUserEmailAddressVerified runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	MarkUserEmailAddressVerified(ctx context.Context, db DBTX, arg MarkUserEmailAddressVerifiedParams) (int64, error)
	// RecordAccountSubscription runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	RecordAccountSubscription(ctx context.Context, db DBTX, arg RecordAccountSubscriptionParams) (int64, error)
	// SearchUsersByUsername runs the :many query.
	SearchUsersByUsername(ctx context.Context, db DBTX, arg SearchUsersByUsernameParams) ([]SearchUsersByUsernameRow, error)
	// SetAccountBillingStatus runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	SetAccountBillingStatus(ctx context.Context, db DBTX, arg SetAccountBillingStatusParams) (int64, error)
	// SetAccountPaymentProcessorCustomerID runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	SetAccountPaymentProcessorCustomerID(ctx context.Context, db DBTX, arg SetAccountPaymentProcessorCustomerIDParams) (int64, error)
	// SetUserEmailAddressVerificationToken runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	SetUserEmailAddressVerificationToken(ctx context.Context, db DBTX, arg SetUserEmailAddressVerificationTokenParams) (int64, error)
	// SetUserRequiresPasswordChange runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	SetUserRequiresPasswordChange(ctx context.Context, db DBTX, arg SetUserRequiresPasswordChangeParams) (int64, error)
	// TransferAccountOwnership runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	TransferAccountOwnership(ctx context.Context, db DBTX, arg TransferAccountOwnershipParams) (int64, error)
	// UpdateAccount runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	UpdateAccount(ctx context.Context, db DBTX, arg UpdateAccountParams) (int64, error)
	// UpdateUser runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (int64, error)
	// UpdateUserAccountStatus runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	UpdateUserAccountStatus(ctx context.Context, db DBTX, arg UpdateUserAccountStatusParams) (int64, error)
	// UpdateUserPassword runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	UpdateUserPassword(ctx context.Context, db DBTX, arg UpdateUserPasswordParams) (int64, error)
	// UpdateUserTwoFactorSecret runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	UpdateUserTwoFactorSecret(ctx context.Context, db DBTX, arg UpdateUserTwoFactorSecretParams) (int64, error)
	// UpsertMembership runs the :exec query.
	UpsertMembership(ctx context.Context, db DBTX, arg UpsertMembershipParams) error
}
