// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: dev

package identitydb

import (
	"time"

	"github.com/primandproper/platform-go/v13/tenancy"
)

// ArchiveAccountParams are the arguments to ArchiveAccount.
type ArchiveAccountParams struct {
	ID    string
	Scope tenancy.Scope
}

// ArchiveUserParams are the arguments to ArchiveUser.
type ArchiveUserParams struct {
	ID    string
	Scope tenancy.Scope
}

// CreateAccountParams are the arguments to CreateAccount.
type CreateAccountParams struct {
	ID                          string
	Scope                       tenancy.Scope
	Name                        string
	OwnerUserID                 string
	BillingStatus               string
	SubscriptionPlanID          *string
	PaymentProcessorCustomerID  string
	LastPaymentProviderSyncedAt *time.Time
	AddressLine1                string
	AddressLine2                string
	AddressCity                 string
	AddressState                string
	AddressPostalCode           string
	AddressCountry              string
	AddressPhone                string
	TimeZone                    string
}

// CreateInvitationParams are the arguments to CreateInvitation.
type CreateInvitationParams struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
}

// CreateUserParams are the arguments to CreateUser.
type CreateUserParams struct {
	ID                            string
	Scope                         tenancy.Scope
	Username                      string
	EmailAddress                  string
	FirstName                     string
	LastName                      string
	HashedPassword                string
	RequiresPasswordChange        bool
	PasswordLastChangedAt         *time.Time
	TwoFactorSecret               string
	TwoFactorSecretVerifiedAt     *time.Time
	EmailAddressVerifiedAt        *time.Time
	EmailAddressVerificationToken string
	AccountStatus                 string
	AccountStatusExplanation      string
	LastAcceptedTermsOfService    *time.Time
	LastAcceptedPrivacyPolicy     *time.Time
}

// GetAccountParams are the arguments to GetAccount.
type GetAccountParams struct {
	ID    string
	Scope tenancy.Scope
}

// GetAccountRow is one row of GetAccount's result.
type GetAccountRow struct {
	ID                          string
	Scope                       tenancy.Scope
	Name                        string
	OwnerUserID                 string
	BillingStatus               string
	SubscriptionPlanID          *string
	PaymentProcessorCustomerID  string
	LastPaymentProviderSyncedAt *time.Time
	AddressLine1                string
	AddressLine2                string
	AddressCity                 string
	AddressState                string
	AddressPostalCode           string
	AddressCountry              string
	AddressPhone                string
	TimeZone                    string
	CreatedAt                   time.Time
	LastUpdatedAt               *time.Time
	ArchivedAt                  *time.Time
}

// GetInvitationParams are the arguments to GetInvitation.
type GetInvitationParams struct {
	ID    string
	Scope tenancy.Scope
}

// GetInvitationRow is one row of GetInvitation's result.
type GetInvitationRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
}

// GetUserParams are the arguments to GetUser.
type GetUserParams struct {
	ID    string
	Scope tenancy.Scope
}

// GetUserRow is one row of GetUser's result.
type GetUserRow struct {
	ID                            string
	Scope                         tenancy.Scope
	Username                      string
	EmailAddress                  string
	FirstName                     string
	LastName                      string
	HashedPassword                string
	RequiresPasswordChange        bool
	PasswordLastChangedAt         *time.Time
	TwoFactorSecret               string
	TwoFactorSecretVerifiedAt     *time.Time
	EmailAddressVerifiedAt        *time.Time
	EmailAddressVerificationToken string
	AccountStatus                 string
	AccountStatusExplanation      string
	LastAcceptedTermsOfService    *time.Time
	LastAcceptedPrivacyPolicy     *time.Time
	CreatedAt                     time.Time
	LastUpdatedAt                 *time.Time
	ArchivedAt                    *time.Time
}

// ListAccountMembersParams are the arguments to ListAccountMembers.
type ListAccountMembersParams struct {
	CreatedAfter     *time.Time
	CreatedBefore    *time.Time
	UpdatedAfter     *time.Time
	UpdatedBefore    *time.Time
	IncludeArchived  bool
	Scope            tenancy.Scope
	BelongsToAccount string
	PageCursor       *string
	ResultLimit      int64
}

// ListAccountMembersRow is one row of ListAccountMembers's result.
type ListAccountMembersRow struct {
	ID                                string
	Scope                             tenancy.Scope
	BelongsToUser                     string
	BelongsToAccount                  string
	DefaultAccount                    bool
	CreatedAt                         time.Time
	LastUpdatedAt                     *time.Time
	ArchivedAt                        *time.Time
	UserID                            string
	UserScope                         tenancy.Scope
	UserUsername                      string
	UserEmailAddress                  string
	UserFirstName                     string
	UserLastName                      string
	UserHashedPassword                string
	UserRequiresPasswordChange        bool
	UserPasswordLastChangedAt         *time.Time
	UserTwoFactorSecret               string
	UserTwoFactorSecretVerifiedAt     *time.Time
	UserEmailAddressVerifiedAt        *time.Time
	UserEmailAddressVerificationToken string
	UserAccountStatus                 string
	UserAccountStatusExplanation      string
	UserLastAcceptedTermsOfService    *time.Time
	UserLastAcceptedPrivacyPolicy     *time.Time
	UserCreatedAt                     time.Time
	UserLastUpdatedAt                 *time.Time
	UserArchivedAt                    *time.Time
	FilteredCount                     int64
	TotalCount                        int64
}

// ListAccountsParams are the arguments to ListAccounts.
type ListAccountsParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	PageCursor      *string
	ResultLimit     int64
}

// ListAccountsRow is one row of ListAccounts's result.
type ListAccountsRow struct {
	ID                          string
	Scope                       tenancy.Scope
	Name                        string
	OwnerUserID                 string
	BillingStatus               string
	SubscriptionPlanID          *string
	PaymentProcessorCustomerID  string
	LastPaymentProviderSyncedAt *time.Time
	AddressLine1                string
	AddressLine2                string
	AddressCity                 string
	AddressState                string
	AddressPostalCode           string
	AddressCountry              string
	AddressPhone                string
	TimeZone                    string
	CreatedAt                   time.Time
	LastUpdatedAt               *time.Time
	ArchivedAt                  *time.Time
	FilteredCount               int64
	TotalCount                  int64
}

// ListAccountsForUserParams are the arguments to ListAccountsForUser.
type ListAccountsForUserParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	BelongsToUser   string
	PageCursor      *string
	ResultLimit     int64
}

// ListAccountsForUserRow is one row of ListAccountsForUser's result.
type ListAccountsForUserRow struct {
	ID                          string
	Scope                       tenancy.Scope
	Name                        string
	OwnerUserID                 string
	BillingStatus               string
	SubscriptionPlanID          *string
	PaymentProcessorCustomerID  string
	LastPaymentProviderSyncedAt *time.Time
	AddressLine1                string
	AddressLine2                string
	AddressCity                 string
	AddressState                string
	AddressPostalCode           string
	AddressCountry              string
	AddressPhone                string
	TimeZone                    string
	CreatedAt                   time.Time
	LastUpdatedAt               *time.Time
	ArchivedAt                  *time.Time
	FilteredCount               int64
	TotalCount                  int64
}

// ListInvitationsParams are the arguments to ListInvitations.
type ListInvitationsParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	PageCursor      *string
	ResultLimit     int64
}

// ListInvitationsRow is one row of ListInvitations's result.
type ListInvitationsRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
	FilteredCount    int64
	TotalCount       int64
}

// ListInvitationsByFromUserParams are the arguments to ListInvitationsByFromUser.
type ListInvitationsByFromUserParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	FromUser        string
	Status          string
	PageCursor      *string
	ResultLimit     int64
}

// ListInvitationsByFromUserRow is one row of ListInvitationsByFromUser's result.
type ListInvitationsByFromUserRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
	FilteredCount    int64
	TotalCount       int64
}

// ListInvitationsByToEmailParams are the arguments to ListInvitationsByToEmail.
type ListInvitationsByToEmailParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	ToEmail         string
	Status          string
	PageCursor      *string
	ResultLimit     int64
}

// ListInvitationsByToEmailRow is one row of ListInvitationsByToEmail's result.
type ListInvitationsByToEmailRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
	FilteredCount    int64
	TotalCount       int64
}

// ListMembershipsForUserParams are the arguments to ListMembershipsForUser.
type ListMembershipsForUserParams struct {
	Scope         tenancy.Scope
	BelongsToUser string
}

// ListMembershipsForUserRow is one row of ListMembershipsForUser's result.
type ListMembershipsForUserRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToUser    string
	BelongsToAccount string
	DefaultAccount   bool
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
}

// ListUsersParams are the arguments to ListUsers.
type ListUsersParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	PageCursor      *string
	ResultLimit     int64
}

// ListUsersRow is one row of ListUsers's result.
type ListUsersRow struct {
	ID                            string
	Scope                         tenancy.Scope
	Username                      string
	EmailAddress                  string
	FirstName                     string
	LastName                      string
	HashedPassword                string
	RequiresPasswordChange        bool
	PasswordLastChangedAt         *time.Time
	TwoFactorSecret               string
	TwoFactorSecretVerifiedAt     *time.Time
	EmailAddressVerifiedAt        *time.Time
	EmailAddressVerificationToken string
	AccountStatus                 string
	AccountStatusExplanation      string
	LastAcceptedTermsOfService    *time.Time
	LastAcceptedPrivacyPolicy     *time.Time
	CreatedAt                     time.Time
	LastUpdatedAt                 *time.Time
	ArchivedAt                    *time.Time
	FilteredCount                 int64
	TotalCount                    int64
}

// UpdateAccountParams are the arguments to UpdateAccount.
type UpdateAccountParams struct {
	Name              string
	AddressLine1      string
	AddressLine2      string
	AddressCity       string
	AddressState      string
	AddressPostalCode string
	AddressCountry    string
	AddressPhone      string
	TimeZone          string
	ID                string
	Scope             tenancy.Scope
}

// UpdateUserParams are the arguments to UpdateUser.
type UpdateUserParams struct {
	Username               string
	EmailAddress           string
	FirstName              string
	LastName               string
	EmailAddressVerifiedAt *time.Time
	ID                     string
	Scope                  tenancy.Scope
}
