// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: dev

package identitydb

import (
	"time"

	"github.com/primandproper/platform-go/v13/tenancy"
)

// AnswerInvitationParams are the arguments to AnswerInvitation.
type AnswerInvitationParams struct {
	Status        string
	Note          string
	ToUser        *string
	ID            string
	Scope         tenancy.Scope
	CurrentStatus string
}

// ArchiveAccountParams are the arguments to ArchiveAccount.
type ArchiveAccountParams struct {
	ID    string
	Scope tenancy.Scope
}

// ArchiveUserParams are the arguments to ArchiveUser.
type ArchiveUserParams struct {
	ID    string
	Scope tenancy.Scope
}

// CountSearchUsersByUsernameParams are the arguments to CountSearchUsersByUsername.
type CountSearchUsersByUsernameParams struct {
	Scope          tenancy.Scope
	UsernamePrefix string
}

// CountSearchUsersByUsernameRow is one row of CountSearchUsersByUsername's result.
type CountSearchUsersByUsernameRow struct {
	Count int64
}

// CreateAccountParams are the arguments to CreateAccount.
type CreateAccountParams struct {
	ID                          string
	Scope                       tenancy.Scope
	Name                        string
	OwnerUserID                 string
	BillingStatus               string
	SubscriptionPlanID          *string
	PaymentProcessorCustomerID  string
	LastPaymentProviderSyncedAt *time.Time
	AddressLine1                string
	AddressLine2                string
	AddressCity                 string
	AddressState                string
	AddressPostalCode           string
	AddressCountry              string
	AddressPhone                string
	TimeZone                    string
}

// CreateInvitationParams are the arguments to CreateInvitation.
type CreateInvitationParams struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
}

// CreateUserParams are the arguments to CreateUser.
type CreateUserParams struct {
	ID                            string
	Scope                         tenancy.Scope
	Username                      string
	EmailAddress                  string
	FirstName                     string
	LastName                      string
	HashedPassword                string
	RequiresPasswordChange        bool
	PasswordLastChangedAt         *time.Time
	TwoFactorSecret               string
	TwoFactorSecretVerifiedAt     *time.Time
	EmailAddressVerifiedAt        *time.Time
	EmailAddressVerificationToken string
	AccountStatus                 string
	AccountStatusExplanation      string
	LastAcceptedTermsOfService    *time.Time
	LastAcceptedPrivacyPolicy     *time.Time
}

// GetAccountParams are the arguments to GetAccount.
type GetAccountParams struct {
	ID    string
	Scope tenancy.Scope
}

// GetAccountRow is one row of GetAccount's result.
type GetAccountRow struct {
	ID                          string
	Scope                       tenancy.Scope
	Name                        string
	OwnerUserID                 string
	BillingStatus               string
	SubscriptionPlanID          *string
	PaymentProcessorCustomerID  string
	LastPaymentProviderSyncedAt *time.Time
	AddressLine1                string
	AddressLine2                string
	AddressCity                 string
	AddressState                string
	AddressPostalCode           string
	AddressCountry              string
	AddressPhone                string
	TimeZone                    string
	CreatedAt                   time.Time
	LastUpdatedAt               *time.Time
	ArchivedAt                  *time.Time
}

// GetAccountCreatedAtParams are the arguments to GetAccountCreatedAt.
type GetAccountCreatedAtParams struct {
	ID string
}

// GetAccountCreatedAtRow is one row of GetAccountCreatedAt's result.
type GetAccountCreatedAtRow struct {
	CreatedAt time.Time
}

// GetInvitationParams are the arguments to GetInvitation.
type GetInvitationParams struct {
	ID    string
	Scope tenancy.Scope
}

// GetInvitationRow is one row of GetInvitation's result.
type GetInvitationRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
}

// GetInvitationCreatedAtParams are the arguments to GetInvitationCreatedAt.
type GetInvitationCreatedAtParams struct {
	ID string
}

// GetInvitationCreatedAtRow is one row of GetInvitationCreatedAt's result.
type GetInvitationCreatedAtRow struct {
	CreatedAt time.Time
}

// GetMembershipByUserAndAccountParams are the arguments to GetMembershipByUserAndAccount.
type GetMembershipByUserAndAccountParams struct {
	Scope            tenancy.Scope
	BelongsToUser    string
	BelongsToAccount string
}

// GetMembershipByUserAndAccountRow is one row of GetMembershipByUserAndAccount's result.
type GetMembershipByUserAndAccountRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToUser    string
	BelongsToAccount string
	DefaultAccount   bool
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
}

// GetMembershipFallbackAccountIDParams are the arguments to GetMembershipFallbackAccountID.
type GetMembershipFallbackAccountIDParams struct {
	Scope            tenancy.Scope
	BelongsToUser    string
	BelongsToAccount string
}

// GetMembershipFallbackAccountIDRow is one row of GetMembershipFallbackAccountID's result.
type GetMembershipFallbackAccountIDRow struct {
	BelongsToAccount string
}

// GetMembershipIDByUserAndAccountParams are the arguments to GetMembershipIDByUserAndAccount.
type GetMembershipIDByUserAndAccountParams struct {
	Scope            tenancy.Scope
	BelongsToUser    string
	BelongsToAccount string
}

// GetMembershipIDByUserAndAccountRow is one row of GetMembershipIDByUserAndAccount's result.
type GetMembershipIDByUserAndAccountRow struct {
	ID string
}

// GetUserParams are the arguments to GetUser.
type GetUserParams struct {
	ID    string
	Scope tenancy.Scope
}

// GetUserRow is one row of GetUser's result.
type GetUserRow struct {
	ID                            string
	Scope                         tenancy.Scope
	Username                      string
	EmailAddress                  string
	FirstName                     string
	LastName                      string
	HashedPassword                string
	RequiresPasswordChange        bool
	PasswordLastChangedAt         *time.Time
	TwoFactorSecret               string
	TwoFactorSecretVerifiedAt     *time.Time
	EmailAddressVerifiedAt        *time.Time
	EmailAddressVerificationToken string
	AccountStatus                 string
	AccountStatusExplanation      string
	LastAcceptedTermsOfService    *time.Time
	LastAcceptedPrivacyPolicy     *time.Time
	CreatedAt                     time.Time
	LastUpdatedAt                 *time.Time
	ArchivedAt                    *time.Time
}

// GetUserByEmailAddressParams are the arguments to GetUserByEmailAddress.
type GetUserByEmailAddressParams struct {
	EmailAddress string
	Scope        tenancy.Scope
}

// GetUserByEmailAddressRow is one row of GetUserByEmailAddress's result.
type GetUserByEmailAddressRow struct {
	ID                            string
	Scope                         tenancy.Scope
	Username                      string
	EmailAddress                  string
	FirstName                     string
	LastName                      string
	HashedPassword                string
	RequiresPasswordChange        bool
	PasswordLastChangedAt         *time.Time
	TwoFactorSecret               string
	TwoFactorSecretVerifiedAt     *time.Time
	EmailAddressVerifiedAt        *time.Time
	EmailAddressVerificationToken string
	AccountStatus                 string
	AccountStatusExplanation      string
	LastAcceptedTermsOfService    *time.Time
	LastAcceptedPrivacyPolicy     *time.Time
	CreatedAt                     time.Time
	LastUpdatedAt                 *time.Time
	ArchivedAt                    *time.Time
}

// GetUserByEmailVerificationTokenParams are the arguments to GetUserByEmailVerificationToken.
type GetUserByEmailVerificationTokenParams struct {
	EmailAddressVerificationToken string
	Scope                         tenancy.Scope
}

// GetUserByEmailVerificationTokenRow is one row of GetUserByEmailVerificationToken's result.
type GetUserByEmailVerificationTokenRow struct {
	ID                            string
	Scope                         tenancy.Scope
	Username                      string
	EmailAddress                  string
	FirstName                     string
	LastName                      string
	HashedPassword                string
	RequiresPasswordChange        bool
	PasswordLastChangedAt         *time.Time
	TwoFactorSecret               string
	TwoFactorSecretVerifiedAt     *time.Time
	EmailAddressVerifiedAt        *time.Time
	EmailAddressVerificationToken string
	AccountStatus                 string
	AccountStatusExplanation      string
	LastAcceptedTermsOfService    *time.Time
	LastAcceptedPrivacyPolicy     *time.Time
	CreatedAt                     time.Time
	LastUpdatedAt                 *time.Time
	ArchivedAt                    *time.Time
}

// GetUserByUsernameParams are the arguments to GetUserByUsername.
type GetUserByUsernameParams struct {
	Username string
	Scope    tenancy.Scope
}

// GetUserByUsernameRow is one row of GetUserByUsername's result.
type GetUserByUsernameRow struct {
	ID                            string
	Scope                         tenancy.Scope
	Username                      string
	EmailAddress                  string
	FirstName                     string
	LastName                      string
	HashedPassword                string
	RequiresPasswordChange        bool
	PasswordLastChangedAt         *time.Time
	TwoFactorSecret               string
	TwoFactorSecretVerifiedAt     *time.Time
	EmailAddressVerifiedAt        *time.Time
	EmailAddressVerificationToken string
	AccountStatus                 string
	AccountStatusExplanation      string
	LastAcceptedTermsOfService    *time.Time
	LastAcceptedPrivacyPolicy     *time.Time
	CreatedAt                     time.Time
	LastUpdatedAt                 *time.Time
	ArchivedAt                    *time.Time
}

// GetUserCreatedAtParams are the arguments to GetUserCreatedAt.
type GetUserCreatedAtParams struct {
	ID string
}

// GetUserCreatedAtRow is one row of GetUserCreatedAt's result.
type GetUserCreatedAtRow struct {
	CreatedAt time.Time
}

// ListAccountMembersParams are the arguments to ListAccountMembers.
type ListAccountMembersParams struct {
	CreatedAfter     *time.Time
	CreatedBefore    *time.Time
	UpdatedAfter     *time.Time
	UpdatedBefore    *time.Time
	IncludeArchived  bool
	Scope            tenancy.Scope
	BelongsToAccount string
	PageCursor       *string
	ResultLimit      int64
}

// ListAccountMembersRow is one row of ListAccountMembers's result.
type ListAccountMembersRow struct {
	ID                                string
	Scope                             tenancy.Scope
	BelongsToUser                     string
	BelongsToAccount                  string
	DefaultAccount                    bool
	CreatedAt                         time.Time
	LastUpdatedAt                     *time.Time
	ArchivedAt                        *time.Time
	UserID                            string
	UserScope                         tenancy.Scope
	UserUsername                      string
	UserEmailAddress                  string
	UserFirstName                     string
	UserLastName                      string
	UserHashedPassword                string
	UserRequiresPasswordChange        bool
	UserPasswordLastChangedAt         *time.Time
	UserTwoFactorSecret               string
	UserTwoFactorSecretVerifiedAt     *time.Time
	UserEmailAddressVerifiedAt        *time.Time
	UserEmailAddressVerificationToken string
	UserAccountStatus                 string
	UserAccountStatusExplanation      string
	UserLastAcceptedTermsOfService    *time.Time
	UserLastAcceptedPrivacyPolicy     *time.Time
	UserCreatedAt                     time.Time
	UserLastUpdatedAt                 *time.Time
	UserArchivedAt                    *time.Time
	FilteredCount                     int64
	TotalCount                        int64
}

// ListAccountMembersDescendingParams are the arguments to ListAccountMembersDescending.
type ListAccountMembersDescendingParams struct {
	CreatedAfter     *time.Time
	CreatedBefore    *time.Time
	UpdatedAfter     *time.Time
	UpdatedBefore    *time.Time
	IncludeArchived  bool
	Scope            tenancy.Scope
	BelongsToAccount string
	PageCursor       *string
	ResultLimit      int64
}

// ListAccountMembersDescendingRow is one row of ListAccountMembersDescending's result.
type ListAccountMembersDescendingRow struct {
	ID                                string
	Scope                             tenancy.Scope
	BelongsToUser                     string
	BelongsToAccount                  string
	DefaultAccount                    bool
	CreatedAt                         time.Time
	LastUpdatedAt                     *time.Time
	ArchivedAt                        *time.Time
	UserID                            string
	UserScope                         tenancy.Scope
	UserUsername                      string
	UserEmailAddress                  string
	UserFirstName                     string
	UserLastName                      string
	UserHashedPassword                string
	UserRequiresPasswordChange        bool
	UserPasswordLastChangedAt         *time.Time
	UserTwoFactorSecret               string
	UserTwoFactorSecretVerifiedAt     *time.Time
	UserEmailAddressVerifiedAt        *time.Time
	UserEmailAddressVerificationToken string
	UserAccountStatus                 string
	UserAccountStatusExplanation      string
	UserLastAcceptedTermsOfService    *time.Time
	UserLastAcceptedPrivacyPolicy     *time.Time
	UserCreatedAt                     time.Time
	UserLastUpdatedAt                 *time.Time
	UserArchivedAt                    *time.Time
	FilteredCount                     int64
	TotalCount                        int64
}

// ListAccountsParams are the arguments to ListAccounts.
type ListAccountsParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	PageCursor      *string
	ResultLimit     int64
}

// ListAccountsRow is one row of ListAccounts's result.
type ListAccountsRow struct {
	ID                          string
	Scope                       tenancy.Scope
	Name                        string
	OwnerUserID                 string
	BillingStatus               string
	SubscriptionPlanID          *string
	PaymentProcessorCustomerID  string
	LastPaymentProviderSyncedAt *time.Time
	AddressLine1                string
	AddressLine2                string
	AddressCity                 string
	AddressState                string
	AddressPostalCode           string
	AddressCountry              string
	AddressPhone                string
	TimeZone                    string
	CreatedAt                   time.Time
	LastUpdatedAt               *time.Time
	ArchivedAt                  *time.Time
	FilteredCount               int64
	TotalCount                  int64
}

// ListAccountsDescendingParams are the arguments to ListAccountsDescending.
type ListAccountsDescendingParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	PageCursor      *string
	ResultLimit     int64
}

// ListAccountsDescendingRow is one row of ListAccountsDescending's result.
type ListAccountsDescendingRow struct {
	ID                          string
	Scope                       tenancy.Scope
	Name                        string
	OwnerUserID                 string
	BillingStatus               string
	SubscriptionPlanID          *string
	PaymentProcessorCustomerID  string
	LastPaymentProviderSyncedAt *time.Time
	AddressLine1                string
	AddressLine2                string
	AddressCity                 string
	AddressState                string
	AddressPostalCode           string
	AddressCountry              string
	AddressPhone                string
	TimeZone                    string
	CreatedAt                   time.Time
	LastUpdatedAt               *time.Time
	ArchivedAt                  *time.Time
	FilteredCount               int64
	TotalCount                  int64
}

// ListAccountsForUserParams are the arguments to ListAccountsForUser.
type ListAccountsForUserParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	BelongsToUser   string
	PageCursor      *string
	ResultLimit     int64
}

// ListAccountsForUserRow is one row of ListAccountsForUser's result.
type ListAccountsForUserRow struct {
	ID                          string
	Scope                       tenancy.Scope
	Name                        string
	OwnerUserID                 string
	BillingStatus               string
	SubscriptionPlanID          *string
	PaymentProcessorCustomerID  string
	LastPaymentProviderSyncedAt *time.Time
	AddressLine1                string
	AddressLine2                string
	AddressCity                 string
	AddressState                string
	AddressPostalCode           string
	AddressCountry              string
	AddressPhone                string
	TimeZone                    string
	CreatedAt                   time.Time
	LastUpdatedAt               *time.Time
	ArchivedAt                  *time.Time
	FilteredCount               int64
	TotalCount                  int64
}

// ListAccountsForUserDescendingParams are the arguments to ListAccountsForUserDescending.
type ListAccountsForUserDescendingParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	BelongsToUser   string
	PageCursor      *string
	ResultLimit     int64
}

// ListAccountsForUserDescendingRow is one row of ListAccountsForUserDescending's result.
type ListAccountsForUserDescendingRow struct {
	ID                          string
	Scope                       tenancy.Scope
	Name                        string
	OwnerUserID                 string
	BillingStatus               string
	SubscriptionPlanID          *string
	PaymentProcessorCustomerID  string
	LastPaymentProviderSyncedAt *time.Time
	AddressLine1                string
	AddressLine2                string
	AddressCity                 string
	AddressState                string
	AddressPostalCode           string
	AddressCountry              string
	AddressPhone                string
	TimeZone                    string
	CreatedAt                   time.Time
	LastUpdatedAt               *time.Time
	ArchivedAt                  *time.Time
	FilteredCount               int64
	TotalCount                  int64
}

// ListInvitationsParams are the arguments to ListInvitations.
type ListInvitationsParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	PageCursor      *string
	ResultLimit     int64
}

// ListInvitationsRow is one row of ListInvitations's result.
type ListInvitationsRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
	FilteredCount    int64
	TotalCount       int64
}

// ListInvitationsByFromUserParams are the arguments to ListInvitationsByFromUser.
type ListInvitationsByFromUserParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	FromUser        string
	Status          string
	PageCursor      *string
	ResultLimit     int64
}

// ListInvitationsByFromUserRow is one row of ListInvitationsByFromUser's result.
type ListInvitationsByFromUserRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
	FilteredCount    int64
	TotalCount       int64
}

// ListInvitationsByFromUserDescendingParams are the arguments to ListInvitationsByFromUserDescending.
type ListInvitationsByFromUserDescendingParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	FromUser        string
	Status          string
	PageCursor      *string
	ResultLimit     int64
}

// ListInvitationsByFromUserDescendingRow is one row of ListInvitationsByFromUserDescending's result.
type ListInvitationsByFromUserDescendingRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
	FilteredCount    int64
	TotalCount       int64
}

// ListInvitationsByToEmailParams are the arguments to ListInvitationsByToEmail.
type ListInvitationsByToEmailParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	ToEmail         string
	Status          string
	PageCursor      *string
	ResultLimit     int64
}

// ListInvitationsByToEmailRow is one row of ListInvitationsByToEmail's result.
type ListInvitationsByToEmailRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
	FilteredCount    int64
	TotalCount       int64
}

// ListInvitationsByToEmailDescendingParams are the arguments to ListInvitationsByToEmailDescending.
type ListInvitationsByToEmailDescendingParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	ToEmail         string
	Status          string
	PageCursor      *string
	ResultLimit     int64
}

// ListInvitationsByToEmailDescendingRow is one row of ListInvitationsByToEmailDescending's result.
type ListInvitationsByToEmailDescendingRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
	FilteredCount    int64
	TotalCount       int64
}

// ListInvitationsDescendingParams are the arguments to ListInvitationsDescending.
type ListInvitationsDescendingParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	PageCursor      *string
	ResultLimit     int64
}

// ListInvitationsDescendingRow is one row of ListInvitationsDescending's result.
type ListInvitationsDescendingRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToAccount string
	FromUser         string
	ToEmail          string
	ToName           string
	ToUser           *string
	Token            string
	Status           string
	Note             string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
	FilteredCount    int64
	TotalCount       int64
}

// ListMembershipsForUserParams are the arguments to ListMembershipsForUser.
type ListMembershipsForUserParams struct {
	Scope         tenancy.Scope
	BelongsToUser string
}

// ListMembershipsForUserRow is one row of ListMembershipsForUser's result.
type ListMembershipsForUserRow struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToUser    string
	BelongsToAccount string
	DefaultAccount   bool
	CreatedAt        time.Time
	LastUpdatedAt    *time.Time
	ArchivedAt       *time.Time
}

// ListUsersParams are the arguments to ListUsers.
type ListUsersParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	PageCursor      *string
	ResultLimit     int64
}

// ListUsersRow is one row of ListUsers's result.
type ListUsersRow struct {
	ID                            string
	Scope                         tenancy.Scope
	Username                      string
	EmailAddress                  string
	FirstName                     string
	LastName                      string
	HashedPassword                string
	RequiresPasswordChange        bool
	PasswordLastChangedAt         *time.Time
	TwoFactorSecret               string
	TwoFactorSecretVerifiedAt     *time.Time
	EmailAddressVerifiedAt        *time.Time
	EmailAddressVerificationToken string
	AccountStatus                 string
	AccountStatusExplanation      string
	LastAcceptedTermsOfService    *time.Time
	LastAcceptedPrivacyPolicy     *time.Time
	CreatedAt                     time.Time
	LastUpdatedAt                 *time.Time
	ArchivedAt                    *time.Time
	FilteredCount                 int64
	TotalCount                    int64
}

// ListUsersDescendingParams are the arguments to ListUsersDescending.
type ListUsersDescendingParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	PageCursor      *string
	ResultLimit     int64
}

// ListUsersDescendingRow is one row of ListUsersDescending's result.
type ListUsersDescendingRow struct {
	ID                            string
	Scope                         tenancy.Scope
	Username                      string
	EmailAddress                  string
	FirstName                     string
	LastName                      string
	HashedPassword                string
	RequiresPasswordChange        bool
	PasswordLastChangedAt         *time.Time
	TwoFactorSecret               string
	TwoFactorSecretVerifiedAt     *time.Time
	EmailAddressVerifiedAt        *time.Time
	EmailAddressVerificationToken string
	AccountStatus                 string
	AccountStatusExplanation      string
	LastAcceptedTermsOfService    *time.Time
	LastAcceptedPrivacyPolicy     *time.Time
	CreatedAt                     time.Time
	LastUpdatedAt                 *time.Time
	ArchivedAt                    *time.Time
	FilteredCount                 int64
	TotalCount                    int64
}

// MarkAccountBillingSyncedParams are the arguments to MarkAccountBillingSynced.
type MarkAccountBillingSyncedParams struct {
	LastPaymentProviderSyncedAt *time.Time
	ID                          string
	Scope                       tenancy.Scope
}

// MarkUserEmailAddressVerifiedParams are the arguments to MarkUserEmailAddressVerified.
type MarkUserEmailAddressVerifiedParams struct {
	EmailAddressVerifiedAt               *time.Time
	EmailAddressVerificationToken        string
	ID                                   string
	Scope                                tenancy.Scope
	CurrentEmailAddressVerificationToken string
}

// RecordAccountSubscriptionParams are the arguments to RecordAccountSubscription.
type RecordAccountSubscriptionParams struct {
	BillingStatus               string
	SubscriptionPlanID          *string
	LastPaymentProviderSyncedAt *time.Time
	ID                          string
	Scope                       tenancy.Scope
}

// SearchUsersByUsernameParams are the arguments to SearchUsersByUsername.
type SearchUsersByUsernameParams struct {
	Scope          tenancy.Scope
	UsernamePrefix string
	PageCursor     *string
	ResultLimit    int64
}

// SearchUsersByUsernameRow is one row of SearchUsersByUsername's result.
type SearchUsersByUsernameRow struct {
	ID                            string
	Scope                         tenancy.Scope
	Username                      string
	EmailAddress                  string
	FirstName                     string
	LastName                      string
	HashedPassword                string
	RequiresPasswordChange        bool
	PasswordLastChangedAt         *time.Time
	TwoFactorSecret               string
	TwoFactorSecretVerifiedAt     *time.Time
	EmailAddressVerifiedAt        *time.Time
	EmailAddressVerificationToken string
	AccountStatus                 string
	AccountStatusExplanation      string
	LastAcceptedTermsOfService    *time.Time
	LastAcceptedPrivacyPolicy     *time.Time
	CreatedAt                     time.Time
	LastUpdatedAt                 *time.Time
	ArchivedAt                    *time.Time
}

// SearchUsersByUsernameDescendingParams are the arguments to SearchUsersByUsernameDescending.
type SearchUsersByUsernameDescendingParams struct {
	Scope          tenancy.Scope
	UsernamePrefix string
	PageCursor     *string
	ResultLimit    int64
}

// SearchUsersByUsernameDescendingRow is one row of SearchUsersByUsernameDescending's result.
type SearchUsersByUsernameDescendingRow struct {
	ID                            string
	Scope                         tenancy.Scope
	Username                      string
	EmailAddress                  string
	FirstName                     string
	LastName                      string
	HashedPassword                string
	RequiresPasswordChange        bool
	PasswordLastChangedAt         *time.Time
	TwoFactorSecret               string
	TwoFactorSecretVerifiedAt     *time.Time
	EmailAddressVerifiedAt        *time.Time
	EmailAddressVerificationToken string
	AccountStatus                 string
	AccountStatusExplanation      string
	LastAcceptedTermsOfService    *time.Time
	LastAcceptedPrivacyPolicy     *time.Time
	CreatedAt                     time.Time
	LastUpdatedAt                 *time.Time
	ArchivedAt                    *time.Time
}

// SetAccountBillingStatusParams are the arguments to SetAccountBillingStatus.
type SetAccountBillingStatusParams struct {
	BillingStatus string
	ID            string
	Scope         tenancy.Scope
}

// SetAccountPaymentProcessorCustomerIDParams are the arguments to SetAccountPaymentProcessorCustomerID.
type SetAccountPaymentProcessorCustomerIDParams struct {
	PaymentProcessorCustomerID string
	ID                         string
	Scope                      tenancy.Scope
}

// SetUserEmailAddressVerificationTokenParams are the arguments to SetUserEmailAddressVerificationToken.
type SetUserEmailAddressVerificationTokenParams struct {
	EmailAddressVerificationToken string
	ID                            string
	Scope                         tenancy.Scope
}

// SetUserRequiresPasswordChangeParams are the arguments to SetUserRequiresPasswordChange.
type SetUserRequiresPasswordChangeParams struct {
	RequiresPasswordChange bool
	ID                     string
	Scope                  tenancy.Scope
}

// TransferAccountOwnershipParams are the arguments to TransferAccountOwnership.
type TransferAccountOwnershipParams struct {
	OwnerUserID        string
	ID                 string
	Scope              tenancy.Scope
	CurrentOwnerUserID string
}

// UpdateAccountParams are the arguments to UpdateAccount.
type UpdateAccountParams struct {
	Name              string
	AddressLine1      string
	AddressLine2      string
	AddressCity       string
	AddressState      string
	AddressPostalCode string
	AddressCountry    string
	AddressPhone      string
	TimeZone          string
	ID                string
	Scope             tenancy.Scope
}

// UpdateUserParams are the arguments to UpdateUser.
type UpdateUserParams struct {
	Username               string
	EmailAddress           string
	FirstName              string
	LastName               string
	EmailAddressVerifiedAt *time.Time
	ID                     string
	Scope                  tenancy.Scope
}

// UpdateUserAccountStatusParams are the arguments to UpdateUserAccountStatus.
type UpdateUserAccountStatusParams struct {
	AccountStatus            string
	AccountStatusExplanation string
	ID                       string
	Scope                    tenancy.Scope
}

// UpdateUserPasswordParams are the arguments to UpdateUserPassword.
type UpdateUserPasswordParams struct {
	HashedPassword         string
	RequiresPasswordChange bool
	PasswordLastChangedAt  *time.Time
	ID                     string
	Scope                  tenancy.Scope
}

// UpdateUserTwoFactorSecretParams are the arguments to UpdateUserTwoFactorSecret.
type UpdateUserTwoFactorSecretParams struct {
	TwoFactorSecret           string
	TwoFactorSecretVerifiedAt *time.Time
	ID                        string
	Scope                     tenancy.Scope
}

// UpsertMembershipParams are the arguments to UpsertMembership.
type UpsertMembershipParams struct {
	ID               string
	Scope            tenancy.Scope
	BelongsToUser    string
	BelongsToAccount string
	DefaultAccount   bool
}
