// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package sessionsdb

import (
	"context"
	"strings"
	"time"
)

const createSessionSQLite = `
INSERT OR IGNORE INTO {{prefix}}sessions (
	id,
	data,
	created_at,
	last_seen_at,
	expires_at,
	version
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6
)`

const deleteSessionSQLite = `DELETE FROM {{prefix}}sessions
WHERE id = ?1`

const getSessionSQLite = `SELECT
	{{prefix}}sessions.data,
	{{prefix}}sessions.created_at,
	{{prefix}}sessions.last_seen_at,
	{{prefix}}sessions.version
FROM {{prefix}}sessions
WHERE {{prefix}}sessions.id = ?1`

const sessionExistsSQLite = `SELECT EXISTS (
	SELECT {{prefix}}sessions.id
	FROM {{prefix}}sessions
	WHERE {{prefix}}sessions.id = ?1
)`

const sweepSessionsSQLite = `DELETE FROM {{prefix}}sessions
WHERE expires_at <= ?1`

const updateSessionSQLite = `UPDATE {{prefix}}sessions SET
	data = ?1,
	last_seen_at = ?2,
	expires_at = ?3,
	version = ?4
WHERE id = ?5`

// sqliteQueries answers every query in Querier against sqlite.
type sqliteQueries struct {
	createSession string
	deleteSession string
	getSession    string
	sessionExists string
	sweepSessions string
	updateSession string
}

// newSQLite returns the sqlite querier with prefix substituted into every
// table name the analyzer identified.
func newSQLite(prefix string) *sqliteQueries {
	return &sqliteQueries{
		createSession: strings.ReplaceAll(createSessionSQLite, prefixMarker, prefix),
		deleteSession: strings.ReplaceAll(deleteSessionSQLite, prefixMarker, prefix),
		getSession:    strings.ReplaceAll(getSessionSQLite, prefixMarker, prefix),
		sessionExists: strings.ReplaceAll(sessionExistsSQLite, prefixMarker, prefix),
		sweepSessions: strings.ReplaceAll(sweepSessionsSQLite, prefixMarker, prefix),
		updateSession: strings.ReplaceAll(updateSessionSQLite, prefixMarker, prefix),
	}
}

// timeText renders a time argument as the text this engine stores timestamps as.
//
// This engine has no date type: a DATETIME column holds text, and a comparison
// between two of them compares two strings. What a driver writes for a bound
// time.Time is Go's own rendering of it, whose leading characters happen to be
// the stored shape — but only while the value is UTC. A time carrying any other
// zone puts its own wall clock in those leading characters, so every window
// comparison is off by that offset, silently, and only for the callers whose
// clock is not UTC.
//
// Converting here is what makes the bound text the stored shape by
// construction rather than by accident, whatever zone the caller's time
// carries. The layout is whole seconds, which is what CURRENT_TIMESTAMP writes,
// so a bound value and a stored one are one shape rather than two that sort
// alike — which does mean a sub-second time bound here is stored truncated to
// the second on this engine.
func timeText(t time.Time) string {
	return t.UTC().Format("2006-01-02 15:04:05")
}

// CreateSession runs the :execrows query against sqlite.
func (q *sqliteQueries) CreateSession(ctx context.Context, db DBTX, arg CreateSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.createSession,
		arg.ID,
		arg.Data,
		timeText(arg.CreatedAt),
		timeText(arg.LastSeenAt),
		timeText(arg.ExpiresAt),
		arg.Version,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// DeleteSession runs the :execrows query against sqlite.
func (q *sqliteQueries) DeleteSession(ctx context.Context, db DBTX, arg DeleteSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteSession,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// GetSession runs the :one query against sqlite.
func (q *sqliteQueries) GetSession(ctx context.Context, db DBTX, arg GetSessionParams) (GetSessionRow, error) {
	row := db.QueryRowContext(ctx, q.getSession,
		arg.ID,
	)

	var i GetSessionRow

	err := row.Scan(
		&i.Data,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.Version,
	)

	return i, err
}

// SessionExists runs the :one query against sqlite.
func (q *sqliteQueries) SessionExists(ctx context.Context, db DBTX, arg SessionExistsParams) (SessionExistsRow, error) {
	row := db.QueryRowContext(ctx, q.sessionExists,
		arg.ID,
	)

	var i SessionExistsRow

	err := row.Scan(
		&i.Exists,
	)

	return i, err
}

// SweepSessions runs the :execrows query against sqlite.
func (q *sqliteQueries) SweepSessions(ctx context.Context, db DBTX, arg SweepSessionsParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.sweepSessions,
		timeText(arg.Cutoff),
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpdateSession runs the :execrows query against sqlite.
func (q *sqliteQueries) UpdateSession(ctx context.Context, db DBTX, arg UpdateSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateSession,
		arg.Data,
		timeText(arg.LastSeenAt),
		timeText(arg.ExpiresAt),
		arg.Version,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		ID         string
		Data       []byte
		CreatedAt  time.Time
		LastSeenAt time.Time
		ExpiresAt  time.Time
		Version    int64
	}(CreateSessionParams{})
	_ = struct {
		ID string
	}(DeleteSessionParams{})
	_ = struct {
		ID string
	}(GetSessionParams{})
	_ = struct {
		Data       []byte
		CreatedAt  time.Time
		LastSeenAt time.Time
		Version    int64
	}(GetSessionRow{})
	_ = struct {
		ID string
	}(SessionExistsParams{})
	_ = struct {
		Exists bool
	}(SessionExistsRow{})
	_ = struct {
		Cutoff time.Time
	}(SweepSessionsParams{})
	_ = struct {
		Data       []byte
		LastSeenAt time.Time
		ExpiresAt  time.Time
		Version    int64
		ID         string
	}(UpdateSessionParams{})
)
