// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package sessionsdb

import (
	"context"
)

// Querier is every query in this package, with one signature per query
// regardless of which dialect answers it.
//
// That is the point of this package: the params type, the row type, and the
// method signature are the same on every dialect, so nothing above this line
// knows or cares which database is underneath.
//
// # A note on the :execrows count
//
// MySQL reports rows *changed*: an UPDATE that sets a column to the value it
// already held affects zero rows there. Postgres and SQLite report rows
// *matched*, and count that same UPDATE as one.
//
// So a statement that gates on the count — treating zero as "not found" — is
// correct on two engines and wrong on the third. Either give it a predicate
// that discriminates, or set clientFoundRows=true in the MySQL DSN, which
// switches MySQL to matched semantics.
type Querier interface {
	// CreateSession runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	CreateSession(ctx context.Context, db DBTX, arg CreateSessionParams) (int64, error)
	// DeleteSession runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	DeleteSession(ctx context.Context, db DBTX, arg DeleteSessionParams) (int64, error)
	// DeleteSessionForPrincipal runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	DeleteSessionForPrincipal(ctx context.Context, db DBTX, arg DeleteSessionForPrincipalParams) (int64, error)
	// DeleteSessionsForPrincipal runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	DeleteSessionsForPrincipal(ctx context.Context, db DBTX, arg DeleteSessionsForPrincipalParams) (int64, error)
	// GetSession runs the :one query.
	GetSession(ctx context.Context, db DBTX, arg GetSessionParams) (GetSessionRow, error)
	// ListSessionsForPrincipal runs the :many query.
	ListSessionsForPrincipal(ctx context.Context, db DBTX, arg ListSessionsForPrincipalParams) ([]ListSessionsForPrincipalRow, error)
	// SessionExists runs the :one query.
	SessionExists(ctx context.Context, db DBTX, arg SessionExistsParams) (SessionExistsRow, error)
	// SweepSessions runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	SweepSessions(ctx context.Context, db DBTX, arg SweepSessionsParams) (int64, error)
	// UpdateSession runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	UpdateSession(ctx context.Context, db DBTX, arg UpdateSessionParams) (int64, error)
}
