// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package sessionsdb

import (
	"context"
	"strings"
	"time"
)

const createSessionMySQL = `
INSERT IGNORE INTO {{prefix}}sessions (
	id,
	data,
	created_at,
	last_seen_at,
	expires_at,
	version
) VALUES (
	?,
	?,
	?,
	?,
	?,
	?
)`

const deleteSessionMySQL = `DELETE FROM {{prefix}}sessions
WHERE id = ?`

const getSessionMySQL = `SELECT
	{{prefix}}sessions.data,
	{{prefix}}sessions.created_at,
	{{prefix}}sessions.last_seen_at,
	{{prefix}}sessions.version
FROM {{prefix}}sessions
WHERE {{prefix}}sessions.id = ?`

const sessionExistsMySQL = `SELECT EXISTS (
	SELECT {{prefix}}sessions.id
	FROM {{prefix}}sessions
	WHERE {{prefix}}sessions.id = ?
)`

const sweepSessionsMySQL = `DELETE FROM {{prefix}}sessions
WHERE expires_at <= ?`

const updateSessionMySQL = `UPDATE {{prefix}}sessions SET
	data = ?,
	last_seen_at = ?,
	expires_at = ?,
	version = ?
WHERE id = ?`

// mysqlQueries answers every query in Querier against mysql.
type mysqlQueries struct {
	createSession string
	deleteSession string
	getSession    string
	sessionExists string
	sweepSessions string
	updateSession string
}

// newMySQL returns the mysql querier with prefix substituted into every
// table name the analyzer identified.
func newMySQL(prefix string) *mysqlQueries {
	return &mysqlQueries{
		createSession: strings.ReplaceAll(createSessionMySQL, prefixMarker, prefix),
		deleteSession: strings.ReplaceAll(deleteSessionMySQL, prefixMarker, prefix),
		getSession:    strings.ReplaceAll(getSessionMySQL, prefixMarker, prefix),
		sessionExists: strings.ReplaceAll(sessionExistsMySQL, prefixMarker, prefix),
		sweepSessions: strings.ReplaceAll(sweepSessionsMySQL, prefixMarker, prefix),
		updateSession: strings.ReplaceAll(updateSessionMySQL, prefixMarker, prefix),
	}
}

// CreateSession runs the :execrows query against mysql.
func (q *mysqlQueries) CreateSession(ctx context.Context, db DBTX, arg CreateSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.createSession,
		arg.ID,
		arg.Data,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// DeleteSession runs the :execrows query against mysql.
func (q *mysqlQueries) DeleteSession(ctx context.Context, db DBTX, arg DeleteSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteSession,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// GetSession runs the :one query against mysql.
func (q *mysqlQueries) GetSession(ctx context.Context, db DBTX, arg GetSessionParams) (GetSessionRow, error) {
	row := db.QueryRowContext(ctx, q.getSession,
		arg.ID,
	)

	var i GetSessionRow

	err := row.Scan(
		&i.Data,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.Version,
	)

	return i, err
}

// SessionExists runs the :one query against mysql.
func (q *mysqlQueries) SessionExists(ctx context.Context, db DBTX, arg SessionExistsParams) (SessionExistsRow, error) {
	row := db.QueryRowContext(ctx, q.sessionExists,
		arg.ID,
	)

	var i SessionExistsRow

	err := row.Scan(
		&i.Exists,
	)

	return i, err
}

// SweepSessions runs the :execrows query against mysql.
func (q *mysqlQueries) SweepSessions(ctx context.Context, db DBTX, arg SweepSessionsParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.sweepSessions,
		arg.Cutoff,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpdateSession runs the :execrows query against mysql.
func (q *mysqlQueries) UpdateSession(ctx context.Context, db DBTX, arg UpdateSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateSession,
		arg.Data,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.Version,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		ID         string
		Data       []byte
		CreatedAt  time.Time
		LastSeenAt time.Time
		ExpiresAt  time.Time
		Version    int64
	}(CreateSessionParams{})
	_ = struct {
		ID string
	}(DeleteSessionParams{})
	_ = struct {
		ID string
	}(GetSessionParams{})
	_ = struct {
		Data       []byte
		CreatedAt  time.Time
		LastSeenAt time.Time
		Version    int64
	}(GetSessionRow{})
	_ = struct {
		ID string
	}(SessionExistsParams{})
	_ = struct {
		Exists bool
	}(SessionExistsRow{})
	_ = struct {
		Cutoff time.Time
	}(SweepSessionsParams{})
	_ = struct {
		Data       []byte
		LastSeenAt time.Time
		ExpiresAt  time.Time
		Version    int64
		ID         string
	}(UpdateSessionParams{})
)
