// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package sessionsdb

import (
	"context"
	"strings"
	"time"
)

const createSessionPostgreSQL = `
INSERT INTO {{prefix}}sessions (
	id,
	data,
	created_at,
	last_seen_at,
	expires_at,
	version
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6
)
ON CONFLICT (id) DO NOTHING`

const deleteSessionPostgreSQL = `DELETE FROM {{prefix}}sessions
WHERE id = $1`

const getSessionPostgreSQL = `SELECT
	{{prefix}}sessions.data,
	{{prefix}}sessions.created_at,
	{{prefix}}sessions.last_seen_at,
	{{prefix}}sessions.version
FROM {{prefix}}sessions
WHERE {{prefix}}sessions.id = $1`

const sessionExistsPostgreSQL = `SELECT EXISTS (
	SELECT {{prefix}}sessions.id
	FROM {{prefix}}sessions
	WHERE {{prefix}}sessions.id = $1
)`

const sweepSessionsPostgreSQL = `DELETE FROM {{prefix}}sessions
WHERE expires_at <= $1`

const updateSessionPostgreSQL = `UPDATE {{prefix}}sessions SET
	data = $1,
	last_seen_at = $2,
	expires_at = $3,
	version = $4
WHERE id = $5`

// postgresqlQueries answers every query in Querier against postgresql.
type postgresqlQueries struct {
	createSession string
	deleteSession string
	getSession    string
	sessionExists string
	sweepSessions string
	updateSession string
}

// newPostgreSQL returns the postgresql querier with prefix substituted into every
// table name the analyzer identified.
func newPostgreSQL(prefix string) *postgresqlQueries {
	return &postgresqlQueries{
		createSession: strings.ReplaceAll(createSessionPostgreSQL, prefixMarker, prefix),
		deleteSession: strings.ReplaceAll(deleteSessionPostgreSQL, prefixMarker, prefix),
		getSession:    strings.ReplaceAll(getSessionPostgreSQL, prefixMarker, prefix),
		sessionExists: strings.ReplaceAll(sessionExistsPostgreSQL, prefixMarker, prefix),
		sweepSessions: strings.ReplaceAll(sweepSessionsPostgreSQL, prefixMarker, prefix),
		updateSession: strings.ReplaceAll(updateSessionPostgreSQL, prefixMarker, prefix),
	}
}

// CreateSession runs the :execrows query against postgresql.
func (q *postgresqlQueries) CreateSession(ctx context.Context, db DBTX, arg CreateSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.createSession,
		arg.ID,
		arg.Data,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// DeleteSession runs the :execrows query against postgresql.
func (q *postgresqlQueries) DeleteSession(ctx context.Context, db DBTX, arg DeleteSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteSession,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// GetSession runs the :one query against postgresql.
func (q *postgresqlQueries) GetSession(ctx context.Context, db DBTX, arg GetSessionParams) (GetSessionRow, error) {
	row := db.QueryRowContext(ctx, q.getSession,
		arg.ID,
	)

	var i GetSessionRow

	err := row.Scan(
		&i.Data,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.Version,
	)

	return i, err
}

// SessionExists runs the :one query against postgresql.
func (q *postgresqlQueries) SessionExists(ctx context.Context, db DBTX, arg SessionExistsParams) (SessionExistsRow, error) {
	row := db.QueryRowContext(ctx, q.sessionExists,
		arg.ID,
	)

	var i SessionExistsRow

	err := row.Scan(
		&i.Exists,
	)

	return i, err
}

// SweepSessions runs the :execrows query against postgresql.
func (q *postgresqlQueries) SweepSessions(ctx context.Context, db DBTX, arg SweepSessionsParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.sweepSessions,
		arg.Cutoff,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpdateSession runs the :execrows query against postgresql.
func (q *postgresqlQueries) UpdateSession(ctx context.Context, db DBTX, arg UpdateSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateSession,
		arg.Data,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.Version,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		ID         string
		Data       []byte
		CreatedAt  time.Time
		LastSeenAt time.Time
		ExpiresAt  time.Time
		Version    int64
	}(CreateSessionParams{})
	_ = struct {
		ID string
	}(DeleteSessionParams{})
	_ = struct {
		ID string
	}(GetSessionParams{})
	_ = struct {
		Data       []byte
		CreatedAt  time.Time
		LastSeenAt time.Time
		Version    int64
	}(GetSessionRow{})
	_ = struct {
		ID string
	}(SessionExistsParams{})
	_ = struct {
		Exists bool
	}(SessionExistsRow{})
	_ = struct {
		Cutoff time.Time
	}(SweepSessionsParams{})
	_ = struct {
		Data       []byte
		LastSeenAt time.Time
		ExpiresAt  time.Time
		Version    int64
		ID         string
	}(UpdateSessionParams{})
)
