// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package sessionsdb

import (
	"time"
)

// CreateSessionParams are the arguments to CreateSession.
type CreateSessionParams struct {
	ID         string
	Data       []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	Version    int64
}

// DeleteSessionParams are the arguments to DeleteSession.
type DeleteSessionParams struct {
	ID string
}

// GetSessionParams are the arguments to GetSession.
type GetSessionParams struct {
	ID string
}

// GetSessionRow is one row of GetSession's result.
type GetSessionRow struct {
	Data       []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
	Version    int64
}

// SessionExistsParams are the arguments to SessionExists.
type SessionExistsParams struct {
	ID string
}

// SessionExistsRow is one row of SessionExists's result.
type SessionExistsRow struct {
	Exists bool
}

// SweepSessionsParams are the arguments to SweepSessions.
type SweepSessionsParams struct {
	Cutoff time.Time
}

// UpdateSessionParams are the arguments to UpdateSession.
type UpdateSessionParams struct {
	Data       []byte
	LastSeenAt time.Time
	ExpiresAt  time.Time
	Version    int64
	ID         string
}
