-- Code generated by github.com/primandproper/platform-go/v13/sessions/database/internal/queriesgen. DO NOT EDIT.

-- name: CreateSession :execrows
INSERT IGNORE INTO sessions (
	id,
	data,
	created_at,
	last_seen_at,
	expires_at,
	version
) VALUES (
	sqlc.arg(id),
	sqlc.narg(data),
	sqlc.arg(created_at),
	sqlc.arg(last_seen_at),
	sqlc.arg(expires_at),
	sqlc.arg(version)
);

-- name: GetSession :one
SELECT
	sessions.data,
	sessions.created_at,
	sessions.last_seen_at,
	sessions.version
FROM sessions
WHERE sessions.id = sqlc.arg(id);

-- name: UpdateSession :execrows
UPDATE sessions SET
	data = sqlc.narg(data),
	last_seen_at = sqlc.arg(last_seen_at),
	expires_at = sqlc.arg(expires_at),
	version = sqlc.arg(version)
WHERE id = sqlc.arg(id);

-- name: SessionExists :one
SELECT EXISTS (
	SELECT sessions.id
	FROM sessions
	WHERE sessions.id = sqlc.arg(id)
);

-- name: DeleteSession :execrows
DELETE FROM sessions
WHERE id = sqlc.arg(id);

-- name: SweepSessions :execrows
DELETE FROM sessions
WHERE expires_at <= sqlc.arg(cutoff);
