// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package auditdb

import (
	"context"
)

// Querier is every query in this package, with one signature per query
// regardless of which dialect answers it.
//
// That is the point of this package: the params type, the row type, and the
// method signature are the same on every dialect, so nothing above this line
// knows or cares which database is underneath.
//
// # A note on the :execrows count
//
// MySQL reports rows *changed*: an UPDATE that sets a column to the value it
// already held affects zero rows there. Postgres and SQLite report rows
// *matched*, and count that same UPDATE as one.
//
// So a statement that gates on the count — treating zero as "not found" — is
// correct on two engines and wrong on the third. Either give it a predicate
// that discriminates, or set clientFoundRows=true in the MySQL DSN, which
// switches MySQL to matched semantics.
//
// # A note on empty lists
//
// A list parameter that is empty matches nothing, on every dialect: Postgres
// binds an empty array to `= ANY`, and the other two expand to `IN (NULL)` because
// `IN ()` is a syntax error there. Asking for the rows whose key is in an empty
// set gets no rows back, which is what the empty set says, so a caller does not
// have to guard the call.
//
// The negation is where they part company, and nothing below can warn you. An
// empty list makes `NOT IN (NULL)` never true, so it matches nothing, while
// Postgres's empty `<> ALL` is true and matches everything. Both readings are
// defensible and no shared signature can say which was meant — so test
// membership rather than its negation, and let the caller decide what an empty
// set means before it calls.
type Querier interface {
	// AdvanceAuditChainHead runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	AdvanceAuditChainHead(ctx context.Context, db DBTX, arg AdvanceAuditChainHeadParams) (int64, error)
	// CountAuditLogEntriesForSubject runs the :one query.
	CountAuditLogEntriesForSubject(ctx context.Context, db DBTX, arg CountAuditLogEntriesForSubjectParams) (CountAuditLogEntriesForSubjectRow, error)
	// CountPrunableAuditEntries runs the :one query.
	CountPrunableAuditEntries(ctx context.Context, db DBTX, arg CountPrunableAuditEntriesParams) (CountPrunableAuditEntriesRow, error)
	// CreateAuditChain runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	CreateAuditChain(ctx context.Context, db DBTX, arg CreateAuditChainParams) (int64, error)
	// DeleteAuditChainsInScopes runs the :exec query.
	DeleteAuditChainsInScopes(ctx context.Context, db DBTX, arg DeleteAuditChainsInScopesParams) error
	// DeleteAuditLogEntriesInScopes runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	DeleteAuditLogEntriesInScopes(ctx context.Context, db DBTX, arg DeleteAuditLogEntriesInScopesParams) (int64, error)
	// GetAuditChain runs the :one query.
	GetAuditChain(ctx context.Context, db DBTX, arg GetAuditChainParams) (GetAuditChainRow, error)
	// GetAuditLogEntry runs the :one query.
	GetAuditLogEntry(ctx context.Context, db DBTX, arg GetAuditLogEntryParams) (GetAuditLogEntryRow, error)
	// GetAuditLogEntryBySeq runs the :one query.
	GetAuditLogEntryBySeq(ctx context.Context, db DBTX, arg GetAuditLogEntryBySeqParams) (GetAuditLogEntryBySeqRow, error)
	// GetAuditPruneBounds runs the :one query.
	GetAuditPruneBounds(ctx context.Context, db DBTX, arg GetAuditPruneBoundsParams) (GetAuditPruneBoundsRow, error)
	// GetAuditPruneTarget runs the :one query.
	GetAuditPruneTarget(ctx context.Context, db DBTX, arg GetAuditPruneTargetParams) (GetAuditPruneTargetRow, error)
	// InsertAuditLogEntry runs the :exec query.
	InsertAuditLogEntry(ctx context.Context, db DBTX, arg InsertAuditLogEntryParams) error
	// ListAuditChainEntries runs the :many query.
	ListAuditChainEntries(ctx context.Context, db DBTX, arg ListAuditChainEntriesParams) ([]ListAuditChainEntriesRow, error)
	// ListAuditLogEntries runs the :many query.
	ListAuditLogEntries(ctx context.Context, db DBTX, arg ListAuditLogEntriesParams) ([]ListAuditLogEntriesRow, error)
	// ListAuditLogEntriesDescending runs the :many query.
	ListAuditLogEntriesDescending(ctx context.Context, db DBTX, arg ListAuditLogEntriesDescendingParams) ([]ListAuditLogEntriesDescendingRow, error)
	// ListPrunableAuditScopes runs the :many query.
	ListPrunableAuditScopes(ctx context.Context, db DBTX, arg ListPrunableAuditScopesParams) ([]ListPrunableAuditScopesRow, error)
	// ListPrunableAuditScopesAfter runs the :many query.
	ListPrunableAuditScopesAfter(ctx context.Context, db DBTX, arg ListPrunableAuditScopesAfterParams) ([]ListPrunableAuditScopesAfterRow, error)
	// LockAuditChain runs the :one query.
	LockAuditChain(ctx context.Context, db DBTX, arg LockAuditChainParams) (LockAuditChainRow, error)
	// PruneAuditLogEntries runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	PruneAuditLogEntries(ctx context.Context, db DBTX, arg PruneAuditLogEntriesParams) (int64, error)
	// RecordAuditChainPrune runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	RecordAuditChainPrune(ctx context.Context, db DBTX, arg RecordAuditChainPruneParams) (int64, error)
}
