/*
Command queriesgen writes the canonical sqlc input for the identity schema, one
file per dialect, from identity/internal/queries.

It is run by `make generate`, and the files it writes are checked in. Nothing
imports them and nothing executes them: they exist so that `sqlc compile` can
check the statements the identity store executes against the schema
identity/migrations renders, at build time, with no database running. The store
itself renders the same statements through database/querygen's Bound methods,
which is the same text with the consumer's table prefix on the name and the
argument references rewritten into bind markers.

Because the check is what the files are for, this command also renders the other
half of it: `-schema <dialect>` prints the DDL sqlc reads them against, so
.scripts/sqlc_compile.sh has no hand-written copy of a schema to keep in step
with identity/migrations.

	go run ./internal/queriesgen                 # writes internal/queries/<dialect>.sql
	go run ./internal/queriesgen -schema sqlite  # prints the DDL to stdout
*/
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/primandproper/platform-go/v13/database/dialect"
	"github.com/primandproper/platform-go/v13/identity/internal/queries"
	"github.com/primandproper/platform-go/v13/identity/migrations"
)

// header marks the output as generated in the form `go generate` consumers,
// linters, and review tools all recognize. SQL's line comment is the same on
// all three dialects, and sqlc reads its own annotations out of comments, so
// this has to be a comment sqlc will ignore rather than one it might parse.
const header = "-- Code generated by github.com/primandproper/platform-go/v13/identity/internal/queriesgen. DO NOT EDIT.\n\n"

func main() {
	schema := flag.String("schema", "", "print the identity DDL for this dialect instead of writing the queries")
	out := flag.String("out", filepath.Join("internal", "queries"), "directory the generated .sql files are written to")

	flag.Parse()

	if err := run(*schema, *out); err != nil {
		fmt.Fprintln(os.Stderr, "queriesgen:", err)
		os.Exit(1)
	}
}

// run does one of the two jobs, so that neither has to call os.Exit itself.
func run(schema, out string) error {
	if schema != "" {
		return printSchema(dialect.Dialect(schema))
	}

	for _, d := range []dialect.Dialect{dialect.Postgres, dialect.MySQL, dialect.SQLite} {
		path := filepath.Join(out, string(d)+".sql")
		if err := os.WriteFile(path, []byte(header+queries.Render(d)), 0o600); err != nil {
			return fmt.Errorf("writing %q: %w", path, err)
		}
	}

	return nil
}

// printSchema writes the DDL for one dialect to stdout, at the empty prefix —
// which is the name the canonical queries use, and the only prefix sqlc could
// resolve, since an identifier is not a bind parameter in any of the three
// engines.
func printSchema(d dialect.Dialect) error {
	if !d.Valid() {
		return fmt.Errorf("unsupported dialect %q", d)
	}

	ddl, err := migrations.SQL(d, "")
	if err != nil {
		return fmt.Errorf("rendering the %s schema: %w", d, err)
	}

	_, err = fmt.Fprintln(os.Stdout, ddl)

	return err
}
