// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package commentsmock

import (
	"context"
	"sync"

	"github.com/primandproper/platform-go/v14/comments"
	"github.com/primandproper/platform-go/v14/database"
	"github.com/primandproper/platform-go/v14/filtering"
	"github.com/primandproper/platform-go/v14/tenancy"
)

// Ensure, that StoreMock does implement comments.Store.
// If this is not the case, regenerate this file with moq.
var _ comments.Store = &StoreMock{}

// StoreMock is a mock implementation of comments.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked comments.Store
//		mockedStore := &StoreMock{
//			ArchiveCommentFunc: func(ctx context.Context, scope tenancy.Scope, commentID string) error {
//				panic("mock out the ArchiveComment method")
//			},
//			ArchiveCommentTxFunc: func(ctx context.Context, q database.Tx, scope tenancy.Scope, commentID string) error {
//				panic("mock out the ArchiveCommentTx method")
//			},
//			CreateCommentFunc: func(ctx context.Context, comment *comments.Comment) error {
//				panic("mock out the CreateComment method")
//			},
//			CreateCommentTxFunc: func(ctx context.Context, q database.Tx, comment *comments.Comment) error {
//				panic("mock out the CreateCommentTx method")
//			},
//			DeleteCommentsByAuthorFunc: func(ctx context.Context, q database.Tx, scope tenancy.Scope, author string) (int64, error) {
//				panic("mock out the DeleteCommentsByAuthor method")
//			},
//			DeleteCommentsForTargetFunc: func(ctx context.Context, q database.Tx, scope tenancy.Scope, target comments.Target) (int64, error) {
//				panic("mock out the DeleteCommentsForTarget method")
//			},
//			GetCommentFunc: func(ctx context.Context, scope tenancy.Scope, commentID string) (*comments.Comment, error) {
//				panic("mock out the GetComment method")
//			},
//			ListCommentsByAuthorFunc: func(ctx context.Context, scope tenancy.Scope, author string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error) {
//				panic("mock out the ListCommentsByAuthor method")
//			},
//			ListCommentsByTargetTypeFunc: func(ctx context.Context, scope tenancy.Scope, targetType comments.TargetType, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error) {
//				panic("mock out the ListCommentsByTargetType method")
//			},
//			ListRepliesFunc: func(ctx context.Context, scope tenancy.Scope, target comments.Target, parentID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error) {
//				panic("mock out the ListReplies method")
//			},
//			ListRootCommentsFunc: func(ctx context.Context, scope tenancy.Scope, target comments.Target, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error) {
//				panic("mock out the ListRootComments method")
//			},
//			UpdateCommentFunc: func(ctx context.Context, comment *comments.Comment) error {
//				panic("mock out the UpdateComment method")
//			},
//			UpdateCommentTxFunc: func(ctx context.Context, q database.Tx, comment *comments.Comment) error {
//				panic("mock out the UpdateCommentTx method")
//			},
//		}
//
//		// use mockedStore in code that requires comments.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// ArchiveCommentFunc mocks the ArchiveComment method.
	ArchiveCommentFunc func(ctx context.Context, scope tenancy.Scope, commentID string) error

	// ArchiveCommentTxFunc mocks the ArchiveCommentTx method.
	ArchiveCommentTxFunc func(ctx context.Context, q database.Tx, scope tenancy.Scope, commentID string) error

	// CreateCommentFunc mocks the CreateComment method.
	CreateCommentFunc func(ctx context.Context, comment *comments.Comment) error

	// CreateCommentTxFunc mocks the CreateCommentTx method.
	CreateCommentTxFunc func(ctx context.Context, q database.Tx, comment *comments.Comment) error

	// DeleteCommentsByAuthorFunc mocks the DeleteCommentsByAuthor method.
	DeleteCommentsByAuthorFunc func(ctx context.Context, q database.Tx, scope tenancy.Scope, author string) (int64, error)

	// DeleteCommentsForTargetFunc mocks the DeleteCommentsForTarget method.
	DeleteCommentsForTargetFunc func(ctx context.Context, q database.Tx, scope tenancy.Scope, target comments.Target) (int64, error)

	// GetCommentFunc mocks the GetComment method.
	GetCommentFunc func(ctx context.Context, scope tenancy.Scope, commentID string) (*comments.Comment, error)

	// ListCommentsByAuthorFunc mocks the ListCommentsByAuthor method.
	ListCommentsByAuthorFunc func(ctx context.Context, scope tenancy.Scope, author string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error)

	// ListCommentsByTargetTypeFunc mocks the ListCommentsByTargetType method.
	ListCommentsByTargetTypeFunc func(ctx context.Context, scope tenancy.Scope, targetType comments.TargetType, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error)

	// ListRepliesFunc mocks the ListReplies method.
	ListRepliesFunc func(ctx context.Context, scope tenancy.Scope, target comments.Target, parentID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error)

	// ListRootCommentsFunc mocks the ListRootComments method.
	ListRootCommentsFunc func(ctx context.Context, scope tenancy.Scope, target comments.Target, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error)

	// UpdateCommentFunc mocks the UpdateComment method.
	UpdateCommentFunc func(ctx context.Context, comment *comments.Comment) error

	// UpdateCommentTxFunc mocks the UpdateCommentTx method.
	UpdateCommentTxFunc func(ctx context.Context, q database.Tx, comment *comments.Comment) error

	// calls tracks calls to the methods.
	calls struct {
		// ArchiveComment holds details about calls to the ArchiveComment method.
		ArchiveComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// CommentID is the commentID argument value.
			CommentID string
		}
		// ArchiveCommentTx holds details about calls to the ArchiveCommentTx method.
		ArchiveCommentTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// CommentID is the commentID argument value.
			CommentID string
		}
		// CreateComment holds details about calls to the CreateComment method.
		CreateComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Comment is the comment argument value.
			Comment *comments.Comment
		}
		// CreateCommentTx holds details about calls to the CreateCommentTx method.
		CreateCommentTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.Tx
			// Comment is the comment argument value.
			Comment *comments.Comment
		}
		// DeleteCommentsByAuthor holds details about calls to the DeleteCommentsByAuthor method.
		DeleteCommentsByAuthor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Author is the author argument value.
			Author string
		}
		// DeleteCommentsForTarget holds details about calls to the DeleteCommentsForTarget method.
		DeleteCommentsForTarget []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Target is the target argument value.
			Target comments.Target
		}
		// GetComment holds details about calls to the GetComment method.
		GetComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// CommentID is the commentID argument value.
			CommentID string
		}
		// ListCommentsByAuthor holds details about calls to the ListCommentsByAuthor method.
		ListCommentsByAuthor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Author is the author argument value.
			Author string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// ListCommentsByTargetType holds details about calls to the ListCommentsByTargetType method.
		ListCommentsByTargetType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// TargetType is the targetType argument value.
			TargetType comments.TargetType
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// ListReplies holds details about calls to the ListReplies method.
		ListReplies []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Target is the target argument value.
			Target comments.Target
			// ParentID is the parentID argument value.
			ParentID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// ListRootComments holds details about calls to the ListRootComments method.
		ListRootComments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Target is the target argument value.
			Target comments.Target
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// UpdateComment holds details about calls to the UpdateComment method.
		UpdateComment []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Comment is the comment argument value.
			Comment *comments.Comment
		}
		// UpdateCommentTx holds details about calls to the UpdateCommentTx method.
		UpdateCommentTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.Tx
			// Comment is the comment argument value.
			Comment *comments.Comment
		}
	}
	lockArchiveComment           sync.RWMutex
	lockArchiveCommentTx         sync.RWMutex
	lockCreateComment            sync.RWMutex
	lockCreateCommentTx          sync.RWMutex
	lockDeleteCommentsByAuthor   sync.RWMutex
	lockDeleteCommentsForTarget  sync.RWMutex
	lockGetComment               sync.RWMutex
	lockListCommentsByAuthor     sync.RWMutex
	lockListCommentsByTargetType sync.RWMutex
	lockListReplies              sync.RWMutex
	lockListRootComments         sync.RWMutex
	lockUpdateComment            sync.RWMutex
	lockUpdateCommentTx          sync.RWMutex
}

// ArchiveComment calls ArchiveCommentFunc.
func (mock *StoreMock) ArchiveComment(ctx context.Context, scope tenancy.Scope, commentID string) error {
	if mock.ArchiveCommentFunc == nil {
		panic("StoreMock.ArchiveCommentFunc: method is nil but Store.ArchiveComment was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Scope     tenancy.Scope
		CommentID string
	}{
		Ctx:       ctx,
		Scope:     scope,
		CommentID: commentID,
	}
	mock.lockArchiveComment.Lock()
	mock.calls.ArchiveComment = append(mock.calls.ArchiveComment, callInfo)
	mock.lockArchiveComment.Unlock()
	return mock.ArchiveCommentFunc(ctx, scope, commentID)
}

// ArchiveCommentCalls gets all the calls that were made to ArchiveComment.
// Check the length with:
//
//	len(mockedStore.ArchiveCommentCalls())
func (mock *StoreMock) ArchiveCommentCalls() []struct {
	Ctx       context.Context
	Scope     tenancy.Scope
	CommentID string
} {
	var calls []struct {
		Ctx       context.Context
		Scope     tenancy.Scope
		CommentID string
	}
	mock.lockArchiveComment.RLock()
	calls = mock.calls.ArchiveComment
	mock.lockArchiveComment.RUnlock()
	return calls
}

// ArchiveCommentTx calls ArchiveCommentTxFunc.
func (mock *StoreMock) ArchiveCommentTx(ctx context.Context, q database.Tx, scope tenancy.Scope, commentID string) error {
	if mock.ArchiveCommentTxFunc == nil {
		panic("StoreMock.ArchiveCommentTxFunc: method is nil but Store.ArchiveCommentTx was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Q         database.Tx
		Scope     tenancy.Scope
		CommentID string
	}{
		Ctx:       ctx,
		Q:         q,
		Scope:     scope,
		CommentID: commentID,
	}
	mock.lockArchiveCommentTx.Lock()
	mock.calls.ArchiveCommentTx = append(mock.calls.ArchiveCommentTx, callInfo)
	mock.lockArchiveCommentTx.Unlock()
	return mock.ArchiveCommentTxFunc(ctx, q, scope, commentID)
}

// ArchiveCommentTxCalls gets all the calls that were made to ArchiveCommentTx.
// Check the length with:
//
//	len(mockedStore.ArchiveCommentTxCalls())
func (mock *StoreMock) ArchiveCommentTxCalls() []struct {
	Ctx       context.Context
	Q         database.Tx
	Scope     tenancy.Scope
	CommentID string
} {
	var calls []struct {
		Ctx       context.Context
		Q         database.Tx
		Scope     tenancy.Scope
		CommentID string
	}
	mock.lockArchiveCommentTx.RLock()
	calls = mock.calls.ArchiveCommentTx
	mock.lockArchiveCommentTx.RUnlock()
	return calls
}

// CreateComment calls CreateCommentFunc.
func (mock *StoreMock) CreateComment(ctx context.Context, comment *comments.Comment) error {
	if mock.CreateCommentFunc == nil {
		panic("StoreMock.CreateCommentFunc: method is nil but Store.CreateComment was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Comment *comments.Comment
	}{
		Ctx:     ctx,
		Comment: comment,
	}
	mock.lockCreateComment.Lock()
	mock.calls.CreateComment = append(mock.calls.CreateComment, callInfo)
	mock.lockCreateComment.Unlock()
	return mock.CreateCommentFunc(ctx, comment)
}

// CreateCommentCalls gets all the calls that were made to CreateComment.
// Check the length with:
//
//	len(mockedStore.CreateCommentCalls())
func (mock *StoreMock) CreateCommentCalls() []struct {
	Ctx     context.Context
	Comment *comments.Comment
} {
	var calls []struct {
		Ctx     context.Context
		Comment *comments.Comment
	}
	mock.lockCreateComment.RLock()
	calls = mock.calls.CreateComment
	mock.lockCreateComment.RUnlock()
	return calls
}

// CreateCommentTx calls CreateCommentTxFunc.
func (mock *StoreMock) CreateCommentTx(ctx context.Context, q database.Tx, comment *comments.Comment) error {
	if mock.CreateCommentTxFunc == nil {
		panic("StoreMock.CreateCommentTxFunc: method is nil but Store.CreateCommentTx was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Q       database.Tx
		Comment *comments.Comment
	}{
		Ctx:     ctx,
		Q:       q,
		Comment: comment,
	}
	mock.lockCreateCommentTx.Lock()
	mock.calls.CreateCommentTx = append(mock.calls.CreateCommentTx, callInfo)
	mock.lockCreateCommentTx.Unlock()
	return mock.CreateCommentTxFunc(ctx, q, comment)
}

// CreateCommentTxCalls gets all the calls that were made to CreateCommentTx.
// Check the length with:
//
//	len(mockedStore.CreateCommentTxCalls())
func (mock *StoreMock) CreateCommentTxCalls() []struct {
	Ctx     context.Context
	Q       database.Tx
	Comment *comments.Comment
} {
	var calls []struct {
		Ctx     context.Context
		Q       database.Tx
		Comment *comments.Comment
	}
	mock.lockCreateCommentTx.RLock()
	calls = mock.calls.CreateCommentTx
	mock.lockCreateCommentTx.RUnlock()
	return calls
}

// DeleteCommentsByAuthor calls DeleteCommentsByAuthorFunc.
func (mock *StoreMock) DeleteCommentsByAuthor(ctx context.Context, q database.Tx, scope tenancy.Scope, author string) (int64, error) {
	if mock.DeleteCommentsByAuthorFunc == nil {
		panic("StoreMock.DeleteCommentsByAuthorFunc: method is nil but Store.DeleteCommentsByAuthor was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Q      database.Tx
		Scope  tenancy.Scope
		Author string
	}{
		Ctx:    ctx,
		Q:      q,
		Scope:  scope,
		Author: author,
	}
	mock.lockDeleteCommentsByAuthor.Lock()
	mock.calls.DeleteCommentsByAuthor = append(mock.calls.DeleteCommentsByAuthor, callInfo)
	mock.lockDeleteCommentsByAuthor.Unlock()
	return mock.DeleteCommentsByAuthorFunc(ctx, q, scope, author)
}

// DeleteCommentsByAuthorCalls gets all the calls that were made to DeleteCommentsByAuthor.
// Check the length with:
//
//	len(mockedStore.DeleteCommentsByAuthorCalls())
func (mock *StoreMock) DeleteCommentsByAuthorCalls() []struct {
	Ctx    context.Context
	Q      database.Tx
	Scope  tenancy.Scope
	Author string
} {
	var calls []struct {
		Ctx    context.Context
		Q      database.Tx
		Scope  tenancy.Scope
		Author string
	}
	mock.lockDeleteCommentsByAuthor.RLock()
	calls = mock.calls.DeleteCommentsByAuthor
	mock.lockDeleteCommentsByAuthor.RUnlock()
	return calls
}

// DeleteCommentsForTarget calls DeleteCommentsForTargetFunc.
func (mock *StoreMock) DeleteCommentsForTarget(ctx context.Context, q database.Tx, scope tenancy.Scope, target comments.Target) (int64, error) {
	if mock.DeleteCommentsForTargetFunc == nil {
		panic("StoreMock.DeleteCommentsForTargetFunc: method is nil but Store.DeleteCommentsForTarget was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Q      database.Tx
		Scope  tenancy.Scope
		Target comments.Target
	}{
		Ctx:    ctx,
		Q:      q,
		Scope:  scope,
		Target: target,
	}
	mock.lockDeleteCommentsForTarget.Lock()
	mock.calls.DeleteCommentsForTarget = append(mock.calls.DeleteCommentsForTarget, callInfo)
	mock.lockDeleteCommentsForTarget.Unlock()
	return mock.DeleteCommentsForTargetFunc(ctx, q, scope, target)
}

// DeleteCommentsForTargetCalls gets all the calls that were made to DeleteCommentsForTarget.
// Check the length with:
//
//	len(mockedStore.DeleteCommentsForTargetCalls())
func (mock *StoreMock) DeleteCommentsForTargetCalls() []struct {
	Ctx    context.Context
	Q      database.Tx
	Scope  tenancy.Scope
	Target comments.Target
} {
	var calls []struct {
		Ctx    context.Context
		Q      database.Tx
		Scope  tenancy.Scope
		Target comments.Target
	}
	mock.lockDeleteCommentsForTarget.RLock()
	calls = mock.calls.DeleteCommentsForTarget
	mock.lockDeleteCommentsForTarget.RUnlock()
	return calls
}

// GetComment calls GetCommentFunc.
func (mock *StoreMock) GetComment(ctx context.Context, scope tenancy.Scope, commentID string) (*comments.Comment, error) {
	if mock.GetCommentFunc == nil {
		panic("StoreMock.GetCommentFunc: method is nil but Store.GetComment was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Scope     tenancy.Scope
		CommentID string
	}{
		Ctx:       ctx,
		Scope:     scope,
		CommentID: commentID,
	}
	mock.lockGetComment.Lock()
	mock.calls.GetComment = append(mock.calls.GetComment, callInfo)
	mock.lockGetComment.Unlock()
	return mock.GetCommentFunc(ctx, scope, commentID)
}

// GetCommentCalls gets all the calls that were made to GetComment.
// Check the length with:
//
//	len(mockedStore.GetCommentCalls())
func (mock *StoreMock) GetCommentCalls() []struct {
	Ctx       context.Context
	Scope     tenancy.Scope
	CommentID string
} {
	var calls []struct {
		Ctx       context.Context
		Scope     tenancy.Scope
		CommentID string
	}
	mock.lockGetComment.RLock()
	calls = mock.calls.GetComment
	mock.lockGetComment.RUnlock()
	return calls
}

// ListCommentsByAuthor calls ListCommentsByAuthorFunc.
func (mock *StoreMock) ListCommentsByAuthor(ctx context.Context, scope tenancy.Scope, author string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error) {
	if mock.ListCommentsByAuthorFunc == nil {
		panic("StoreMock.ListCommentsByAuthorFunc: method is nil but Store.ListCommentsByAuthor was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Scope  tenancy.Scope
		Author string
		Filter *filtering.QueryFilter
	}{
		Ctx:    ctx,
		Scope:  scope,
		Author: author,
		Filter: filter,
	}
	mock.lockListCommentsByAuthor.Lock()
	mock.calls.ListCommentsByAuthor = append(mock.calls.ListCommentsByAuthor, callInfo)
	mock.lockListCommentsByAuthor.Unlock()
	return mock.ListCommentsByAuthorFunc(ctx, scope, author, filter)
}

// ListCommentsByAuthorCalls gets all the calls that were made to ListCommentsByAuthor.
// Check the length with:
//
//	len(mockedStore.ListCommentsByAuthorCalls())
func (mock *StoreMock) ListCommentsByAuthorCalls() []struct {
	Ctx    context.Context
	Scope  tenancy.Scope
	Author string
	Filter *filtering.QueryFilter
} {
	var calls []struct {
		Ctx    context.Context
		Scope  tenancy.Scope
		Author string
		Filter *filtering.QueryFilter
	}
	mock.lockListCommentsByAuthor.RLock()
	calls = mock.calls.ListCommentsByAuthor
	mock.lockListCommentsByAuthor.RUnlock()
	return calls
}

// ListCommentsByTargetType calls ListCommentsByTargetTypeFunc.
func (mock *StoreMock) ListCommentsByTargetType(ctx context.Context, scope tenancy.Scope, targetType comments.TargetType, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error) {
	if mock.ListCommentsByTargetTypeFunc == nil {
		panic("StoreMock.ListCommentsByTargetTypeFunc: method is nil but Store.ListCommentsByTargetType was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Scope      tenancy.Scope
		TargetType comments.TargetType
		Filter     *filtering.QueryFilter
	}{
		Ctx:        ctx,
		Scope:      scope,
		TargetType: targetType,
		Filter:     filter,
	}
	mock.lockListCommentsByTargetType.Lock()
	mock.calls.ListCommentsByTargetType = append(mock.calls.ListCommentsByTargetType, callInfo)
	mock.lockListCommentsByTargetType.Unlock()
	return mock.ListCommentsByTargetTypeFunc(ctx, scope, targetType, filter)
}

// ListCommentsByTargetTypeCalls gets all the calls that were made to ListCommentsByTargetType.
// Check the length with:
//
//	len(mockedStore.ListCommentsByTargetTypeCalls())
func (mock *StoreMock) ListCommentsByTargetTypeCalls() []struct {
	Ctx        context.Context
	Scope      tenancy.Scope
	TargetType comments.TargetType
	Filter     *filtering.QueryFilter
} {
	var calls []struct {
		Ctx        context.Context
		Scope      tenancy.Scope
		TargetType comments.TargetType
		Filter     *filtering.QueryFilter
	}
	mock.lockListCommentsByTargetType.RLock()
	calls = mock.calls.ListCommentsByTargetType
	mock.lockListCommentsByTargetType.RUnlock()
	return calls
}

// ListReplies calls ListRepliesFunc.
func (mock *StoreMock) ListReplies(ctx context.Context, scope tenancy.Scope, target comments.Target, parentID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error) {
	if mock.ListRepliesFunc == nil {
		panic("StoreMock.ListRepliesFunc: method is nil but Store.ListReplies was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Scope    tenancy.Scope
		Target   comments.Target
		ParentID string
		Filter   *filtering.QueryFilter
	}{
		Ctx:      ctx,
		Scope:    scope,
		Target:   target,
		ParentID: parentID,
		Filter:   filter,
	}
	mock.lockListReplies.Lock()
	mock.calls.ListReplies = append(mock.calls.ListReplies, callInfo)
	mock.lockListReplies.Unlock()
	return mock.ListRepliesFunc(ctx, scope, target, parentID, filter)
}

// ListRepliesCalls gets all the calls that were made to ListReplies.
// Check the length with:
//
//	len(mockedStore.ListRepliesCalls())
func (mock *StoreMock) ListRepliesCalls() []struct {
	Ctx      context.Context
	Scope    tenancy.Scope
	Target   comments.Target
	ParentID string
	Filter   *filtering.QueryFilter
} {
	var calls []struct {
		Ctx      context.Context
		Scope    tenancy.Scope
		Target   comments.Target
		ParentID string
		Filter   *filtering.QueryFilter
	}
	mock.lockListReplies.RLock()
	calls = mock.calls.ListReplies
	mock.lockListReplies.RUnlock()
	return calls
}

// ListRootComments calls ListRootCommentsFunc.
func (mock *StoreMock) ListRootComments(ctx context.Context, scope tenancy.Scope, target comments.Target, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[comments.Comment], error) {
	if mock.ListRootCommentsFunc == nil {
		panic("StoreMock.ListRootCommentsFunc: method is nil but Store.ListRootComments was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Scope  tenancy.Scope
		Target comments.Target
		Filter *filtering.QueryFilter
	}{
		Ctx:    ctx,
		Scope:  scope,
		Target: target,
		Filter: filter,
	}
	mock.lockListRootComments.Lock()
	mock.calls.ListRootComments = append(mock.calls.ListRootComments, callInfo)
	mock.lockListRootComments.Unlock()
	return mock.ListRootCommentsFunc(ctx, scope, target, filter)
}

// ListRootCommentsCalls gets all the calls that were made to ListRootComments.
// Check the length with:
//
//	len(mockedStore.ListRootCommentsCalls())
func (mock *StoreMock) ListRootCommentsCalls() []struct {
	Ctx    context.Context
	Scope  tenancy.Scope
	Target comments.Target
	Filter *filtering.QueryFilter
} {
	var calls []struct {
		Ctx    context.Context
		Scope  tenancy.Scope
		Target comments.Target
		Filter *filtering.QueryFilter
	}
	mock.lockListRootComments.RLock()
	calls = mock.calls.ListRootComments
	mock.lockListRootComments.RUnlock()
	return calls
}

// UpdateComment calls UpdateCommentFunc.
func (mock *StoreMock) UpdateComment(ctx context.Context, comment *comments.Comment) error {
	if mock.UpdateCommentFunc == nil {
		panic("StoreMock.UpdateCommentFunc: method is nil but Store.UpdateComment was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Comment *comments.Comment
	}{
		Ctx:     ctx,
		Comment: comment,
	}
	mock.lockUpdateComment.Lock()
	mock.calls.UpdateComment = append(mock.calls.UpdateComment, callInfo)
	mock.lockUpdateComment.Unlock()
	return mock.UpdateCommentFunc(ctx, comment)
}

// UpdateCommentCalls gets all the calls that were made to UpdateComment.
// Check the length with:
//
//	len(mockedStore.UpdateCommentCalls())
func (mock *StoreMock) UpdateCommentCalls() []struct {
	Ctx     context.Context
	Comment *comments.Comment
} {
	var calls []struct {
		Ctx     context.Context
		Comment *comments.Comment
	}
	mock.lockUpdateComment.RLock()
	calls = mock.calls.UpdateComment
	mock.lockUpdateComment.RUnlock()
	return calls
}

// UpdateCommentTx calls UpdateCommentTxFunc.
func (mock *StoreMock) UpdateCommentTx(ctx context.Context, q database.Tx, comment *comments.Comment) error {
	if mock.UpdateCommentTxFunc == nil {
		panic("StoreMock.UpdateCommentTxFunc: method is nil but Store.UpdateCommentTx was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Q       database.Tx
		Comment *comments.Comment
	}{
		Ctx:     ctx,
		Q:       q,
		Comment: comment,
	}
	mock.lockUpdateCommentTx.Lock()
	mock.calls.UpdateCommentTx = append(mock.calls.UpdateCommentTx, callInfo)
	mock.lockUpdateCommentTx.Unlock()
	return mock.UpdateCommentTxFunc(ctx, q, comment)
}

// UpdateCommentTxCalls gets all the calls that were made to UpdateCommentTx.
// Check the length with:
//
//	len(mockedStore.UpdateCommentTxCalls())
func (mock *StoreMock) UpdateCommentTxCalls() []struct {
	Ctx     context.Context
	Q       database.Tx
	Comment *comments.Comment
} {
	var calls []struct {
		Ctx     context.Context
		Q       database.Tx
		Comment *comments.Comment
	}
	mock.lockUpdateCommentTx.RLock()
	calls = mock.calls.UpdateCommentTx
	mock.lockUpdateCommentTx.RUnlock()
	return calls
}
