// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package meteringdb

import (
	"context"
)

// Querier is every query in this package, with one signature per query
// regardless of which dialect answers it.
//
// That is the point of this package: the params type, the row type, and the
// method signature are the same on every dialect, so nothing above this line
// knows or cares which database is underneath.
//
// # A note on the :execrows count
//
// MySQL reports rows *changed*: an UPDATE that sets a column to the value it
// already held affects zero rows there. Postgres and SQLite report rows
// *matched*, and count that same UPDATE as one.
//
// So a statement that gates on the count — treating zero as "not found" — is
// correct on two engines and wrong on the third. Either give it a predicate
// that discriminates, or set clientFoundRows=true in the MySQL DSN, which
// switches MySQL to matched semantics.
type Querier interface {
	// ApplyMeteringConsume runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	ApplyMeteringConsume(ctx context.Context, db DBTX, arg ApplyMeteringConsumeParams) (int64, error)
	// ClaimMeteringTotal runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	ClaimMeteringTotal(ctx context.Context, db DBTX, arg ClaimMeteringTotalParams) (int64, error)
	// FoldMeteringTotalLast runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	FoldMeteringTotalLast(ctx context.Context, db DBTX, arg FoldMeteringTotalLastParams) (int64, error)
	// FoldMeteringTotalMax runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	FoldMeteringTotalMax(ctx context.Context, db DBTX, arg FoldMeteringTotalMaxParams) (int64, error)
	// FoldMeteringTotalSum runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	FoldMeteringTotalSum(ctx context.Context, db DBTX, arg FoldMeteringTotalSumParams) (int64, error)
	// GetMeteringTotal runs the :one query.
	GetMeteringTotal(ctx context.Context, db DBTX, arg GetMeteringTotalParams) (GetMeteringTotalRow, error)
	// GetMeteringTotalForUpdate runs the :one query.
	GetMeteringTotalForUpdate(ctx context.Context, db DBTX, arg GetMeteringTotalForUpdateParams) (GetMeteringTotalForUpdateRow, error)
	// InsertMeteringEvent runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	InsertMeteringEvent(ctx context.Context, db DBTX, arg InsertMeteringEventParams) (int64, error)
	// InsertMeteringTotal runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	InsertMeteringTotal(ctx context.Context, db DBTX, arg InsertMeteringTotalParams) (int64, error)
	// MarkMeteringTotalFlushed runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	MarkMeteringTotalFlushed(ctx context.Context, db DBTX, arg MarkMeteringTotalFlushedParams) (int64, error)
	// MeteringEventExists runs the :one query.
	MeteringEventExists(ctx context.Context, db DBTX, arg MeteringEventExistsParams) (MeteringEventExistsRow, error)
	// PruneMeteringEvents runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	PruneMeteringEvents(ctx context.Context, db DBTX, arg PruneMeteringEventsParams) (int64, error)
	// ReleaseMeteringFlush runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	ReleaseMeteringFlush(ctx context.Context, db DBTX, arg ReleaseMeteringFlushParams) (int64, error)
	// SelectFlushableMeteringTotals runs the :many query.
	SelectFlushableMeteringTotals(ctx context.Context, db DBTX, arg SelectFlushableMeteringTotalsParams) ([]SelectFlushableMeteringTotalsRow, error)
}
